MLIR: lib/Dialect/Affine/Transforms/AffineLoopInvariantCodeMotion.cpp File Reference
AffineLoopInvariantCodeMotion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "licm"
Functions
static bool checkInvarianceOfNestedIfOps (Operation *op, Value indVar, SmallPtrSetImpl< Operation *> &opsWithUsers, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool isOpLoopInvariant (Operation &op, Value indVar, SmallPtrSetImpl< Operation *> &opsWithUsers, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool areAllOpsInTheBlockListInvariant (Region &blockList, Value indVar, SmallPtrSetImpl< Operation *> &opsWithUsers, SmallPtrSetImpl< Operation *> &opsToHoist)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "licm"
Definition at line 33 of file AffineLoopInvariantCodeMotion.cpp.
Function Documentation
areAllOpsInTheBlockListInvariant()
bool areAllOpsInTheBlockListInvariant (Region & blockList, Value indVar, SmallPtrSetImpl< Operation *> & opsWithUsers, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 150 of file AffineLoopInvariantCodeMotion.cpp.
References isOpLoopInvariant().
Referenced by checkInvarianceOfNestedIfOps(), and isOpLoopInvariant().
checkInvarianceOfNestedIfOps()
bool checkInvarianceOfNestedIfOps (Operation * op, Value indVar, SmallPtrSetImpl< Operation *> & opsWithUsers, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 166 of file AffineLoopInvariantCodeMotion.cpp.
References areAllOpsInTheBlockListInvariant(), isOpLoopInvariant(), mlir::Operation::moveBefore(), and mlir::Operation::use_empty().
Referenced by isOpLoopInvariant().
isOpLoopInvariant()
bool isOpLoopInvariant (Operation & op, Value indVar, SmallPtrSetImpl< Operation *> & opsWithUsers, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 65 of file AffineLoopInvariantCodeMotion.cpp.
References areAllOpsInTheBlockListInvariant(), checkInvarianceOfNestedIfOps(), mlir::Value::getDefiningOp(), mlir::getForInductionVarOwner(), mlir::getLoopIVs(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Value::getUsers(), and mlir::Value::print().
Referenced by areAllOpsInTheBlockListInvariant(), and checkInvarianceOfNestedIfOps().