MLIR: lib/Analysis/AffineAnalysis.cpp File Reference
AffineAnalysis.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "affine-analysis"
Functions
static bool dependsOnIterArgs (Value value, AffineForOp forOp)
Returns true if value (transitively) depends on iteration arguments of the given forOp.
static Value getSupportedReduction (AffineForOp forOp, unsigned pos, AtomicRMWKind &kind)
Get the value that is being reduced by pos-th reduction in the loop if such a reduction can be performed by affine parallel loops.
static LogicalResult getOpIndexSet (Operation *op, FlatAffineConstraints *indexSet)
Computes the iteration domain for 'op' and populates 'indexSet', which encapsulates the constraints involving loops surrounding 'op' and potentially involving any Function symbols.
static void buildDimAndSymbolPositionMaps (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, ValuePositionMap *valuePosMap, FlatAffineConstraints *dependenceConstraints)
static void initDependenceConstraints (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, const ValuePositionMap &valuePosMap, FlatAffineConstraints *dependenceConstraints)
static void addDomainConstraints (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, const ValuePositionMap &valuePosMap, FlatAffineConstraints *dependenceDomain)
static LogicalResult addMemRefAccessConstraints (const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, const ValuePositionMap &valuePosMap, FlatAffineConstraints *dependenceDomain)
static unsigned getNumCommonLoops (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, SmallVectorImpl< AffineForOp > *commonLoops=nullptr)
static Block * getCommonBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, const FlatAffineConstraints &srcDomain, unsigned numCommonLoops)
Returns Block common to 'srcAccess.opInst' and 'dstAccess.opInst'.
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, const FlatAffineConstraints &srcDomain, unsigned numCommonLoops)
static void addOrderingConstraints (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, unsigned loopDepth, FlatAffineConstraints *dependenceDomain)
static void computeDirectionVector (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, unsigned loopDepth, FlatAffineConstraints *dependenceDomain, SmallVector< DependenceComponent, 2 > *dependenceComponents)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-analysis"
Definition at line 30 of file AffineAnalysis.cpp.
Function Documentation
addDomainConstraints()
static void addDomainConstraints (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, const ValuePositionMap & valuePosMap, FlatAffineConstraints * dependenceDomain) static
Definition at line 500 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), and mlir::FlatAffineConstraints::getNumLocalIds().
Referenced by mlir::checkMemrefAccessDependence().
addMemRefAccessConstraints()
static LogicalResult addMemRefAccessConstraints (const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, const ValuePositionMap & valuePosMap, FlatAffineConstraints * dependenceDomain) static
Definition at line 577 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::addLocalId(), mlir::FlatAffineConstraints::atIneq(), mlir::edsc::op::eq(), mlir::failed(), mlir::failure(), mlir::AffineValueMap::getAffineMap(), mlir::getFlattenedAffineExprs(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), mlir::isValidSymbol(), mlir::FlatAffineConstraints::setIdToConstant(), and mlir::success().
Referenced by mlir::checkMemrefAccessDependence().
addOrderingConstraints()
static void addOrderingConstraints (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, unsigned loopDepth, FlatAffineConstraints * dependenceDomain) static
Definition at line 806 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::edsc::op::eq(), mlir::FlatAffineConstraints::getNumCols(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), and min().
Referenced by mlir::checkMemrefAccessDependence().
buildDimAndSymbolPositionMaps()
static void buildDimAndSymbolPositionMaps (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, ValuePositionMap * valuePosMap, FlatAffineConstraints * dependenceConstraints) static
Definition at line 344 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::getIdValues(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), and mlir::isValidSymbol().
Referenced by mlir::checkMemrefAccessDependence().
computeDirectionVector()
static void computeDirectionVector (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, unsigned loopDepth, FlatAffineConstraints * dependenceDomain, SmallVector< DependenceComponent, 2 > * dependenceComponents) static
Definition at line 832 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addDimId(), mlir::FlatAffineConstraints::addEquality(), mlir::edsc::op::eq(), mlir::FlatAffineConstraints::getConstantLowerBound(), mlir::FlatAffineConstraints::getConstantUpperBound(), mlir::FlatAffineConstraints::getNumCols(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumIds(), max(), min(), and mlir::FlatAffineConstraints::projectOut().
Referenced by mlir::checkMemrefAccessDependence().
dependsOnIterArgs()
static bool dependsOnIterArgs (Value value, AffineForOp forOp) static
Returns true if value (transitively) depends on iteration arguments of the given forOp.
Definition at line 38 of file AffineAnalysis.cpp.
References mlir::getBackwardSlice(), and mlir::Operation::getOperands().
Referenced by getSupportedReduction().
getCommonBlock()
static Block* getCommonBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, const FlatAffineConstraints & srcDomain, unsigned numCommonLoops) static
Returns Block common to 'srcAccess.opInst' and 'dstAccess.opInst'.
Definition at line 731 of file AffineAnalysis.cpp.
References mlir::Operation::getBlock(), mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getIdValue(), mlir::Block::getParentOp(), mlir::Operation::hasTrait(), mlir::MemRefAccess::opInst, and mlir::Block::push_back().
Referenced by srcAppearsBeforeDstInAncestralBlock().
getNumCommonLoops()
static unsigned getNumCommonLoops (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, SmallVectorImpl< AffineForOp > * commonLoops = nullptr) static
Definition at line 709 of file AffineAnalysis.cpp.
References mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::isForInductionVar(), and min().
Referenced by addOrderingConstraints(), mlir::checkMemrefAccessDependence(), and computeDirectionVector().
getOpIndexSet()
static LogicalResult getOpIndexSet (Operation * op, FlatAffineConstraints * indexSet) static
Computes the iteration domain for 'op' and populates 'indexSet', which encapsulates the constraints involving loops surrounding 'op' and potentially involving any Function symbols.
The dimensional identifiers in 'indexSet' correspond to the loops surrounding 'op' from outermost to innermost.
Definition at line 247 of file AffineAnalysis.cpp.
References mlir::getEnclosingAffineForAndIfOps(), and mlir::getIndexSet().
Referenced by mlir::checkMemrefAccessDependence().
getSupportedReduction()
static Value getSupportedReduction (AffineForOp forOp, unsigned pos, AtomicRMWKind & kind) static
Get the value that is being reduced by pos-th reduction in the loop if such a reduction can be performed by affine parallel loops.
This assumes floating-point operations are commutative. On success, kind will be the reduction kind suitable for use in affine parallel loop builder. If the reduction is not supported, returns null.
Definition at line 64 of file AffineAnalysis.cpp.
References dependsOnIterArgs(), and mlir::Operation::getOperand().
Referenced by mlir::isLoopParallel().
initDependenceConstraints()
static void initDependenceConstraints (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, const ValuePositionMap & valuePosMap, FlatAffineConstraints * dependenceConstraints) static
Definition at line 430 of file AffineAnalysis.cpp.
References mlir::AffineValueMap::getAffineMap(), mlir::FlatAffineConstraints::getIds(), mlir::FlatAffineConstraints::getIdValues(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), mlir::isValidSymbol(), mlir::FlatAffineConstraints::reset(), mlir::FlatAffineConstraints::setIdValue(), and mlir::FlatAffineConstraints::setIdValues().
Referenced by mlir::checkMemrefAccessDependence().
srcAppearsBeforeDstInAncestralBlock()
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, const FlatAffineConstraints & srcDomain, unsigned numCommonLoops) static
Definition at line 782 of file AffineAnalysis.cpp.
References getCommonBlock(), and mlir::MemRefAccess::opInst.
Referenced by mlir::checkMemrefAccessDependence().