MLIR: lib/Transforms/BufferOptimizations.cpp File Reference
BufferOptimizations.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/LoopLikeInterface.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/BufferUtils.h"
#include "mlir/Transforms/Passes.h"
Functions
static bool isKnownControlFlowInterface (Operation *op)
Returns true if the given operation implements a known high-level region- based control-flow interface.
static bool defaultIsSmallAlloc (Value alloc, unsigned maximumSizeInBytes, unsigned bitwidthOfIndexType, unsigned maxRankOfAllocatedMemRef)
Check if the size of the allocation is less than the given size.
static bool leavesAllocationScope (Region *parentRegion, const BufferAliasAnalysis::ValueSetT &aliases)
Checks whether the given aliases leave the allocation scope.
static bool hasAllocationScope (Value alloc, const BufferAliasAnalysis &aliasAnalysis)
Checks, if an automated allocation scope for a given alloc value exists.
Function Documentation
defaultIsSmallAlloc()
static bool defaultIsSmallAlloc (Value alloc, unsigned maximumSizeInBytes, unsigned bitwidthOfIndexType, unsigned maxRankOfAllocatedMemRef) static
Check if the size of the allocation is less than the given size.
The transformation is only applied to small buffers since large buffers could exceed the stack space.
Definition at line 33 of file BufferOptimizations.cpp.
References mlir::Type::dyn_cast(), mlir::Value::getDefiningOp(), mlir::ShapedType::getElementType(), mlir::Operation::getOperands(), mlir::Value::getType(), and mlir::Type::isIndex().
Referenced by hasAllocationScope().
hasAllocationScope()
static bool hasAllocationScope (Value alloc, const BufferAliasAnalysis & aliasAnalysis) static
Checks, if an automated allocation scope for a given alloc value exists.
Definition at line 76 of file BufferOptimizations.cpp.
References mlir::Type::cast(), mlir::Operation::create(), defaultIsSmallAlloc(), mlir::Operation::erase(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Operation::getOperands(), mlir::Value::getParentBlock(), mlir::Block::getParentOp(), mlir::Region::getParentOp(), mlir::Value::getParentRegion(), mlir::Region::getParentRegion(), mlir::BufferPlacementAllocs::getStartOperation(), mlir::Value::getType(), isKnownControlFlowInterface(), mlir::BufferPlacementTransformationBase::isLoop(), leavesAllocationScope(), mlir::Operation::moveBefore(), mlir::Operation::replaceAllUsesWith(), mlir::BufferAliasAnalysis::resolve(), and mlir::success().
isKnownControlFlowInterface()
static bool isKnownControlFlowInterface (Operation * op) static
Returns true if the given operation implements a known high-level region- based control-flow interface.
Definition at line 26 of file BufferOptimizations.cpp.
Referenced by hasAllocationScope().
leavesAllocationScope()
static bool leavesAllocationScope (Region * parentRegion, const BufferAliasAnalysis::ValueSetT & aliases) static
Checks whether the given aliases leave the allocation scope.
Definition at line 60 of file BufferOptimizations.cpp.
Referenced by hasAllocationScope().