MLIR: include/mlir-c/Support.h File Reference
Support.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
Classes
struct MlirStringRef
A pointer to a sized fragment of a string, not necessarily null-terminated.
struct MlirLogicalResult
A logical result value, essentially a boolean with named states.
Macros
#define MLIR_CAPI_EXPORTED __attribute__((visibility("default")))
Typedefs
typedef struct MlirStringRef MlirStringRef
typedef void(* MlirStringCallback) (MlirStringRef, void *)
A callback for returning string references.
typedef struct MlirLogicalResult MlirLogicalResult
Functions
static MlirStringRef mlirStringRefCreate (const char *str, size_t length)
Constructs a string reference from the pointer and length.
MLIR_CAPI_EXPORTED MlirStringRef mlirStringRefCreateFromCString (const char *str)
Constructs a string reference from a null-terminated C string.
static bool mlirLogicalResultIsSuccess (MlirLogicalResult res)
Checks if the given logical result represents a success.
static bool mlirLogicalResultIsFailure (MlirLogicalResult res)
Checks if the given logical result represents a failure.
static MlirLogicalResult mlirLogicalResultSuccess ()
Creates a logical result representing a success.
static MlirLogicalResult mlirLogicalResultFailure ()
Creates a logical result representing a failure.
Macro Definition Documentation
MLIR_CAPI_EXPORTED
#define MLIR_CAPI_EXPORTED __attribute__((visibility("default")))
Definition at line 38 of file Support.h.
Referenced by mlirAffineExprIsNull(), mlirAffineMapIsNull(), mlirAttributeIsNull(), mlirBlockIsNull(), mlirContextIsNull(), mlirDialectIsNull(), mlirExecutionEngineIsNull(), mlirIntegerSetIsNull(), mlirLocationIsNull(), mlirModuleIsNull(), mlirOperationIsNull(), mlirPassManagerIsNull(), mlirRegionIsNull(), mlirStringRefCreate(), mlirTypeIsNull(), and mlirValueIsNull().
Typedef Documentation
MlirLogicalResult
typedef struct MlirLogicalResult MlirLogicalResult
Definition at line 94 of file Support.h.
MlirStringCallback
typedef void(* MlirStringCallback) (MlirStringRef, void *)
A callback for returning string references.
This function is called back by the functions that need to return a reference to the portion of the string with the following arguments:
an MlirStringRef representing the current portion of the string
a pointer to user data forwarded from the printing call.
Definition at line 80 of file Support.h.
MlirStringRef
typedef struct MlirStringRef MlirStringRef
Definition at line 56 of file Support.h.
Function Documentation
mlirLogicalResultFailure()
static MlirLogicalResult mlirLogicalResultFailure () inline static
Creates a logical result representing a failure.
Definition at line 113 of file Support.h.
Referenced by wrap().
mlirLogicalResultIsFailure()
static bool mlirLogicalResultIsFailure (MlirLogicalResult res) inline static
Checks if the given logical result represents a failure.
Definition at line 102 of file Support.h.
References MlirLogicalResult::value.
mlirLogicalResultIsSuccess()
static bool mlirLogicalResultIsSuccess (MlirLogicalResult res) inline static
Checks if the given logical result represents a success.
Definition at line 97 of file Support.h.
References MlirLogicalResult::value.
Referenced by unwrap().
mlirLogicalResultSuccess()
static MlirLogicalResult mlirLogicalResultSuccess () inline static
Creates a logical result representing a success.
Definition at line 107 of file Support.h.
Referenced by wrap().
mlirStringRefCreate()
static MlirStringRef mlirStringRefCreate (const char * str, size_t length) inline static
Constructs a string reference from the pointer and length.
The pointer need not reference to a null-terminated string.
Definition at line 61 of file Support.h.
References MlirStringRef::data, MlirStringRef::length, MLIR_CAPI_EXPORTED, and mlirStringRefCreateFromCString().
Referenced by mlirStringRefCreateFromCString(), toMlirStringRef(), wrap(), and mlir::detail::CallbackOstream::write_impl().
mlirStringRefCreateFromCString()
MLIR_CAPI_EXPORTED MlirStringRef mlirStringRefCreateFromCString (const char * str)
Constructs a string reference from a null-terminated C string.
Prefer mlirStringRefCreate if the length of the string is known.
Definition at line 13 of file Support.cpp.
References mlirStringRefCreate().
Referenced by mlirStringRefCreate().