MLIR: mlir::MLIRContext Class Reference
mlir::MLIRContext Class Reference
MLIRContext is the top-level object for a collection of MLIR operations.
#include "mlir/IR/MLIRContext.h"
Public Member Functions
MLIRContext ()
Create a new Context.
MLIRContext (const DialectRegistry &registry)
~MLIRContext ()
std::vector< Dialect * > getLoadedDialects ()
Return information about all IR dialects loaded in the context.
const DialectRegistry & getDialectRegistry ()
Return the dialect registry associated with this context.
void appendDialectRegistry (const DialectRegistry &registry)
Append the contents of the given dialect registry to the registry associated with this context.
std::vector< StringRef > getAvailableDialects ()
Return information about all available dialects in the registry in this context.
Dialect * getLoadedDialect (StringRef name)
Get a registered IR dialect with the given namespace.
template<typename T >
T * getLoadedDialect ()
Get a registered IR dialect for the given derived dialect type.
template<typename T >
T * getOrLoadDialect ()
Get (or create) a dialect for the given derived dialect type.
template<typename Dialect >
void loadDialect ()
Load a dialect in the context.
template<typename Dialect , typename OtherDialect , typename... MoreDialects>
void loadDialect ()
Load a list dialects in the context.
void loadAllAvailableDialects ()
Load all dialects available in the registry in this context.
Dialect * getOrLoadDialect (StringRef name)
Get (or create) a dialect for the given derived dialect name.
bool allowsUnregisteredDialects ()
Return true if we allow to create operation for unregistered dialects.
void allowUnregisteredDialects (bool allow=true)
Enables creating operations in unregistered dialects.
bool isMultithreadingEnabled ()
Return true if multi-threading is enabled by the context.
void disableMultithreading (bool disable=true)
Set the flag specifying if multi-threading is disabled by the context.
void enableMultithreading (bool enable=true)
bool shouldPrintOpOnDiagnostic ()
Return true if we should attach the operation to diagnostics emitted via Operation::emit.
void printOpOnDiagnostic (bool enable)
Set the flag specifying if we should attach the operation to diagnostics emitted via Operation::emit.
bool shouldPrintStackTraceOnDiagnostic ()
Return true if we should attach the current stacktrace to diagnostics when emitted.
void printStackTraceOnDiagnostic (bool enable)
Set the flag specifying if we should attach the current stacktrace when emitting diagnostics.
std::vector< AbstractOperation * > getRegisteredOperations ()
Return information about all registered operations.
bool isOperationRegistered (StringRef name)
Return true if this operation name is registered in this context.
MLIRContextImpl & getImpl ()
DiagnosticEngine & getDiagEngine ()
Returns the diagnostic engine for this context.
StorageUniquer & getAffineUniquer ()
Returns the storage uniquer used for creating affine constructs.
StorageUniquer & getTypeUniquer ()
Returns the storage uniquer used for constructing type storage instances.
StorageUniquer & getAttributeUniquer ()
Returns the storage uniquer used for constructing attribute storage instances.
DebugActionManager & getDebugActionManager ()
Returns the manager of debug actions within the context.
void enterMultiThreadedExecution ()
These APIs are tracking whether the context will be used in a multithreading environment: this has no effect other than enabling assertions on misuses of some APIs.
void exitMultiThreadedExecution ()
Dialect * getOrLoadDialect (StringRef dialectNamespace, TypeID dialectID, function_ref< std::unique_ptr< Dialect >()> ctor)
Get a dialect for the provided namespace and TypeID: abort the program if a dialect exist for this namespace with different TypeID.
llvm::hash_code getRegistryHash ()
Returns a hash of the registry of the context that may be used to give a rough indicator of if the state of the context registry has changed.
Detailed Description
MLIRContext is the top-level object for a collection of MLIR operations.
It holds immortal uniqued objects like types, and the tables used to unique them.
MLIRContext gets a redundant "MLIR" prefix because otherwise it ends up with a very generic name ("Context") and because it is uncommon for clients to interact with it.
Definition at line 37 of file MLIRContext.h.
Constructor & Destructor Documentation
MLIRContext() [1/2]
MLIRContext::MLIRContext () explicit
Create a new Context.
Definition at line 347 of file MLIRContext.cpp.
Referenced by getImpl().
MLIRContext() [2/2]
MLIRContext::MLIRContext (const DialectRegistry & registry) explicit
Types. Floating-point Types.
Index Type.
Integer Types.
None Type.
of the above types internally. Unknown Location Attribute.
Bool Attributes.
Unit Attribute.
The empty dictionary attribute.
Definition at line 349 of file MLIRContext.cpp.
References mlir::DialectRegistry::appendTo(), clOptions, disableMultithreading(), printOpOnDiagnostic(), and printStackTraceOnDiagnostic().
~MLIRContext()
MLIRContext::~MLIRContext ()
Definition at line 412 of file MLIRContext.cpp.
Member Function Documentation
allowsUnregisteredDialects()
bool MLIRContext::allowsUnregisteredDialects ()
Return true if we allow to create operation for unregistered dialects.
Definition at line 553 of file MLIRContext.cpp.
Referenced by mlir::BoolAttr::classof(), iterateIndicesExcept(), loadDialect(), and mayBeValidWithoutTerminator().
allowUnregisteredDialects()
void MLIRContext::allowUnregisteredDialects (bool allow = true)
Enables creating operations in unregistered dialects.
Definition at line 557 of file MLIRContext.cpp.
Referenced by loadDialect(), and processBuffer().
appendDialectRegistry()
void MLIRContext::appendDialectRegistry (const DialectRegistry & registry)
Append the contents of the given dialect registry to the registry associated with this context.
Definition at line 443 of file MLIRContext.cpp.
References mlir::DialectRegistry::appendTo(), and mlir::DialectRegistry::registerDelayedInterfaces().
Referenced by mlir::registerAllDialects(), mlir::registerAMXDialectTranslation(), mlir::registerArmNeonDialectTranslation(), mlir::registerArmSVEDialectTranslation(), mlir::registerLLVMDialectTranslation(), mlir::registerNVVMDialectTranslation(), mlir::registerOpenMPDialectTranslation(), mlir::registerROCDLDialectTranslation(), mlir::registerX86VectorDialectTranslation(), mlir::PassManager::run(), and mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration().
disableMultithreading()
void MLIRContext::disableMultithreading (bool disable = true)
Set the flag specifying if multi-threading is disabled by the context.
Definition at line 567 of file MLIRContext.cpp.
Referenced by enableMultithreading(), loadDialect(), MLIRContext(), and performActions().
enableMultithreading()
void mlir::MLIRContext::enableMultithreading (bool enable = true) inline
Definition at line 113 of file MLIRContext.h.
References disableMultithreading(), getRegisteredOperations(), isOperationRegistered(), printOpOnDiagnostic(), printStackTraceOnDiagnostic(), shouldPrintOpOnDiagnostic(), and shouldPrintStackTraceOnDiagnostic().
Referenced by performActions().
enterMultiThreadedExecution()
void MLIRContext::enterMultiThreadedExecution ()
These APIs are tracking whether the context will be used in a multithreading environment: this has no effect other than enabling assertions on misuses of some APIs.
Definition at line 576 of file MLIRContext.cpp.
Referenced by getImpl(), and mlir::PassManager::run().
exitMultiThreadedExecution()
void MLIRContext::exitMultiThreadedExecution ()
Definition at line 581 of file MLIRContext.cpp.
Referenced by getImpl(), and mlir::PassManager::run().
getAffineUniquer()
StorageUniquer & MLIRContext::getAffineUniquer ()
Returns the storage uniquer used for creating affine constructs.
Definition at line 932 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::affineUniquer, getImpl(), and safeGetOrCreate().
Referenced by mlir::AffineExpr::ceilDiv(), mlir::AffineExpr::floorDiv(), mlir::getAffineConstantExpr(), getAffineDimOrSymbol(), getImpl(), mlir::AffineExpr::operator%(), mlir::AffineExpr::operator*(), and mlir::AffineExpr::operator+().
getAttributeUniquer()
StorageUniquer & MLIRContext::getAttributeUniquer ()
Returns the storage uniquer used for constructing attribute storage instances.
This should not be used directly.
Definition at line 896 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::attributeUniquer, getImpl(), mlir::AttributeStorage::getType(), mlir::AttributeStorage::initialize(), mlir::AbstractAttribute::lookup(), and mlir::AttributeStorage::setType().
Referenced by mlir::detail::AttributeUniquer::get(), getImpl(), mlir::detail::AttributeUniquer::mutate(), and mlir::detail::AttributeUniquer::registerAttribute().
getAvailableDialects()
std::vector< StringRef > MLIRContext::getAvailableDialects ()
Return information about all available dialects in the registry in this context.
Definition at line 467 of file MLIRContext.cpp.
Referenced by loadAllAvailableDialects().
getDebugActionManager()
DebugActionManager & MLIRContext::getDebugActionManager ()
Returns the manager of debug actions within the context.
Definition at line 428 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::debugActionManager, and getImpl().
Referenced by getImpl(), and processBuffer().
getDiagEngine()
DiagnosticEngine & MLIRContext::getDiagEngine ()
Returns the diagnostic engine for this context.
Definition at line 437 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::diagEngine, and getImpl().
Referenced by emitDiag(), getImpl(), and mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl().
getDialectRegistry()
const DialectRegistry & MLIRContext::getDialectRegistry ()
Return the dialect registry associated with this context.
Definition at line 451 of file MLIRContext.cpp.
Referenced by roundTripModule().
getImpl()
MLIRContextImpl& mlir::MLIRContext::getImpl () inline
Definition at line 143 of file MLIRContext.h.
References enterMultiThreadedExecution(), exitMultiThreadedExecution(), getAffineUniquer(), getAttributeUniquer(), getDebugActionManager(), getDiagEngine(), getOrLoadDialect(), getRegistryHash(), getTypeUniquer(), MLIRContext(), and mlir::registerMLIRContextCLOptions().
Referenced by mlir::Identifier::get(), mlir::AffineMap::get(), mlir::BoolAttr::get(), getAffineUniquer(), getAttributeUniquer(), getCachedIntegerType(), getDebugActionManager(), getDiagEngine(), getOrLoadDialect(), getTypeUniquer(), mlir::AbstractOperation::insert(), mlir::AbstractType::lookup(), mlir::AbstractAttribute::lookup(), and mlir::AbstractOperation::lookup().
getLoadedDialect() [1/2]
Dialect * MLIRContext::getLoadedDialect (StringRef name)
Get a registered IR dialect with the given namespace.
If an exact match is not found, then return nullptr.
If none is found, then return nullptr.
Definition at line 476 of file MLIRContext.cpp.
Referenced by mlir::BoolAttr::classof(), combineOneSpec(), mlir::Identifier::get(), iterateIndicesExcept(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), and mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait().
getLoadedDialect() [2/2]
template<typename T > T* mlir::MLIRContext::getLoadedDialect () inline
Get a registered IR dialect for the given derived dialect type.
The derived type must provide a static 'getDialectNamespace' method.
Definition at line 65 of file MLIRContext.h.
References linalg.opdsl.lang.types::T.
Referenced by getOrLoadDialect().
getLoadedDialects()
std::vector< Dialect * > MLIRContext::getLoadedDialects ()
Return information about all IR dialects loaded in the context.
Return information about all registered IR dialects.
Definition at line 456 of file MLIRContext.cpp.
Referenced by mlir::detail::DialectInterfaceCollectionBase::DialectInterfaceCollectionBase().
getOrLoadDialect() [1/3]
template<typename T > T* mlir::MLIRContext::getOrLoadDialect () inline
Get (or create) a dialect for the given derived dialect type.
The derived type must provide a static 'getDialectNamespace' method.
Definition at line 72 of file MLIRContext.h.
References linalg.opdsl.lang.types::T.
Referenced by getImpl(), mlir::DialectRegistry::insert(), loadAllAvailableDialects(), loadDialect(), mlir::detail::Parser::parseAttributeDict(), mlir::detail::Parser::parseExtendedAttr(), prepareLLVMModule(), mlir::PassManager::run(), and mlir::SDBMExpr::tryConvertAffineExpr().
getOrLoadDialect() [2/3]
Dialect * MLIRContext::getOrLoadDialect (StringRef name)
Get (or create) a dialect for the given derived dialect name.
The dialect will be loaded from the registry if no dialect is found. If no dialect is loaded for this name and none is available in the registry, returns nullptr.
Definition at line 482 of file MLIRContext.cpp.
References getLoadedDialect().
getOrLoadDialect() [3/3]
Dialect * MLIRContext::getOrLoadDialect (StringRef dialectNamespace, TypeID dialectID, function_ref< std::unique_ptr< Dialect >()> ctor)
Get a dialect for the provided namespace and TypeID: abort the program if a dialect exist for this namespace with different TypeID.
If a dialect has not been loaded for this namespace/TypeID yet, use the provided ctor to create one on the fly and load it. Returns a pointer to the dialect owned by the context. The use of this method is in general discouraged in favor of 'getOrLoadDialect<DialectClass>()'.
Returns a pointer to the dialect owned by the context.
Definition at line 495 of file MLIRContext.cpp.
References getImpl().
getRegisteredOperations()
std::vector< AbstractOperation * > MLIRContext::getRegisteredOperations ()
Return information about all registered operations.
This isn't very efficient: typically you should ask the operations about their properties directly.
This isn't very efficient, typically you should ask the operations about their properties directly.
Definition at line 614 of file MLIRContext.cpp.
Referenced by enableMultithreading().
getRegistryHash()
llvm::hash_code MLIRContext::getRegistryHash ()
Returns a hash of the registry of the context that may be used to give a rough indicator of if the state of the context registry has changed.
The context registry correlates to loaded dialects and their entities (attributes, operations, types, etc.).
Definition at line 543 of file MLIRContext.cpp.
Referenced by getImpl(), and mlir::PassManager::run().
getTypeUniquer()
StorageUniquer & MLIRContext::getTypeUniquer ()
Returns the storage uniquer used for constructing type storage instances.
This should not be used directly.
Definition at line 812 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::bf16Ty, mlir::MLIRContextImpl::f128Ty, mlir::MLIRContextImpl::f16Ty, mlir::MLIRContextImpl::f32Ty, mlir::MLIRContextImpl::f64Ty, mlir::MLIRContextImpl::f80Ty, getImpl(), mlir::MLIRContextImpl::indexTy, and mlir::MLIRContextImpl::typeUniquer.
Referenced by mlir::detail::TypeUniquer::get(), getImpl(), mlir::detail::TypeUniquer::mutate(), and mlir::detail::TypeUniquer::registerType().
isMultithreadingEnabled()
bool MLIRContext::isMultithreadingEnabled ()
Return true if multi-threading is enabled by the context.
Return true if multi-threading is disabled by the context.
Definition at line 562 of file MLIRContext.cpp.
Referenced by mlir::PassManager::enableIRPrinting(), mlir::Identifier::get(), inlineCallsInSCC(), loadDialect(), and performActions().
isOperationRegistered()
bool MLIRContext::isOperationRegistered (StringRef name)
Return true if this operation name is registered in this context.
Definition at line 634 of file MLIRContext.cpp.
Referenced by enableMultithreading().
loadAllAvailableDialects()
void MLIRContext::loadAllAvailableDialects ()
Load all dialects available in the registry in this context.
Definition at line 538 of file MLIRContext.cpp.
References getAvailableDialects(), and getOrLoadDialect().
Referenced by loadDialect(), processBuffer(), and roundTripModule().
loadDialect() [1/2]
template<typename Dialect > void mlir::MLIRContext::loadDialect () inline
Load a dialect in the context.
Definition at line 82 of file MLIRContext.h.
Referenced by deserializeModule(), loadDialect(), and mlir::translateLLVMIRToModule().
loadDialect() [2/2]
template<typename Dialect , typename OtherDialect , typename... MoreDialects> void mlir::MLIRContext::loadDialect () inline
Load a list dialects in the context.
Definition at line 88 of file MLIRContext.h.
References allowsUnregisteredDialects(), allowUnregisteredDialects(), disableMultithreading(), getOrLoadDialect(), isMultithreadingEnabled(), loadAllAvailableDialects(), and loadDialect().
printOpOnDiagnostic()
void MLIRContext::printOpOnDiagnostic (bool enable)
Set the flag specifying if we should attach the operation to diagnostics emitted via Operation::emit.
Definition at line 595 of file MLIRContext.cpp.
Referenced by enableMultithreading(), MLIRContext(), mlir::mlirTranslateMain(), and processBuffer().
printStackTraceOnDiagnostic()
void MLIRContext::printStackTraceOnDiagnostic (bool enable)
Set the flag specifying if we should attach the current stacktrace when emitting diagnostics.
Definition at line 607 of file MLIRContext.cpp.
Referenced by enableMultithreading(), and MLIRContext().
shouldPrintOpOnDiagnostic()
bool MLIRContext::shouldPrintOpOnDiagnostic ()
Return true if we should attach the operation to diagnostics emitted via Operation::emit.
Definition at line 589 of file MLIRContext.cpp.
Referenced by enableMultithreading().
shouldPrintStackTraceOnDiagnostic()
bool MLIRContext::shouldPrintStackTraceOnDiagnostic ()
Return true if we should attach the current stacktrace to diagnostics when emitted.
Definition at line 601 of file MLIRContext.cpp.
Referenced by emitDiag(), and enableMultithreading().
The documentation for this class was generated from the following files:
include/mlir/IR/MLIRContext.h
lib/IR/MLIRContext.cpp