MLIR: linalg.opdsl.lang.comprehension.TensorExpression Class Reference
linalg.opdsl.lang.comprehension.TensorExpression Class Reference
Public Member Functions
def to_scalar_expression (self)
def visit_tensor_exprs (self, callback)
def collect_uses
def collect_indices
def collect_captures
def __add__
def __mul__ (self, rhs)
def __sub__ (self, rhs)
def __hash__ (self)
Detailed Description
An expression that can appear on the RHS of a comprehension.
Definition at line 24 of file comprehension.py.
Member Function Documentation
__add__()
def linalg.opdsl.lang.comprehension.TensorExpression.__add__ (self, rhs)
Definition at line 74 of file comprehension.py.
__hash__()
def linalg.opdsl.lang.comprehension.TensorExpression.__hash__ (self)
Definition at line 83 of file comprehension.py.
__mul__()
def linalg.opdsl.lang.comprehension.TensorExpression.__mul__ (self, rhs, TensorExpression)
Definition at line 77 of file comprehension.py.
__sub__()
def linalg.opdsl.lang.comprehension.TensorExpression.__sub__ (self, rhs, TensorExpression)
Definition at line 80 of file comprehension.py.
collect_captures()
def linalg.opdsl.lang.comprehension.TensorExpression.collect_captures (self, captures)
Definition at line 67 of file comprehension.py.
References linalg.opdsl.lang.comprehension.TensorExpression.visit_tensor_exprs().
collect_indices()
def linalg.opdsl.lang.comprehension.TensorExpression.collect_indices (self, indices)
Definition at line 60 of file comprehension.py.
References linalg.opdsl.lang.comprehension.TensorExpression.visit_tensor_exprs().
collect_uses()
def linalg.opdsl.lang.comprehension.TensorExpression.collect_uses (self, uses)
Definition at line 53 of file comprehension.py.
References linalg.opdsl.lang.comprehension.TensorExpression.visit_tensor_exprs().
to_scalar_expression()
def linalg.opdsl.lang.comprehension.TensorExpression.to_scalar_expression (self, ScalarExpression)
Definition at line 27 of file comprehension.py.
visit_tensor_exprs()
def linalg.opdsl.lang.comprehension.TensorExpression.visit_tensor_exprs (self, callback)
Visits all tensor expression reachable by the expression.
Definition at line 30 of file comprehension.py.
References linalg.opdsl.lang.comprehension.TensorExpression.visit_tensor_exprs().
Referenced by linalg.opdsl.lang.comprehension.TensorExpression.collect_captures(), linalg.opdsl.lang.comprehension.TensorExpression.collect_indices(), linalg.opdsl.lang.comprehension.TensorExpression.collect_uses(), and linalg.opdsl.lang.comprehension.TensorExpression.visit_tensor_exprs().
The documentation for this class was generated from the following file:
lib/Bindings/Python/mlir/dialects/linalg/opdsl/lang/comprehension.py