MLIR: mlir::LLVM::TypeFromLLVMIRTranslator Class Reference
mlir::LLVM::TypeFromLLVMIRTranslator Class Reference
Utility class to translate LLVM IR types to the MLIR LLVM dialect.
Public Member Functions
TypeFromLLVMIRTranslator (MLIRContext &context)
~TypeFromLLVMIRTranslator ()
Type translateType (llvm::Type *type)
Translates the given LLVM IR type to the MLIR LLVM dialect.
Detailed Description
Utility class to translate LLVM IR types to the MLIR LLVM dialect.
Stores the translation state, in particular any identified structure types that are reused across translations.
Definition at line 184 of file ConvertFromLLVMIR.cpp.
Constructor & Destructor Documentation
TypeFromLLVMIRTranslator()
LLVM::TypeFromLLVMIRTranslator::TypeFromLLVMIRTranslator (MLIRContext & context)
Definition at line 200 of file ConvertFromLLVMIR.cpp.
~TypeFromLLVMIRTranslator()
LLVM::TypeFromLLVMIRTranslator::~TypeFromLLVMIRTranslator ()
Definition at line 203 of file ConvertFromLLVMIR.cpp.
Member Function Documentation
translateType()
Type LLVM::TypeFromLLVMIRTranslator::translateType (llvm::Type * type)
Translates the given LLVM IR type to the MLIR LLVM dialect.
Definition at line 205 of file ConvertFromLLVMIR.cpp.
References mlir::OperationState::addTypes(), mlir::Block::begin(), mlir::Constant, diag(), mlir::Type::dyn_cast(), mlir::Type::dyn_cast_or_null(), elementType(), mlir::emitError(), mlir::failed(), mlir::DenseElementsAttr::get(), mlir::FloatType::getF32(), mlir::FloatType::getF64(), mlir::LLVM::getVectorElementType(), mlir::LLVM::getVectorNumElements(), mlir::Type::isa(), mlir::LLVM::isCompatibleVectorType(), and processValue().
The documentation for this class was generated from the following file:
lib/Target/LLVMIR/ConvertFromLLVMIR.cpp