MLIR: linalg.opdsl.lang.dsl.DefinedOpCallable Class Reference
linalg.opdsl.lang.dsl.DefinedOpCallable Class Reference
Public Member Functions
def __init__
def __call__
Public Attributes
op_name
model
Detailed Description
Callable that wraps any defined op function.
Definition at line 40 of file dsl.py.
Constructor & Destructor Documentation
__init__()
def linalg.opdsl.lang.dsl.DefinedOpCallable.__init__ (self, op_name)
Definition at line 43 of file dsl.py.
Member Function Documentation
__call__()
def linalg.opdsl.lang.dsl.DefinedOpCallable.__call__ (self, args, emit_generic)
Definition at line 47 of file dsl.py.
References linalg.opdsl.lang.emitter.emit_generic_structured_op(), linalg.opdsl.lang.emitter.emit_named_structured_op(), linalg.opdsl.lang.dsl.linalg_structured_op(), linalg.opdsl.lang.dsl.DefinedOpCallable.model, and linalg.opdsl.lang.dsl.DefinedOpCallable.op_name.
Member Data Documentation
model
linalg.opdsl.lang.dsl.DefinedOpCallable.model
Definition at line 45 of file dsl.py.
Referenced by linalg.opdsl.lang.dsl.DefinedOpCallable.__call__().
op_name
linalg.opdsl.lang.dsl.DefinedOpCallable.op_name
Definition at line 44 of file dsl.py.
Referenced by linalg.opdsl.lang.dsl.DefinedOpCallable.__call__().
The documentation for this class was generated from the following file:
lib/Bindings/Python/mlir/dialects/linalg/opdsl/lang/dsl.py