MLIR: mlir::AsmParserState Class Reference
mlir::AsmParserState Class Reference
This class represents state from a parsed MLIR textual format string.
#include "mlir/Parser/AsmParserState.h"
Classes
struct BlockDefinition
This class represents the information for a block definition within the input file.
struct Impl
struct OperationDefinition
This class represents the information for an operation definition within an input file.
struct SMDefinition
This class represents a definition within the source manager, containing it's defining location and locations of any uses.
Public Types
using BlockDefIterator = llvm::pointee_iterator< ArrayRef< std::unique_ptr< BlockDefinition > >::iterator >
using OperationDefIterator = llvm::pointee_iterator< ArrayRef< std::unique_ptr< OperationDefinition > >::iterator >
Public Member Functions
AsmParserState ()
~AsmParserState ()
iterator_range< BlockDefIterator > getBlockDefs () const
Return a range of the BlockDefinitions held by the current parser state.
iterator_range< OperationDefIterator > getOpDefs () const
Return a range of the OperationDefinitions held by the current parser state.
void addDefinition (Operation *op, llvm::SMRange location, ArrayRef< std::pair< unsigned, llvm::SMLoc >> resultGroups=llvm::None)
Add a definition of the given operation.
void addDefinition (Block *block, llvm::SMLoc location)
void addDefinition (BlockArgument blockArg, llvm::SMLoc location)
void addUses (Value value, ArrayRef< llvm::SMLoc > locations)
Add a source uses of the given value.
void addUses (Block *block, ArrayRef< llvm::SMLoc > locations)
void refineDefinition (Value oldValue, Value newValue)
Refine the oldValue to the newValue.
Detailed Description
This class represents state from a parsed MLIR textual format string.
It is useful for building additional analysis and language utilities on top of textual MLIR. This should generally not be used for traditional compilation.
Definition at line 28 of file AsmParserState.h.
Member Typedef Documentation
BlockDefIterator
using mlir::AsmParserState::BlockDefIterator = llvm::pointee_iterator< ArrayRef<std::unique_ptr<BlockDefinition> >::iterator>
Definition at line 91 of file AsmParserState.h.
OperationDefIterator
using mlir::AsmParserState::OperationDefIterator = llvm::pointee_iterator< ArrayRef<std::unique_ptr<OperationDefinition> >::iterator>
Definition at line 93 of file AsmParserState.h.
Constructor & Destructor Documentation
AsmParserState()
AsmParserState::AsmParserState ()
Definition at line 53 of file AsmParserState.cpp.
~AsmParserState()
AsmParserState::~AsmParserState ()
Definition at line 54 of file AsmParserState.cpp.
Member Function Documentation
addDefinition() [1/3]
void AsmParserState::addDefinition (Operation * op, llvm::SMRange location, ArrayRef< std::pair< unsigned, llvm::SMLoc >> resultGroups = llvm::None)
Add a definition of the given operation.
Definition at line 70 of file AsmParserState.cpp.
References convertIdLocToRange().
Referenced by mlir::detail::Parser::parseFloatFromIntegerLiteral().
addDefinition() [2/3]
void AsmParserState::addDefinition (Block * block, llvm::SMLoc location)
Definition at line 83 of file AsmParserState.cpp.
References convertIdLocToRange().
addDefinition() [3/3]
void AsmParserState::addDefinition (BlockArgument blockArg, llvm::SMLoc location)
Definition at line 97 of file AsmParserState.cpp.
References convertIdLocToRange(), mlir::BlockArgument::getArgNumber(), and mlir::BlockArgument::getOwner().
addUses() [1/2]
void AsmParserState::addUses (Value value, ArrayRef< llvm::SMLoc > locations)
Add a source uses of the given value.
Definition at line 110 of file AsmParserState.cpp.
References mlir::Value::cast(), convertIdLocToRange(), mlir::Value::dyn_cast(), mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), mlir::AsmParserState::OperationDefinition::resultGroups, and mlir::AsmParserState::SMDefinition::uses.
Referenced by mlir::detail::Parser::parseFloatFromIntegerLiteral(), and refineDefinition().
addUses() [2/2]
void AsmParserState::addUses (Block * block, ArrayRef< llvm::SMLoc > locations)
Definition at line 150 of file AsmParserState.cpp.
References convertIdLocToRange(), mlir::AsmParserState::BlockDefinition::definition, and mlir::AsmParserState::SMDefinition::uses.
getBlockDefs()
auto AsmParserState::getBlockDefs () const
Return a range of the BlockDefinitions held by the current parser state.
Definition at line 59 of file AsmParserState.cpp.
getOpDefs()
auto AsmParserState::getOpDefs () const
Return a range of the OperationDefinitions held by the current parser state.
Definition at line 63 of file AsmParserState.cpp.
refineDefinition()
void AsmParserState::refineDefinition (Value oldValue, Value newValue)
Refine the oldValue to the newValue.
This is used to indicate that oldValue was a placeholder, and the uses of it should really refer to newValue.
Definition at line 162 of file AsmParserState.cpp.
References addUses().
Referenced by mlir::detail::Parser::parseFloatFromIntegerLiteral().
The documentation for this class was generated from the following files:
include/mlir/Parser/AsmParserState.h
lib/Parser/AsmParserState.cpp