MLIR: mlir::RewritePattern Class Reference
mlir::RewritePattern Class Reference
RewritePattern is the common base class for all DAG to DAG replacements.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
Protected Member Functions
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
RewritePattern is the common base class for all DAG to DAG replacements.
There are two possible usages of this class:
Multi-step RewritePattern with "match" and "rewrite"
By overloading the "match" and "rewrite" functions, the user can separate the concerns of matching and rewriting.
Single-step RewritePattern with "matchAndRewrite"
By overloading the "matchAndRewrite" function, the user can perform the rewrite in the same call as the match.
Definition at line 220 of file PatternMatch.h.
Constructor & Destructor Documentation
~RewritePattern()
virtual mlir::RewritePattern::~RewritePattern () inline virtual
Definition at line 222 of file PatternMatch.h.
References rewrite().
Member Function Documentation
anchor()
void RewritePattern::anchor () protected virtual
An anchor for the virtual table.
Out-of-line vtable anchor.
Definition at line 96 of file PatternMatch.cpp.
match()
LogicalResult RewritePattern::match (Operation * op) const virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Reimplemented in mlir::ConvertOpToLLVMPattern< SourceOp >, mlir::ConvertOpToLLVMPattern< Op >, mlir::ConvertOpToLLVMPattern< gpu::GPUFuncOp >, mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >, mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< CopyOp >, mlir::detail::OpOrInterfaceRewritePatternBase< IndexedGenericOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ExtractStridedSliceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::BitCastOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::CreateMaskOp >, mlir::detail::OpOrInterfaceRewritePatternBase< T >, mlir::detail::OpOrInterfaceRewritePatternBase< ConcreteOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ExtractOp >, mlir::detail::OpOrInterfaceRewritePatternBase< LinalgOp >, mlir::detail::OpOrInterfaceRewritePatternBase< AddOpType >, mlir::detail::OpOrInterfaceRewritePatternBase< AffineMinOp >, mlir::detail::OpOrInterfaceRewritePatternBase< ExtractMapOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferReadOp >, mlir::detail::OpOrInterfaceRewritePatternBase< ConvOp >, mlir::detail::OpOrInterfaceRewritePatternBase< OpType >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferWriteOp >, mlir::detail::OpOrInterfaceRewritePatternBase< PadTensorOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::InsertStridedSliceOp >, and mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >.
Definition at line 91 of file PatternMatch.cpp.
matchAndRewrite()
virtual LogicalResult mlir::RewritePattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented in mlir::linalg::LinalgLoweringPattern< OpTy >, mlir::linalg::LinalgBaseVectorizationPattern, mlir::linalg::LinalgBasePromotionPattern, mlir::linalg::LinalgBaseInterchangePattern, mlir::VectorTransferRewriter< TransferOpTy >, mlir::linalg::LinalgBaseTileAndFusePattern, mlir::linalg::LinalgTilingPattern< OpTy >, mlir::VectorTransferRewriter< TransferOpTy >, mlir::ConversionPattern, mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< CopyOp >, mlir::detail::OpOrInterfaceRewritePatternBase< IndexedGenericOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ExtractStridedSliceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::BitCastOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::CreateMaskOp >, mlir::detail::OpOrInterfaceRewritePatternBase< T >, mlir::detail::OpOrInterfaceRewritePatternBase< ConcreteOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ExtractOp >, mlir::detail::OpOrInterfaceRewritePatternBase< LinalgOp >, mlir::detail::OpOrInterfaceRewritePatternBase< AddOpType >, mlir::detail::OpOrInterfaceRewritePatternBase< AffineMinOp >, mlir::detail::OpOrInterfaceRewritePatternBase< ExtractMapOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferReadOp >, mlir::detail::OpOrInterfaceRewritePatternBase< ConvOp >, mlir::detail::OpOrInterfaceRewritePatternBase< OpType >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferWriteOp >, mlir::detail::OpOrInterfaceRewritePatternBase< PadTensorOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::InsertStridedSliceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >, mlir::vector::VectorTransferFullPartialRewriter, mlir::VectorTransferRewriter< TransferOpTy >, and mlir::vector::UnrollVectorPattern.
Definition at line 238 of file PatternMatch.h.
References mlir::failure(), mlir::Pattern::Pattern(), rewrite(), mlir::succeeded(), and mlir::success().
rewrite()
void RewritePattern::rewrite (Operation * op, PatternRewriter & rewriter) const virtual
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
If an unexpected error is encountered (an internal compiler error), it is emitted through the normal MLIR diagnostic hooks and the IR is left in a valid state.
Reimplemented in mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< CopyOp >, mlir::detail::OpOrInterfaceRewritePatternBase< IndexedGenericOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ExtractStridedSliceOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::BitCastOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::CreateMaskOp >, mlir::detail::OpOrInterfaceRewritePatternBase< T >, mlir::detail::OpOrInterfaceRewritePatternBase< ConcreteOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::ExtractOp >, mlir::detail::OpOrInterfaceRewritePatternBase< LinalgOp >, mlir::detail::OpOrInterfaceRewritePatternBase< AddOpType >, mlir::detail::OpOrInterfaceRewritePatternBase< AffineMinOp >, mlir::detail::OpOrInterfaceRewritePatternBase< ExtractMapOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferReadOp >, mlir::detail::OpOrInterfaceRewritePatternBase< ConvOp >, mlir::detail::OpOrInterfaceRewritePatternBase< OpType >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::TransferWriteOp >, mlir::detail::OpOrInterfaceRewritePatternBase< PadTensorOp >, mlir::detail::OpOrInterfaceRewritePatternBase< vector::InsertStridedSliceOp >, and mlir::detail::OpOrInterfaceRewritePatternBase< vector::ContractionOp >.
Definition at line 86 of file PatternMatch.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp