MLIR: mlir::lsp::Reply Class Reference
mlir::lsp::Reply Class Reference
Function object to reply to an LSP call.
#include "Tools/mlir-lsp-server/lsp/Transport.h"
Public Member Functions
Reply (const llvm::json::Value &id, StringRef method, JSONTransport &transport)
Reply (Reply &&other)
Reply & operator= (Reply &&)=delete
Reply (const Reply &)=delete
Reply & operator= (const Reply &)=delete
void operator() (llvm::Expected< llvm::json::Value > reply)
Detailed Description
Function object to reply to an LSP call.
Each instance must be called exactly once, otherwise:
if there was no reply, an error reply is sent
if there were multiple replies, only the first is sent
Definition at line 41 of file Transport.h.
Constructor & Destructor Documentation
Reply() [1/3]
mlir::lsp::Reply::Reply (const llvm::json::Value & id, StringRef method, JSONTransport & transport)
Reply() [2/3]
Reply::Reply (Reply && other)
Definition at line 28 of file Transport.cpp.
Reply() [3/3]
mlir::lsp::Reply::Reply (const Reply &) delete
Member Function Documentation
operator()()
void Reply::operator() (llvm::Expected< llvm::json::Value > reply)
Definition at line 34 of file Transport.cpp.
References mlir::lsp::Logger::error(), mlir::Error, mlir::lsp::Logger::info(), and mlir::lsp::JSONTransport::reply().
operator=() [1/2]
Reply& mlir::lsp::Reply::operator= (Reply &&) delete
operator=() [2/2]
Reply& mlir::lsp::Reply::operator= (const Reply &) delete
The documentation for this class was generated from the following files:
lib/Tools/mlir-lsp-server/lsp/Transport.h
lib/Tools/mlir-lsp-server/lsp/Transport.cpp