MLIR: lib/Transforms/Utils/DialectConversion.cpp File Reference
DialectConversion.cpp File Reference
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/FunctionSupport.h"
#include "mlir/Rewrite/PatternApplicator.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/ScopedPrinter.h"
Classes
struct mlir::detail::ConversionPatternRewriterImpl
Namespaces
mlir
Include the generated interface declarations.
mlir::detail
Macros
#define DEBUG_TYPE "dialect-conversion"
Enumerations
enum BlockActionKind
The kind of the block action performed during the rewrite.
enum OpConversionMode
Functions
static LogicalResult computeConversionSet (iterator_range< Region::iterator > region, Location regionLoc, std::vector< Operation *> &toConvert, ConversionTarget *target=nullptr)
Recursively collect all of the operations to convert from within 'region'.
template<typename... Args>
static void logSuccess (llvm::ScopedPrinter &os, StringRef fmt, Args &&...args)
A utility function to log a successful result for the given reason.
template<typename... Args>
static void logFailure (llvm::ScopedPrinter &os, StringRef fmt, Args &&...args)
A utility function to log a failure result for the given reason.
static void detachNestedAndErase (Operation *op)
Detach any operations nested in the given operation from their parent blocks, and erase the given operation.
static Operation * findLiveUserOfReplaced (Value value, ConversionPatternRewriterImpl &rewriterImpl, const BlockAndValueMapping &inverseMapping)
Finds a user of the given value, or of any other value that the given value replaced, that was not replaced in the conversion process.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dialect-conversion"
Definition at line 27 of file DialectConversion.cpp.
Enumeration Type Documentation
BlockActionKind
enum BlockActionKind strong
The kind of the block action performed during the rewrite.
Actions can be undone if the conversion fails.
Definition at line 618 of file DialectConversion.cpp.
OpConversionMode
enum OpConversionMode
Definition at line 2142 of file DialectConversion.cpp.
Function Documentation
computeConversionSet()
static LogicalResult computeConversionSet (iterator_range< Region::iterator > region, Location regionLoc, std::vector< Operation *> & toConvert, ConversionTarget * target = nullptr) static
Recursively collect all of the operations to convert from within 'region'.
If 'target' is nonnull, operations that are recursively legal have their regions pre-filtered to avoid considering them for legalization.
Definition at line 33 of file DialectConversion.cpp.
References mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Block::getSuccessors(), and mlir::success().
Referenced by mlir::detail::ConversionPatternRewriterImpl::notifyRegionWasClonedBefore().
detachNestedAndErase()
static void detachNestedAndErase (Operation * op) static
Detach any operations nested in the given operation from their parent blocks, and erase the given operation.
This can be used when the nested operations are scheduled for erasure themselves, so deleting the regions of the given operation together with their content would result in double-free. This happens, for example, when rolling back op creation in the reverse order and if the nested ops were created before the parent op. This function does not need to collect nested ops recursively because it is expected to also be called for each nested op when it is about to be deleted.
Definition at line 871 of file DialectConversion.cpp.
References mlir::Block::dropAllDefinedValueUses(), mlir::Operation::dropAllUses(), mlir::Operation::erase(), mlir::Block::getOperations(), and mlir::Operation::getRegions().
Referenced by mlir::detail::ConversionPatternRewriterImpl::discardRewrites(), and mlir::detail::ConversionPatternRewriterImpl::resetState().
findLiveUserOfReplaced()
static Operation* findLiveUserOfReplaced (Value value, ConversionPatternRewriterImpl & rewriterImpl, const BlockAndValueMapping & inverseMapping) static
Finds a user of the given value, or of any other value that the given value replaced, that was not replaced in the conversion process.
Definition at line 2387 of file DialectConversion.cpp.
References mlir::InFlightDiagnostic::attachNote(), mlir::detail::ConversionPatternRewriterImpl::createdOps, diag(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), mlir::BlockAndValueMapping::lookupOrNull(), mlir::detail::ConversionPatternRewriterImpl::mapping, mlir::TypeConverter::materializeSourceConversion(), mlir::success(), and mlir::Value::user_end().
logFailure()
template<typename... Args> static void logFailure (llvm::ScopedPrinter & os, StringRef fmt, Args &&... args) static
A utility function to log a failure result for the given reason.
Definition at line 91 of file DialectConversion.cpp.
References mlir::Block::addArguments(), mlir::InFlightDiagnostic::attachNote(), mlir::Block::begin(), mlir::TypeConverter::convertBlockSignature(), diag(), mlir::IRObjectWithUseList< OperandType >::dropAllUses(), mlir::Value::dropAllUses(), mlir::Value::dyn_cast(), mlir::emitError(), mlir::Block::end(), mlir::detail::enumerate(), mlir::Block::erase(), mlir::failure(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Operation::getAttrDictionary(), mlir::Region::getBlocks(), mlir::TypeConverter::SignatureConversion::getConvertedTypes(), mlir::TypeConverter::SignatureConversion::getInputMapping(), mlir::BlockAndValueMapping::getInverse(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Block::getNumArguments(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::Region::getParentOp(), mlir::Operation::getRegions(), mlir::Value::getType(), mlir::TypeConverter::materializeArgumentConversion(), mlir::Block::moveBefore(), mlir::Operation::operand_begin(), mlir::Operation::operand_end(), mlir::IRObjectWithUseList< OperandType >::replaceAllUsesWith(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setAttrs(), mlir::Operation::setLoc(), mlir::Operation::setOperands(), mlir::Operation::setSuccessor(), mlir::Block::splitBlock(), mlir::success(), mlir::Operation::successor_begin(), mlir::Operation::successor_end(), and mlir::Value::use_empty().
Referenced by mlir::ConversionPattern::matchAndRewrite().
logSuccess()
template<typename... Args> static void logSuccess (llvm::ScopedPrinter & os, StringRef fmt, Args &&... args) static
A utility function to log a successful result for the given reason.
Definition at line 78 of file DialectConversion.cpp.
Referenced by mlir::ConversionPattern::matchAndRewrite().