MLIR: lib/Parser/DialectSymbolParser.cpp File Reference
DialectSymbolParser.cpp File Reference
#include "Parser.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/Support/SourceMgr.h"
Functions
template<typename Symbol , typename SymbolAliasMap , typename CreateFn >
static Symbol parseExtendedSymbol (Parser &p, Token::Kind identifierTok, SymbolAliasMap &aliases, CreateFn &&createSymbol)
Parse an extended dialect symbol.
template<typename T , typename ParserFn >
static T parseSymbol (StringRef inputStr, MLIRContext *context, SymbolState &symbolState, ParserFn &&parserFn, size_t *numRead=nullptr)
Parses a symbol, of type 'T', and returns it if parsing was successful.
template<typename T , typename ParserFn >
static T parseSymbol (StringRef inputStr, MLIRContext *context, size_t &numRead, ParserFn &&parserFn)
Parses a symbol, of type 'T', and returns it if parsing was successful.
Function Documentation
parseExtendedSymbol()
template<typename Symbol , typename SymbolAliasMap , typename CreateFn > static Symbol parseExtendedSymbol (Parser & p, Token::Kind identifierTok, SymbolAliasMap & aliases, CreateFn && createSymbol) static
Parse an extended dialect symbol.
Definition at line 408 of file DialectSymbolParser.cpp.
References mlir::detail::Parser::consumeToken(), mlir::detail::Parser::emitError(), mlir::Token::getLoc(), mlir::detail::Parser::getState(), mlir::Token::getStringValue(), mlir::detail::Parser::getToken(), mlir::detail::Parser::getTokenSpelling(), mlir::Token::is(), mlir::Token::isNot(), mlir::detail::SymbolState::nestedParserLocs, mlir::detail::Parser::parsePrettyDialectSymbolName(), mlir::detail::Parser::parseToken(), mlir::detail::Parser::remapLocationToTopLevelBuffer(), and mlir::detail::ParserState::symbols.
parseSymbol() [1/2]
template<typename T , typename ParserFn > static T parseSymbol (StringRef inputStr, MLIRContext * context, SymbolState & symbolState, ParserFn && parserFn, size_t * numRead = nullptr) static
Parses a symbol, of type 'T', and returns it if parsing was successful.
If parsing failed, nullptr is returned. The number of bytes read from the input string is returned in 'numRead'.
Definition at line 485 of file DialectSymbolParser.cpp.
References mlir::detail::Parser::emitError(), mlir::Token::getLoc(), mlir::detail::Parser::getToken(), mlir::Token::isNot(), and linalg.opdsl.lang.types::T.
parseSymbol() [2/2]
template<typename T , typename ParserFn > static T parseSymbol (StringRef inputStr, MLIRContext * context, size_t & numRead, ParserFn && parserFn) static
Parses a symbol, of type 'T', and returns it if parsing was successful.
If parsing failed, nullptr is returned. The number of bytes read from the input string is returned in 'numRead'.
Definition at line 596 of file DialectSymbolParser.cpp.
References mlir::Type::getContext(), mlir::parseAttribute(), and mlir::parseType().