MLIR: lib/Dialect/Linalg/Transforms/DropUnitDims.cpp File Reference
DropUnitDims.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "linalg-drop-unit-dims"
Functions
static ArrayAttr replaceUnitDims (DenseSet< unsigned > &unitDims, ArrayRef< AffineMap > indexingMaps, MLIRContext *context)
Implements a pass that canonicalizes the uses of unit-extent dimensions for broadcasting.
template<typename GenericOpTy >
static void replaceUnitDimIndexOps (GenericOpTy op, const DenseSet< unsigned > &unitDims, PatternRewriter &rewriter)
Update the index accesses of linalg operations having index semantics.
template<typename OpTy >
static LogicalResult replaceBlockArgForUnitDimLoops (OpTy op, const DenseSet< unsigned > &unitDims, PatternRewriter &rewriterp)
Modify the region of indexed generic op to drop arguments corresponding to loops that are unit trip count.
template<>
LogicalResult replaceBlockArgForUnitDimLoops< IndexedGenericOp > (IndexedGenericOp op, const DenseSet< unsigned > &unitDims, PatternRewriter &rewriter)
static UnitExtentReplacementInfo replaceUnitExtents (AffineMap indexMap, RankedTensorType type, MLIRContext *context)
Utility function for replacing operands/results to a linalg generic operation on tensors with unit-extent dimensions.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-drop-unit-dims"
Definition at line 29 of file DropUnitDims.cpp.
Function Documentation
replaceBlockArgForUnitDimLoops()
template<typename OpTy > static LogicalResult replaceBlockArgForUnitDimLoops (OpTy op, const DenseSet< unsigned > & unitDims, PatternRewriter & rewriterp) static
Modify the region of indexed generic op to drop arguments corresponding to loops that are unit trip count.
Definition at line 177 of file DropUnitDims.cpp.
References mlir::success().
Referenced by replaceBlockArgForUnitDimLoops< IndexedGenericOp >().
replaceBlockArgForUnitDimLoops< IndexedGenericOp >()
template<> LogicalResult replaceBlockArgForUnitDimLoops< IndexedGenericOp > (IndexedGenericOp op, const DenseSet< unsigned > & unitDims, PatternRewriter & rewriter)
Definition at line 183 of file DropUnitDims.cpp.
References mlir::AffineExpr::cast(), mlir::concatAffineMaps(), mlir::AffineExpr::dyn_cast(), mlir::detail::enumerate(), mlir::Block::eraseArguments(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Builder::getContext(), mlir::linalg::getDimsOfType(), mlir::getReductionIteratorTypeName(), mlir::AffineMap::getResults(), mlir::inversePermutation(), mlir::isParallelIterator(), mlir::isReductionIterator(), mlir::Value::replaceAllUsesWith(), replaceBlockArgForUnitDimLoops(), replaceUnitDimIndexOps(), replaceUnitDims(), mlir::RewriterBase::startRootUpdate(), and mlir::success().
replaceUnitDimIndexOps()
template<typename GenericOpTy > static void replaceUnitDimIndexOps (GenericOpTy op, const DenseSet< unsigned > & unitDims, PatternRewriter & rewriter) static
Update the index accesses of linalg operations having index semantics.
Definition at line 150 of file DropUnitDims.cpp.
References mlir::Block::front(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::OpBuilder::setInsertionPoint().
Referenced by replaceBlockArgForUnitDimLoops< IndexedGenericOp >().
replaceUnitDims()
static ArrayAttr replaceUnitDims (DenseSet< unsigned > & unitDims, ArrayRef< AffineMap > indexingMaps, MLIRContext * context) static
Implements a pass that canonicalizes the uses of unit-extent dimensions for broadcasting.
For example,
```mlir #accesses = [ affine_map<(d0, d1) -> (0, d1)>, affine_map<(d0, d1) -> (d0, 0)>, affine_map<(d0, d1) -> (d0, d1)> ]
#trait = { args_in = 2, args_out = 1, indexing_maps = #accesses, iterator_types = ["parallel", "parallel"], library_call = "some_external_fn" }
func (arg0 : tensor<5xf32>, arg1 : tensor<5xf32>) -> tensor<5x5xf32> { %0 = linalg.tensor_reshape arg0 [affine_map<(d0, d1) -> (d0, d1)>] : tensor<5xf32> into tensor<1x5xf32> %1 = linalg.tensor_reshape arg1 [affine_map<(d0, d1) -> (d0, d1)>] : tensor<5xf32> into tensor<5x1xf32> %2 = linalg.generic #trait %0, %1 { ^bb0(arg2: f32, arg3: f32): %3 = addf arg2, arg3 : f32 linalg.yield %3 : f32 } : tensor<1x5xf32>, tensor<5x1xf32> -> tensor<5x5xf32> return %2 : tensor<5x5xf32> }
would canonicalize to
```mlir #accesses = [ affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d0, d1)> ]
#trait = { args_in = 2, args_out = 1, indexing_maps = #accesses, iterator_types = ["parallel", "parallel"], library_call = "some_external_fn" }
func (arg0 : tensor<5xf32>, arg1 : tensor<5xf32>) -> tensor<5x5xf32> { %0 = linalg.generic #trait arg0, arg1 { ^bb0(arg2: f32, arg3: f32): %3 = addf arg2, arg3 : f32 linalg.yield %3 : f32 } : tensor<5xf32>, tensor<5xf32> -> tensor<5x5xf32> return %0 : tensor<5x5xf32> } Given dims of the iteration space of a structured op that are known to be single trip count (unitDims), return the indexing maps to use in the canonicalized op with these dims removed, given the original indexingMaps.
Definition at line 100 of file DropUnitDims.cpp.
References mlir::concatAffineMaps(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::inversePermutation(), and mlir::simplifyAffineMap().
Referenced by replaceBlockArgForUnitDimLoops< IndexedGenericOp >().
replaceUnitExtents()
static UnitExtentReplacementInfo replaceUnitExtents (AffineMap indexMap, RankedTensorType type, MLIRContext * context) static
Utility function for replacing operands/results to a linalg generic operation on tensors with unit-extent dimensions.
These can be replaced with an operand/result with the unit-extent dimension removed. This is only done if the indexing map used to access that didimensionmension has a AffineConstantExpr of value 0. Given the type of an result/operand of a Linalg op, and its indexMap the utility function returns:
the new type with dimensions of size 1 removed.
modified index map that can be used to access the replaced result/operand
the reassociation that converts from the original tensor type to the modified tensor type.
Definition at line 300 of file DropUnitDims.cpp.
References mlir::Attribute::cast(), mlir::concatAffineMaps(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), mlir::getAffineDimExpr(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getContext(), mlir::Builder::getI64IntegerAttr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), mlir::RewriterBase::inlineRegionBefore(), mlir::inversePermutation(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().