MLIR: lib/Dialect/Linalg/Transforms/FusionOnTensors.cpp File Reference
FusionOnTensors.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
Functions
static bool areElementwiseOpsFusable (LinalgOp producer, LinalgOp consumer, unsigned consumerIdx)
Implementation of fusion of generic ops and indexed_generic ops.
static AffineMap getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp (OpOperand &producerOpOperand, AffineMap producerResultIndexMap, AffineMap fusedConsumerArgIndexMap)
Append to fusedOpIndexingMapAttrs the indexing maps for the operands of the producer to use in the fused operation given the indexing map of the result of the producer in the consumer.
static void generateFusedElementwiseOpRegion (PatternRewriter &rewriter, Operation *fusedOp, LinalgOp producer, LinalgOp consumer, AffineMap consumerToProducerLoopsMap, unsigned consumerIdx, unsigned nloops)
Generate the region of the fused tensor operation.
static Optional< SmallVector< Value, 1 > > fuseElementwiseOpsImpl (LinalgOp producer, OpOperand &consumerOpOperand, const ControlElementwiseOpsFusionFn &controlFn, PatternRewriter &rewriter)
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, ArrayRef< int64_t > sourceShape, ArrayRef< AffineMap > reassociationMaps)
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
static bool isTensorReshapeOpFoldableByLinearization (TensorReshapeOp reshapeOp, AffineMap useIndexMap, bool asProducer)
Checks if the reshapeOp can be fused with it consumer (if asProducer is true) or its producer (if asProducer is false) given the indexing map at its use.
template<typename... Args>
static LinalgOp createLinalgOpOfSameType (LinalgOp op, PatternRewriter &rewriter, Args... args)
Based on the type of op create a linalg op of the same type, i.e.
static bool isUnitDimExpansionOnly (ArrayRef< int64_t > expandedShape, ArrayRef< AffineMap > reassociation)
Check if the reshape operation is only expansion into/collapsing of unit-dimension.
static bool isFusableWithReshapeByDimExpansion (LinalgOp linalgOp, unsigned fusedTensorIndex)
Conditions for folding a generic/indexed-generic operation with a reshape op by expanding the iteration space dimensionality for tensor operations.
LogicalResult isIndexedOpExpandable (LinalgOp linalgOp, const ExpansionInfo &expansionInfo)
Epanding the body of a linalg operation requires adaptations of the accessed loop indices.
static AffineMap getIndexingMapInExpandedOp (OpBuilder &builder, AffineMap indexingMap, const ExpansionInfo &expansionInfo)
Return the indexing map to use in the expanded op for a given the indexingMap of the original operation.
static RankedTensorType getExpandedType (RankedTensorType originalType, AffineMap indexingMap, const ExpansionInfo &expansionInfo)
Return the type of the operand/result to use in the expanded op given the type in the original op.
static SmallVector< ReassociationIndices, 4 > getReassociationForExpansion (AffineMap indexingMap, const ExpansionInfo &expansionInfo)
Returns the reassociation maps to use in the linalg.tensor_reshape operation to convert the operands of the origial operation to operands of the expanded operation.
static void buildExpandedIndexedGenericOpRegion (PatternRewriter &rewriter, Location loc, Region &originalOpRegion, Region &fusedOpRegion, const ExpansionInfo &expansionInfo)
Build the body of the expanded IndexedGenericOp.
static void updateExpandedIndexOpRegion (PatternRewriter &rewriter, Location loc, Region &fusedRegion, const ExpansionInfo &expansionInfo)
Update the body of an expanded linalg operation having index semantics.
static Optional< SmallVector< Value, 1 > > fuseWithReshapeByExpansion (LinalgOp linalgOp, TensorReshapeOp reshapeOp, unsigned fusedTensorIndex, PatternRewriter &rewriter)
Implements the fusion of a tensor_reshape op and a generic/indexed_generic op as explained in isFusableWithReshapeByExpansion.
static Optional< SmallVector< Value, 1 > > fuseElementwiseOps (PatternRewriter &rewriter, OpOperand &consumerOpOperand, const ControlElementwiseOpsFusionFn &controlFn)
Function Documentation
areElementwiseOpsFusable()
static bool areElementwiseOpsFusable (LinalgOp producer, LinalgOp consumer, unsigned consumerIdx) static
Implementation of fusion of generic ops and indexed_generic ops.
Definition at line 30 of file FusionOnTensors.cpp.
References mlir::AffineMap::getNumResults(), and mlir::AffineMap::isPermutation().
Referenced by fuseElementwiseOpsImpl().
buildExpandedIndexedGenericOpRegion()
static void buildExpandedIndexedGenericOpRegion (PatternRewriter & rewriter, Location loc, Region & originalOpRegion, Region & fusedOpRegion, const ExpansionInfo & expansionInfo) static
Build the body of the expanded IndexedGenericOp.
The arguments for the induction variables of the original operation need to be recovered by linearizing the arguments of the corresponding dimensions of the expanded op. For now it is assumed that the shapes of the expanded op needed for linearization are static.
Definition at line 708 of file FusionOnTensors.cpp.
References mlir::RewriterBase::cloneRegionBefore(), mlir::Region::empty(), mlir::Region::end(), mlir::Region::getArgument(), mlir::Builder::getIndexType(), mlir::Region::getNumArguments(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), mlir::RewriterBase::mergeBlocks(), mlir::Region::push_back(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by fuseWithReshapeByExpansion().
createLinalgOpOfSameType()
template<typename... Args> static LinalgOp createLinalgOpOfSameType (LinalgOp op, PatternRewriter & rewriter, Args... args) static
Based on the type of op create a linalg op of the same type, i.e.
if op is a linalg.generic operation, the create a linalg.generic operation with the given args. Expects op to be linalg.generic or linalg.indexed_generic.
Definition at line 436 of file FusionOnTensors.cpp.
References mlir::OpBuilder::create().
Referenced by fuseWithReshapeByExpansion().
fuseElementwiseOps()
static Optional<SmallVector<Value, 1> > fuseElementwiseOps (PatternRewriter & rewriter, OpOperand & consumerOpOperand, const ControlElementwiseOpsFusionFn & controlFn) static
Definition at line 1379 of file FusionOnTensors.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::failure(), fuseElementwiseOpsImpl(), mlir::OpOperand::get(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Operation::getNumResults(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), mlir::Operation::getRegions(), mlir::linalg::populateElementwiseOpsFusionPatterns(), mlir::linalg::populateFoldReshapeOpsByLinearizationPatterns(), mlir::RewriterBase::replaceOp(), and mlir::success().
fuseElementwiseOpsImpl()
static Optional<SmallVector<Value, 1> > fuseElementwiseOpsImpl (LinalgOp producer, OpOperand & consumerOpOperand, const ControlElementwiseOpsFusionFn & controlFn, PatternRewriter & rewriter) static
Definition at line 248 of file FusionOnTensors.cpp.
References areElementwiseOpsFusable(), mlir::AffineMap::compose(), mlir::OpBuilder::create(), generateFusedElementwiseOpRegion(), mlir::Builder::getAffineMapArrayAttr(), getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp(), mlir::OpOperand::getOperandNumber(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), and mlir::inversePermutation().
Referenced by fuseElementwiseOps().
fuseWithReshapeByExpansion()
static Optional<SmallVector<Value, 1> > fuseWithReshapeByExpansion (LinalgOp linalgOp, TensorReshapeOp reshapeOp, unsigned fusedTensorIndex, PatternRewriter & rewriter) static
Implements the fusion of a tensor_reshape op and a generic/indexed_generic op as explained in isFusableWithReshapeByExpansion.
Assumes that those conditions have been satisfied.
Definition at line 802 of file FusionOnTensors.cpp.
References mlir::Region::begin(), mlir::Block::begin(), buildExpandedIndexedGenericOpRegion(), mlir::RewriterBase::cloneRegionBefore(), mlir::concatAffineMaps(), mlir::OpBuilder::create(), createLinalgOpOfSameType(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::AffineMap::getDimPosition(), getExpandedType(), getIndexingMapInExpandedOp(), mlir::Operation::getLoc(), mlir::Block::getNumArguments(), mlir::AffineMap::getNumResults(), mlir::getParallelIteratorTypeName(), getReassociationForExpansion(), mlir::Operation::getResult(), mlir::DenseElementsAttr::getSplatValue(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::Builder::getUnknownLoc(), mlir::RewriterBase::inlineRegionBefore(), mlir::inversePermutation(), isFusableWithReshapeByDimExpansion(), isIndexedOpExpandable(), mlir::DenseElementsAttr::isSplat(), isTensorReshapeOpFoldableByLinearization(), isUnitDimExpansionOnly(), linearizeCollapsedDims(), mlir::BlockAndValueMapping::map(), mlir::matchPattern(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::startRootUpdate(), mlir::success(), and updateExpandedIndexOpRegion().
generateFusedElementwiseOpRegion()
static void generateFusedElementwiseOpRegion (PatternRewriter & rewriter, Operation * fusedOp, LinalgOp producer, LinalgOp consumer, AffineMap consumerToProducerLoopsMap, unsigned consumerIdx, unsigned nloops) static
Generate the region of the fused tensor operation.
The region of the fused op must be empty.
Definition at line 98 of file FusionOnTensors.cpp.
References mlir::Block::addArgument(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Block::getOperations(), mlir::Block::getOps(), mlir::Operation::getRegion(), mlir::AffineMap::getSubMap(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), max(), mlir::Region::push_back(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::Block::without_terminator().
Referenced by fuseElementwiseOpsImpl().
getExpandedType()
static RankedTensorType getExpandedType (RankedTensorType originalType, AffineMap indexingMap, const ExpansionInfo & expansionInfo) static
Return the type of the operand/result to use in the expanded op given the type in the original op.
Definition at line 670 of file FusionOnTensors.cpp.
References mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByExpansion().
getIndexingMapInExpandedOp()
static AffineMap getIndexingMapInExpandedOp (OpBuilder & builder, AffineMap indexingMap, const ExpansionInfo & expansionInfo) static
Return the indexing map to use in the expanded op for a given the indexingMap of the original operation.
Definition at line 652 of file FusionOnTensors.cpp.
References mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByExpansion().
getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp()
static AffineMap getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp (OpOperand & producerOpOperand, AffineMap producerResultIndexMap, AffineMap fusedConsumerArgIndexMap) static
Append to fusedOpIndexingMapAttrs the indexing maps for the operands of the producer to use in the fused operation given the indexing map of the result of the producer in the consumer.
Definition at line 65 of file FusionOnTensors.cpp.
References mlir::AffineMap::compose(), mlir::OpOperand::getOperandNumber(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), and mlir::inversePermutation().
Referenced by fuseElementwiseOpsImpl().
getReassociationForExpansion()
static SmallVector<ReassociationIndices, 4> getReassociationForExpansion (AffineMap indexingMap, const ExpansionInfo & expansionInfo) static
Returns the reassociation maps to use in the linalg.tensor_reshape operation to convert the operands of the origial operation to operands of the expanded operation.
The same method is used to compute the linalg.tensor_reshape used to collapse the result of the expanded op to get the value that can replace all uses of the results of the original op.
Definition at line 688 of file FusionOnTensors.cpp.
References mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByExpansion().
isFusableWithReshapeByDimExpansion()
static bool isFusableWithReshapeByDimExpansion (LinalgOp linalgOp, unsigned fusedTensorIndex) static
Conditions for folding a generic/indexed-generic operation with a reshape op by expanding the iteration space dimensionality for tensor operations.
These are preconditions assumed by foldReshapeByDimExpansion which implements the following fusion pattern.
Consider
c = linalg.generic ins(a, b : memref<?x?x?xf32>, memref<?x?xf32>) indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d2, d1)>] d = linalg.tensor_reshape c [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d2)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d4, d5)>] : tensor<?x?x?xf32> into tensor<?x?x?x?x?x?xf32>
The reshape can be folded into the linalgOp if the generic/indexed-generic op loop dimensionality is increased to match the result (operand) of the tensor_reshape when the reshape is expanding (folding). The indexing_map of the fused tensor in the linalgOp and the reassociation map helps compute the indexing maps of the modified op. For the above example, based on the reassociation map it can be concluded that
The loop used to access the first dimension of the fused tensor is split into two.
The loop used to access the second dimension of the fused tensor is kept as is.
The loop used to access the third dimension of the fused tensor is split into three.
i.e. (e0, e1, e2, e3, e4) is the domain of the indexing map of the modified op, then
d0 -> e0, e1 d1 -> e2, e3, e4 d2 -> e5
substituting this, the generic op can be rewritten as
d = linalg.generic ins(%0, %1 :) indexing_maps = [affine_map<(e0, e1, e2, e3, e4, e5) -> (e2, e3, e4, e0, e1, e5)>, affine_map<(e0, e1, e2, e3, e4, e5) -> (e2, e3, e4, e5)>, affine_map<(e0, e1, e2, e3, e4, e5) -> (e0, e1, e5, e2, e3, e4)>]
Since operands to the linalg generic are now 5D, reshapes can be introduced to make it consistent
%0 = linalg.tensor_reshape a [affine_map<(e0, e1, e2, e3, e4, e5) -> (e0, e1, e2), affine_map<(e0, e1, e2, e3, e4, e5) -> (e3, e4), affine_map<(e0, e1, e2, e3, e4, e5) -> (e5)] : tensor<?x?x?xf32> into tensor<?x?x?x?x?x?xf32> %1 = linalg.tensor_reshape b [affine_map<(e0, e1, e2, e3) -> (e0, e1, e2), affine_map<(e0, e1, e2, e3) -> (e3)] : tensor<?x?x?xf32> into tensor<?x?x?x?xf32>
The added reshapes are again expanding patterns, so they will get fused with its producers if possible.
Definition at line 525 of file FusionOnTensors.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::getParallelIteratorTypeName(), mlir::AffineMap::getResults(), and mlir::success().
Referenced by fuseWithReshapeByExpansion().
isIndexedOpExpandable()
LogicalResult isIndexedOpExpandable (LinalgOp linalgOp, const ExpansionInfo & expansionInfo)
Epanding the body of a linalg operation requires adaptations of the accessed loop indices.
Specifically, access of indices in the original operation need to be replaced with linearizations of indices in the expanded op. That requires the shape of the expanded dimensions to be static (at least all but the most significant). For now check that these are all statically sized. Note that this could be extended to handle dynamic case, but the implementation below uses affine.apply which seems to have issues when the shapes are not static.
Definition at line 632 of file FusionOnTensors.cpp.
References mlir::ShapedType::isDynamic(), and mlir::success().
Referenced by fuseWithReshapeByExpansion().
isTensorReshapeOpFoldableByLinearization()
static bool isTensorReshapeOpFoldableByLinearization (TensorReshapeOp reshapeOp, AffineMap useIndexMap, bool asProducer) static
Checks if the reshapeOp can be fused with it consumer (if asProducer is true) or its producer (if asProducer is false) given the indexing map at its use.
Definition at line 412 of file FusionOnTensors.cpp.
References mlir::AffineMap::isPermutation().
Referenced by fuseWithReshapeByExpansion().
isUnitDimExpansionOnly()
static bool isUnitDimExpansionOnly (ArrayRef< int64_t > expandedShape, ArrayRef< AffineMap > reassociation) static
Check if the reshape operation is only expansion into/collapsing of unit-dimension.
Definition at line 449 of file FusionOnTensors.cpp.
Referenced by fuseWithReshapeByExpansion().
linearizeCollapsedDims()
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, ArrayRef< int64_t > sourceShape, ArrayRef< AffineMap > reassociationMaps) static
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
Note that this implicitly assumes that the tensors dimensions are "row-major" ordered logically.
For example:
%0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
and reshape: %1 = linalg.tensor_reshape %0 [affine_map<(i, j, k, l) -> (i)>, affine_map<(i, j, k, l) -> (j, k, l)>] : tensor<?x?x4x5xf32> into tensor<?x?xf32>
would be rewritten into: %0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1 * 20 + d2 * 5 + d3)>
Definition at line 375 of file FusionOnTensors.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::makeCanonicalStridedLayoutExpr().
Referenced by fuseWithReshapeByExpansion().
updateExpandedIndexOpRegion()
static void updateExpandedIndexOpRegion (PatternRewriter & rewriter, Location loc, Region & fusedRegion, const ExpansionInfo & expansionInfo) static
Update the body of an expanded linalg operation having index semantics.
The indices of the original operation need to be recovered by linearizing the indices of the correspoding dimensions of the expanded operation. For now it is assumed that the shapes of the expanded operation needed for linearization are static.
Definition at line 760 of file FusionOnTensors.cpp.
References mlir::bindDims(), mlir::OpBuilder::create(), mlir::Region::front(), mlir::Builder::getContext(), mlir::Block::getOps(), mlir::ShapedType::isDynamic(), mlir::RewriterBase::replaceOp(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by fuseWithReshapeByExpansion().