MLIR: lib/Conversion/GPUToSPIRV/GPUToSPIRV.cpp File Reference
GPUToSPIRV.cpp File Reference
#include "mlir/Conversion/GPUToSPIRV/GPUToSPIRV.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/StringSwitch.h"
#include "GPUToSPIRV.cpp.inc"
Functions
static Optional< int32_t > getLaunchConfigIndex (Operation *op)
static spirv::FuncOp lowerAsEntryFunction (gpu::GPUFuncOp funcOp, TypeConverter &typeConverter, ConversionPatternRewriter &rewriter, spirv::EntryPointABIAttr entryPointInfo, ArrayRef< spirv::InterfaceVarABIAttr > argABIInfo)
static LogicalResult getDefaultABIAttrs (MLIRContext *context, gpu::GPUFuncOp funcOp, SmallVectorImpl< spirv::InterfaceVarABIAttr > &argABI)
Populates argABI with spv.interface_var_abi attributes for lowering gpu.func to spv.func if no arguments have the attributes set already.
Variables
static constexpr const char kSPIRVModule [] = "__spv__"
Function Documentation
getDefaultABIAttrs()
static LogicalResult getDefaultABIAttrs (MLIRContext * context, gpu::GPUFuncOp funcOp, SmallVectorImpl< spirv::InterfaceVarABIAttr > & argABI) static
Populates argABI with spv.interface_var_abi attributes for lowering gpu.func to spv.func if no arguments have the attributes set already.
Returns failure if any argument has the ABI attribute set already.
Definition at line 225 of file GPUToSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::ConversionPatternRewriter::eraseBlock(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::Identifier::get(), mlir::spirv::getAddressingModel(), mlir::Builder::getContext(), mlir::spirv::getInterfaceVarABIAttr(), mlir::spirv::getInterfaceVarABIAttrName(), mlir::spirv::getMemoryModel(), mlir::ConversionPatternRewriter::inlineRegionBefore(), kSPIRVModule, mlir::spirv::lookupEntryPointABI(), mlir::spirv::lookupTargetEnvOrDefault(), lowerAsEntryFunction(), mlir::spirv::needsInterfaceVarABIAttrs(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
getLaunchConfigIndex()
static Optional<int32_t> getLaunchConfigIndex (Operation * op) static
Definition at line 105 of file GPUToSPIRV.cpp.
References mlir::failure(), mlir::Operation::getAttrOfType(), mlir::spirv::getBuiltinVariableValue(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getIntegerType(), mlir::spirv::lookupLocalWorkGroupSize(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
lowerAsEntryFunction()
static spirv::FuncOp lowerAsEntryFunction (gpu::GPUFuncOp funcOp, TypeConverter & typeConverter, ConversionPatternRewriter & rewriter, spirv::EntryPointABIAttr entryPointInfo, ArrayRef< spirv::InterfaceVarABIAttr > argABIInfo) static
Definition at line 167 of file GPUToSPIRV.cpp.
References mlir::ConversionPatternRewriter::convertRegionTypes(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::spirv::getEntryPointABIAttrName(), mlir::Builder::getFunctionType(), mlir::spirv::getInterfaceVarABIAttrName(), mlir::SymbolTable::getSymbolAttrName(), mlir::impl::getTypeAttrName(), and mlir::ConversionPatternRewriter::inlineRegionBefore().
Referenced by getDefaultABIAttrs().
Variable Documentation
kSPIRVModule
constexpr const char kSPIRVModule[] = "__spv__" static
Definition at line 25 of file GPUToSPIRV.cpp.
Referenced by getDefaultABIAttrs().