MLIR: lib/Dialect/Linalg/IR/LinalgInterfaces.cpp File Reference
LinalgInterfaces.cpp File Reference
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "llvm/ADT/SmallSet.h"
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.cpp.inc"
Classes
struct HasAffineDimExprVisitor
Visitor to check if any of the given set of positions from AffineDimExprs are used within an AffineExpr.
Enumerations
enum MatchContractionResult {
Success = 0, NotLinalgOp, WrongNumOperands, NoReduction,
NotProjectedPermutations, NotAddMul
}
Functions
static bool isChainOfUnaryOpsFrom (Value v, Value from)
Include the definitions of the copy operation interface.
template<typename OpType >
static OpType getSingleOpOfType (Block &block)
Return the unique instance of OpType in block if it is indeed unique.
template<typename AddOpType , typename MulOpType >
static bool isAddMul (Block &block)
Detect whether res is any permutation of u5(u1(c) + u2(u3(a) * u4(b))) on the field (AddOpType, MulOpType), where u1, u2, u3, u4 and u5 represent unary operations that may change the type.
static MatchContractionResult isContractionInterfaceImpl (Operation *op)
static Value createFoldedComposedAffineApply (OpBuilder &b, Location loc, AffineMap map, ValueRange operandsRef)
Fully compose map with operands and canonicalize the result.
Enumeration Type Documentation
MatchContractionResult
enum MatchContractionResult
Enumerator
Success
NotLinalgOp
WrongNumOperands
NoReduction
NotProjectedPermutations
NotAddMul
Definition at line 91 of file LinalgInterfaces.cpp.
Function Documentation
createFoldedComposedAffineApply()
static Value createFoldedComposedAffineApply (OpBuilder & b, Location loc, AffineMap map, ValueRange operandsRef) static
Fully compose map with operands and canonicalize the result.
Return the createOrFold'ed AffineApply op.
Definition at line 160 of file LinalgInterfaces.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::OpBuilder::createOrFold(), and mlir::fullyComposeAffineMapAndOperands().
Referenced by mlir::linalg::applyMapToValues().
getSingleOpOfType()
template<typename OpType > static OpType getSingleOpOfType (Block & block) static
Return the unique instance of OpType in block if it is indeed unique.
Return null if none or more than 1 instances exist.
Definition at line 45 of file LinalgInterfaces.cpp.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), and mlir::Block::walk().
isAddMul()
template<typename AddOpType , typename MulOpType > static bool isAddMul (Block & block) static
Detect whether res is any permutation of u5(u1(c) + u2(u3(a) * u4(b))) on the field (AddOpType, MulOpType), where u1, u2, u3, u4 and u5 represent unary operations that may change the type.
Definition at line 62 of file LinalgInterfaces.cpp.
References mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Block::getTerminator(), isChainOfUnaryOpsFrom(), and mlir::success().
isChainOfUnaryOpsFrom()
static bool isChainOfUnaryOpsFrom (Value v, Value from) static
Include the definitions of the copy operation interface.
Return true if the use-def chain from v to from consists of 0 or more unary single-operand operations.
Definition at line 31 of file LinalgInterfaces.cpp.
References mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), and mlir::Operation::getOperand().
Referenced by isAddMul().
isContractionInterfaceImpl()
static MatchContractionResult isContractionInterfaceImpl (Operation * op) static
Definition at line 99 of file LinalgInterfaces.cpp.
References mlir::AffineMap::isProjectedPermutation(), NoReduction, NotAddMul, NotLinalgOp, NotProjectedPermutations, Success, and WrongNumOperands.
Referenced by mlir::linalg::isaContractionOpInterface(), and mlir::linalg::detail::verifyContractionInterface().