MLIR: lib/CAPI/Dialect/Linalg.cpp File Reference
Linalg.cpp File Reference
#include "mlir-c/Dialect/Linalg.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/Linalg/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
Functions
void mlirLinalgFillBuiltinNamedOpRegion (MlirDialect linalgDialect, MlirOperation mlirOp, intptr_t n, MlirValue const *mlirCaptures)
Apply the special region builder for the builtin named Linalg op.
Function Documentation
mlirLinalgFillBuiltinNamedOpRegion()
void mlirLinalgFillBuiltinNamedOpRegion (MlirDialect linalgDialect, MlirOperation mlirOp, intptr_t n, MlirValue const * mlirCaptures)
Apply the special region builder for the builtin named Linalg op.
Assert that op is a builtin named Linalg op.
Definition at line 19 of file Linalg.cpp.
References mlir::Region::getBlocks(), mlir::Operation::getContext(), mlir::getElementTypeOrSelf(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::OperationName::getStringRef(), MLIR_DEFINE_CAPI_DIALECT_REGISTRATION, and unwrap().
Referenced by mlir::python::populateDialectLinalgSubmodule().