MLIR: lib/Dialect/Linalg/IR/LinalgOps.cpp File Reference
LinalgOps.cpp File Reference
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Parser.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.tcgen.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yamlgen.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgOps.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define DEFINE_POOLING_OP_GET_EFFECTS(OP_NAME)
#define GET_OP_CLASSES
#define GET_OP_CLASSES
#define INSTANTIATE_WEIGHTED_POOLING_INPUT_INDEX(OP_TYPE)
#define CANONICALIZERS_AND_FOLDERS(XXX)
Functions
template<typename NamedStructuredOpType >
static void fillStructuredOpRegion (OpBuilder &opBuilder, Region &region, TypeRange inputTypes, TypeRange outputTypes, ValueRange captures={}, std::function< void(unsigned, unsigned)> errorHandler=nullptr)
Forward declarations.
template<typename NamedStructuredOpType >
static void createAndFillStructuredOpRegion (OpBuilder &opBuilder, OperationState &result, TypeRange inputTypes, TypeRange outputTypes, ValueRange captures={})
Generic entry point to create both the region and the block of a LinalgOp.
static ParseResult parseCommonStructuredOpParts (OpAsmParser &parser, OperationState &result, SmallVectorImpl< Type > &inputTypes, SmallVectorImpl< Type > &outputTypes)
Common parsing and printing used for both named structured ops created by ods-gen and by manually defined C++ ops.
template<typename NamedStructuredOpType >
static void printCommonStructuredOpParts (OpAsmPrinter &p, NamedStructuredOpType op)
template<typename NamedStructuredOpType >
static ParseResult parseNamedStructuredOpRegion (OpAsmParser &parser, Region &region, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< OpAsmParser::OperandType > captures={})
Specific parsing and printing for named structured ops created by ods-gen.
static ParseResult parseNamedStructuredOpResults (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes)
template<typename NamedStructuredOpType >
static ParseResult parseNamedStructuredOp (OpAsmParser &parser, OperationState &result, ArrayRef< OpAsmParser::OperandType > captures={})
static void printNamedStructuredOpResults (OpAsmPrinter &p, TypeRange resultTypes)
template<typename NamedStructuredOpType >
static void printNamedStructuredOp (OpAsmPrinter &p, NamedStructuredOpType op)
static SmallVector< OpFoldResult > getAsOpFoldResult (ArrayRef< Value > values)
Helper function to convert a Value into an OpFoldResult, if the Value is known to be a constant index value.
static SmallVector< Value > getAsValues (OpBuilder &b, Location loc, ArrayRef< OpFoldResult > valueOrAttrVec)
Helper function to convert a vector of OpFoldResults into a vector of Values.
static void dispatchIndexOpFoldResult (OpFoldResult ofr, SmallVectorImpl< Value > &dynamicVec, SmallVectorImpl< int64_t > &staticVec, int64_t sentinel)
Helper function to dispatch an OpFoldResult into either the dynamicVec if it is a Value or into staticVec if it is an IntegerAttr.
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form
someop(memrefcast(%src)) -> someop(%src)
It folds the source of the memref.cast into the root operation directly.
static LogicalResult foldMemRefCastInTiledLoopOp (TiledLoopOp op)
This is a specialization of foldMemRefCast used for patterns of the form
tiled_loop(memrefcast(%src)) -> tiled_loop(%src)
It folds the source of the memref.cast into the root operation directly.
ParseResult parseCopyOpRegion (OpAsmParser &parser, Region &r, Type inputType, Type outputType)
void printCopyOpRegion (OpAsmPrinter &, Operation *, Region &, Type, Type)
CopyOp region is elided when printing.
static LogicalResult verify (CopyOp op)
ParseResult parseFillOpRegion (OpAsmParser &parser, Region &r, Type outputType, OpAsmParser::OperandType valueRef)
void printFillOpRegion (OpAsmPrinter &, Operation *, Region &, Type, Value)
FillOp region is elided when printing.
static LogicalResult verify (FillOp op)
template<typename GenericOpType >
static void printGenericOp (OpAsmPrinter &p, GenericOpType op)
static void print (OpAsmPrinter &p, GenericOp op)
static void print (OpAsmPrinter &p, IndexedGenericOp op)
static ParseResult parseGenericOp (OpAsmParser &parser, OperationState &result)
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> &effects, ValueRange results, ValueRange inputBuffers, ValueRange outputs)
template<typename GenericOpType >
static LogicalResult verifyGenericOp (GenericOpType op)
static LogicalResult verify (GenericOp op)
static LogicalResult verify (IndexedGenericOp op)
static LogicalResult verify (InitTensorOp op)
static SmallVector< int64_t, 4 > extractFromI64ArrayAttr (Attribute attr)
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
static LogicalResult verify (PadTensorOp op)
static ArrayAttr collapseReassociationMaps (ArrayRef< AffineMap > mapsProducer, ArrayRef< AffineMap > mapsConsumer, MLIRContext *context)
Collapse reassociation maps that are used in pair of reshape ops where one is a producer and other is the consumer.
template<typename ReshapeOpTy >
static OpFoldResult foldReshapeOp (ReshapeOpTy reshapeOp, ArrayRef< Attribute > operands)
static bool isReassociationValid (ArrayRef< AffineMap > reassociation, int *invalidIndex=nullptr)
Return true if the reassociation specification is valid, false otherwise.
static bool isReshapableDimBand (unsigned dim, unsigned extent, ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > strides)
Detect whether memref dims [dim, dim + extent) can be reshaped without copies.
static MemRefType computeReshapeCollapsedType (MemRefType type, ArrayRef< AffineMap > reassociation)
Compute the MemRefType obtained by applying the reassociation (which is expected to be valid) to type.
static SmallVector< AffineMap, 4 > getAffineMaps (ArrayAttr attrs)
Helper functions assert Attribute of the proper type in attr and returns the corresponding vector.
template<typename AffineExprTy >
unsigned getMaxPosOfType (ArrayRef< ReassociationExprs > exprArrays)
static SmallVector< AffineMap, 4 > getSymbolLessAffineMaps (ArrayRef< ReassociationExprs > reassociation)
static SmallVector< SmallVector< AffineExpr, 2 >, 2 > convertReassociationIndicesToMaps (OpBuilder &b, ArrayRef< ReassociationIndices > reassociationIndices)
static OpFoldResult getCollapsedOutputDimFromInputShape (OpBuilder &builder, Location loc, int64_t dimIndex, Value src, ArrayRef< AffineMap > reassociationMap)
For reshape op compute the shape at dimension dimIndex of the output in terms of shape of the src, when the reshape op is a collapsing operation.
static SmallVector< OpFoldResult, 4 > getCollapsedOutputShapeFromInputShape (OpBuilder &builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation)
Given the src of a collapsing reshape op and its reassociation maps, compute the shape of the result of the reshape.
static llvm::DenseMap< int64_t, int64_t > getExpandedDimToCollapsedDimMap (ArrayRef< AffineMap > reassociation)
Compute a map that for a given dimension of the expanded type gives the dimension in the collapsed type it maps to.
static OpFoldResult getExpandedOutputDimFromInputShape (OpBuilder &builder, Location loc, int64_t dimIndex, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation, llvm::DenseMap< int64_t, int64_t > &expandedDimToCollapsedDim)
For an expanding reshape op, compute the value for a dimension of the output from the shape of the input.
static SmallVector< OpFoldResult, 4 > getExpandedOutputShapeFromInputShape (OpBuilder &builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation)
Given the src of an expanding reshape op, the reassociation maps and the result type, compute the shape of the result of the reshape.
static SmallVector< OpFoldResult, 4 > getReshapeOutputShapeFromInputShape (OpBuilder &builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassocation)
template<typename OpTy >
static LogicalResult verifyReshapeLikeShapes (OpTy op, ShapedType collapsedType, ShapedType expandedType, bool isExpandingReshape)
Verify that shapes of the reshaped types using following rules 1) if a dimension in the collapsed type is static, then the corresponding dimensions in the expanded shape should be a) static b) the product should be same as the collaped shape.
template<typename Op , typename T >
static LogicalResult verifyReshapeLikeTypes (Op op, T &expandedType, T &collapsedType)
static LogicalResult verify (ReshapeOp op)
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation)
Compute the RankedTensorType obtained by applying reassociation to type.
static LogicalResult verify (TensorReshapeOp op)
static void print (OpAsmPrinter &p, linalg::YieldOp op)
static ParseResult parseYieldOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOpInterface)
static LogicalResult verify (linalg::YieldOp op)
static void print (OpAsmPrinter &p, TiledLoopOp op)
static ParseResult parseTiledLoopOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TiledLoopOp op)
static LogicalResult verify (IndexOp op)
template<typename LinalgPoolingOp >
static LogicalResult verifyStrideOrDilation (LinalgPoolingOp op, ArrayRef< Attribute > attrs, bool isStride)
static LogicalResult verify (ConvOp op)
template<typename PoolingOp >
static LogicalResult verifySingleInputPoolingOp (PoolingOp op)
static LogicalResult verify (PoolingMaxOp op)
static LogicalResult verify (PoolingMinOp op)
static LogicalResult verify (PoolingSumOp op)
static void appendMangledType (llvm::raw_string_ostream &ss, Type t)
template<typename NamedStructuredOpType >
void createAndFillStructuredOpRegion (OpBuilder &opBuilder, OperationState &result, TypeRange inputTypes, TypeRange outputTypes, ValueRange captures)
Generic entry point to create both the region and the block of a LinalgOp.
template<typename NamedStructuredOpType >
static LogicalResult verifyNamedStructuredOp (NamedStructuredOpType op)
Macro Definition Documentation
CANONICALIZERS_AND_FOLDERS
#define CANONICALIZERS_AND_FOLDERS (XXX)
Value:
void XXX::getCanonicalizationPatterns(RewritePatternSet &results,            \
                                        MLIRContext *context) {                \
    results.add<DeduplicateInputs, EraseDeadLinalgOp, FoldTensorCastOp,        \
                RemoveIdentityLinalgOps>(context);                             \
  }                                                                            \
                                                                               \
  LogicalResult XXX::fold(ArrayRef<Attribute>,                                 \
                          SmallVectorImpl<OpFoldResult> &) {                   \
    return foldMemRefCast(*this);                                              \
  }
Definition at line 2946 of file LinalgOps.cpp.
DEFINE_POOLING_OP_GET_EFFECTS
#define DEFINE_POOLING_OP_GET_EFFECTS (OP_NAME)
Value:
void OP_NAME::getEffects(\
      SmallVectorImpl<SideEffects::EffectInstance<MemoryEffects::Effect>>      \
          &effects) {                                                          \
    effects.emplace_back(MemoryEffects::Read::get(), input(),                  \
                         SideEffects::DefaultResource::get());                 \
    effects.emplace_back(MemoryEffects::Write::get(), output(),                \
                         SideEffects::DefaultResource::get());                 \
  }
Definition at line 2349 of file LinalgOps.cpp.
Referenced by verify().
GET_OP_CLASSES [1/2]
#define GET_OP_CLASSES
Definition at line 2384 of file LinalgOps.cpp.
GET_OP_CLASSES [2/2]
#define GET_OP_CLASSES
Definition at line 2384 of file LinalgOps.cpp.
INSTANTIATE_WEIGHTED_POOLING_INPUT_INDEX
#define INSTANTIATE_WEIGHTED_POOLING_INPUT_INDEX (OP_TYPE)
Value:
template SmallVector<AffineExpr, 4>                                          \
  mlir::linalg::weightedPoolingInputIndex<OP_TYPE>(                            \
      OP_TYPE op, ArrayRef<AffineExpr> outputDims,                             \
      ArrayRef<AffineExpr> windowDims);
Definition at line 2441 of file LinalgOps.cpp.
Function Documentation
appendMangledType()
static void appendMangledType (llvm::raw_string_ostream & ss, Type t) static
Definition at line 2460 of file LinalgOps.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isSignlessIntOrIndexOrFloat().
Referenced by mlir::linalg::generateLibraryCallName().
collapseReassociationMaps()
static ArrayAttr collapseReassociationMaps (ArrayRef< AffineMap > mapsProducer, ArrayRef< AffineMap > mapsConsumer, MLIRContext * context) static
Collapse reassociation maps that are used in pair of reshape ops where one is a producer and other is the consumer.
Only valid to use this method when both the producer and consumer are collapsing dimensions or both are expanding dimensions.
For example, mapsProducer = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d1)>, affine_map<(d0, d1, d2, d3, d4) -> (d2)>, affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>] mapsConsumer = [affine_map<(d0, d1, d2) -> (d0, d1)>, affine_map<(d0, d1, d2) -> (d2)>]
is folded into
result = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>, affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>]
Definition at line 1107 of file LinalgOps.cpp.
References mlir::AffineExpr::cast(), mlir::failure(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineDimExpr::getPosition(), mlir::ShapedType::getRank(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
computeReshapeCollapsedType()
static MemRefType computeReshapeCollapsedType (MemRefType type, ArrayRef< AffineMap > reassociation) static
Compute the MemRefType obtained by applying the reassociation (which is expected to be valid) to type.
If type is Contiguous MemRefType, this always produce a contiguous MemRefType.
Definition at line 1258 of file LinalgOps.cpp.
References mlir::canonicalizeStridedLayout(), mlir::AffineExpr::dyn_cast(), getAffineMaps(), mlir::getStridesAndOffset(), isReassociationValid(), isReshapableDimBand(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::makeStridedLinearLayoutMap(), mlir::MemRefType::Builder::setAffineMaps(), mlir::MemRefType::Builder::setShape(), and mlir::succeeded().
Referenced by getReshapeOutputShapeFromInputShape(), and verify().
computeTensorReshapeCollapsedType()
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation) static
Compute the RankedTensorType obtained by applying reassociation to type.
Definition at line 1630 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::Builder::getAffineMapArrayAttr(), getSymbolLessAffineMaps(), mlir::Value::getType(), isReassociationValid(), and mlir::ShapedType::kDynamicSize.
Referenced by verify().
convertReassociationIndicesToMaps()
static SmallVector<SmallVector<AffineExpr, 2>, 2> convertReassociationIndicesToMaps (OpBuilder & b, ArrayRef< ReassociationIndices > reassociationIndices) static
Definition at line 1354 of file LinalgOps.cpp.
References mlir::Builder::getAffineDimExpr().
createAndFillStructuredOpRegion() [1/2]
template<typename NamedStructuredOpType > static void createAndFillStructuredOpRegion (OpBuilder & opBuilder, OperationState & result, TypeRange inputTypes, TypeRange outputTypes, ValueRange captures = {}) static
Generic entry point to create both the region and the block of a LinalgOp.
Definition at line 2556 of file LinalgOps.cpp.
References mlir::OperationState::addRegion().
createAndFillStructuredOpRegion() [2/2]
template<typename NamedStructuredOpType > void createAndFillStructuredOpRegion (OpBuilder & opBuilder, OperationState & result, TypeRange inputTypes, TypeRange outputTypes, ValueRange captures)
Generic entry point to create both the region and the block of a LinalgOp.
Definition at line 2556 of file LinalgOps.cpp.
References mlir::OperationState::addRegion().
dispatchIndexOpFoldResult()
static void dispatchIndexOpFoldResult (OpFoldResult ofr, SmallVectorImpl< Value > & dynamicVec, SmallVectorImpl< int64_t > & staticVec, int64_t sentinel) static
Helper function to dispatch an OpFoldResult into either the dynamicVec if it is a Value or into staticVec if it is an IntegerAttr.
In the case of a Value, a copy of the sentinel value is also pushed to staticVec. This is useful to extract mixed static and dynamic entries that come from an AttrSizedOperandSegments trait.
Definition at line 124 of file LinalgOps.cpp.
Referenced by verify().
extractFromI64ArrayAttr()
static SmallVector<int64_t, 4> extractFromI64ArrayAttr (Attribute attr) static
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
Definition at line 912 of file LinalgOps.cpp.
References mlir::Attribute::cast().
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
fillStructuredOpRegion()
template<typename NamedStructuredOpType > static void fillStructuredOpRegion (OpBuilder & opBuilder, Region & region, TypeRange inputTypes, TypeRange outputTypes, ValueRange captures = {}, std::function< void(unsigned, unsigned)> errorHandler = nullptr) static
Forward declarations.
Generic entry point to create the block for the region of a LinalgOp.
Generic entry point to create the block for the region of a LinalgOp. This is used by both named structured ops created by ods-gen and by manually defined C++ ops. This is used by both builders and parsers. This function creates the block in the region with arguments corresponding to the elemental types of inputTypes and outputTypes, which are asserted to be ShapedType.
This is used by both named structured ops created by ods-gen and by manually defined C++ ops. This is used by both builders and parsers. This function creates the block in the region with arguments corresponding to the elemental types of inputTypes and outputTypes, which are asserted to be ShapedType.
Definition at line 2520 of file LinalgOps.cpp.
References mlir::OpBuilder::createBlock(), mlir::getElementTypeOrSelf(), mlir::Block::getNumArguments(), mlir::Builder::getUnknownLoc(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPointToStart().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form
someop(memrefcast(%src)) -> someop(%src)
It folds the source of the memref.cast into the root operation directly.
Definition at line 142 of file LinalgOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::getOpOperands(), and mlir::success().
Referenced by mlir::linalg::generateLibraryCallName().
foldMemRefCastInTiledLoopOp()
static LogicalResult foldMemRefCastInTiledLoopOp (TiledLoopOp op) static
This is a specialization of foldMemRefCast used for patterns of the form
tiled_loop(memrefcast(%src)) -> tiled_loop(%src)
It folds the source of the memref.cast into the root operation directly.
Definition at line 159 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OpBuilder::atBlockBegin(), mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::emitWarning(), mlir::Block::eraseArgument(), mlir::OpOperand::get(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArgument(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Block::getNumArguments(), mlir::Value::getType(), mlir::Block::insertArgument(), mlir::Type::isa(), mlir::OperationState::regions, mlir::Value::replaceAllUsesWith(), mlir::OpOperand::set(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
Referenced by verify().
foldReshapeOp()
template<typename ReshapeOpTy > static OpFoldResult foldReshapeOp (ReshapeOpTy reshapeOp, ArrayRef< Attribute > operands) static
Definition at line 1181 of file LinalgOps.cpp.
Referenced by mlir::linalg::generateLibraryCallName().
getAffineMaps()
static SmallVector<AffineMap, 4> getAffineMaps (ArrayAttr attrs) static
Helper functions assert Attribute of the proper type in attr and returns the corresponding vector.
TODO: this should be evolved into a generic getRangeOfType<AffineMap>(ArrayAttr attrs) that does not copy.
Definition at line 1320 of file LinalgOps.cpp.
References mlir::Attribute::cast().
Referenced by computeReshapeCollapsedType(), isMemRefNormalizable(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetNumAffineMaps(), verify(), and verifyReshapeLikeTypes().
getAsOpFoldResult()
static SmallVector<OpFoldResult> getAsOpFoldResult (ArrayRef< Value > values) static
Helper function to convert a Value into an OpFoldResult, if the Value is known to be a constant index value.
Definition at line 94 of file LinalgOps.cpp.
References mlir::Value::getType(), mlir::Type::isa(), mlir::m_ConstantInt(), and mlir::matchPattern().
Referenced by verify().
getAsValues()
static SmallVector<Value> getAsValues (OpBuilder & b, Location loc, ArrayRef< OpFoldResult > valueOrAttrVec) static
Helper function to convert a vector of OpFoldResults into a vector of Values.
Definition at line 108 of file LinalgOps.cpp.
References mlir::Location::cast(), and mlir::OpBuilder::create().
Referenced by verify().
getCollapsedOutputDimFromInputShape()
static OpFoldResult getCollapsedOutputDimFromInputShape (OpBuilder & builder, Location loc, int64_t dimIndex, Value src, ArrayRef< AffineMap > reassociationMap) static
For reshape op compute the shape at dimension dimIndex of the output in terms of shape of the src, when the reshape op is a collapsing operation.
It is the product of the shape of the collapsed dimensions of the src.
Definition at line 1372 of file LinalgOps.cpp.
References mlir::linalg::applyMapToValues(), mlir::OpBuilder::createOrFold(), mlir::AffineMap::get(), mlir::Builder::getAffineSymbolExpr(), and mlir::AffineMap::getResults().
Referenced by getCollapsedOutputShapeFromInputShape().
getCollapsedOutputShapeFromInputShape()
static SmallVector<OpFoldResult, 4> getCollapsedOutputShapeFromInputShape (OpBuilder & builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation) static
Given the src of a collapsing reshape op and its reassociation maps, compute the shape of the result of the reshape.
Definition at line 1393 of file LinalgOps.cpp.
References getCollapsedOutputDimFromInputShape().
Referenced by getReshapeOutputShapeFromInputShape().
getExpandedDimToCollapsedDimMap()
static llvm::DenseMap<int64_t, int64_t> getExpandedDimToCollapsedDimMap (ArrayRef< AffineMap > reassociation) static
Compute a map that for a given dimension of the expanded type gives the dimension in the collapsed type it maps to.
Essentially its the inverse of the reassocation maps.
Definition at line 1407 of file LinalgOps.cpp.
References mlir::detail::enumerate().
Referenced by getExpandedOutputShapeFromInputShape().
getExpandedOutputDimFromInputShape()
static OpFoldResult getExpandedOutputDimFromInputShape (OpBuilder & builder, Location loc, int64_t dimIndex, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation, llvm::DenseMap< int64_t, int64_t > & expandedDimToCollapsedDim) static
For an expanding reshape op, compute the value for a dimension of the output from the shape of the input.
Definition at line 1423 of file LinalgOps.cpp.
References mlir::linalg::applyMapToValues(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::AffineExpr::floorDiv(), mlir::AffineMap::get(), mlir::Builder::getAffineSymbolExpr(), mlir::Builder::getI64IntegerAttr(), and mlir::ShapedType::isDynamic().
Referenced by getExpandedOutputShapeFromInputShape().
getExpandedOutputShapeFromInputShape()
static SmallVector<OpFoldResult, 4> getExpandedOutputShapeFromInputShape (OpBuilder & builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassociation) static
Given the src of an expanding reshape op, the reassociation maps and the result type, compute the shape of the result of the reshape.
Definition at line 1461 of file LinalgOps.cpp.
References getExpandedDimToCollapsedDimMap(), and getExpandedOutputDimFromInputShape().
Referenced by getReshapeOutputShapeFromInputShape().
getGenericEffectsImpl()
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> & effects, ValueRange results, ValueRange inputBuffers, ValueRange outputs) static
Definition at line 645 of file LinalgOps.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::isDenseDim(), mlir::isSparseDim(), mlir::success(), mlir::verify(), and verify().
getMaxPosOfType()
template<typename AffineExprTy > unsigned getMaxPosOfType (ArrayRef< ReassociationExprs > exprArrays)
Definition at line 1326 of file LinalgOps.cpp.
References mlir::AffineExpr::dyn_cast(), and max().
getReshapeOutputShapeFromInputShape()
static SmallVector<OpFoldResult, 4> getReshapeOutputShapeFromInputShape (OpBuilder & builder, Location loc, Value src, ArrayRef< int64_t > dstStaticShape, ArrayRef< AffineMap > reassocation) static
Definition at line 1475 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), computeReshapeCollapsedType(), mlir::Builder::getAffineMapArrayAttr(), getCollapsedOutputShapeFromInputShape(), getExpandedOutputShapeFromInputShape(), getSymbolLessAffineMaps(), and mlir::Value::getType().
Referenced by verify().
getSymbolLessAffineMaps()
static SmallVector<AffineMap, 4> getSymbolLessAffineMaps (ArrayRef< ReassociationExprs > reassociation) static
Definition at line 1340 of file LinalgOps.cpp.
References mlir::AffineMap::get().
Referenced by computeTensorReshapeCollapsedType(), and getReshapeOutputShapeFromInputShape().
isReassociationValid()
static bool isReassociationValid (ArrayRef< AffineMap > reassociation, int * invalidIndex = nullptr) static
Return true if the reassociation specification is valid, false otherwise.
When false, the invalidIndex integer pointer is optionally filled with the index of the offending reassociation map.
Definition at line 1200 of file LinalgOps.cpp.
References mlir::detail::enumerate().
Referenced by computeReshapeCollapsedType(), computeTensorReshapeCollapsedType(), and verifyReshapeLikeTypes().
isReshapableDimBand()
static bool isReshapableDimBand (unsigned dim, unsigned extent, ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > strides) static
Detect whether memref dims [dim, dim + extent) can be reshaped without copies.
Definition at line 1232 of file LinalgOps.cpp.
References mlir::ShapedType::isDynamic().
Referenced by computeReshapeCollapsedType().
parseCommonStructuredOpParts()
static ParseResult parseCommonStructuredOpParts (OpAsmParser & parser, OperationState & result, SmallVectorImpl< Type > & inputTypes, SmallVectorImpl< Type > & outputTypes) static
Common parsing and printing used for both named structured ops created by ods-gen and by manually defined C++ ops.
Common parsing used for both named structured ops created by ods-gen and by manually defined C++ ops.
Does not handle regions.
Definition at line 2572 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI32VectorAttr(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
Referenced by parseGenericOp(), and parseNamedStructuredOp().
parseCopyOpRegion()
ParseResult parseCopyOpRegion (OpAsmParser & parser, Region & r, Type inputType, Type outputType)
Definition at line 333 of file LinalgOps.cpp.
References mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), and mlir::success().
parseFillOpRegion()
ParseResult parseFillOpRegion (OpAsmParser & parser, Region & r, Type outputType, OpAsmParser::OperandType valueRef)
Definition at line 403 of file LinalgOps.cpp.
References mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::getElementTypeOrSelf(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseGenericOp()
static ParseResult parseGenericOp (OpAsmParser & parser, OperationState & result) static
Definition at line 604 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::NamedAttrList::assign(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::OpAsmParser::parseAttribute(), parseCommonStructuredOpParts(), mlir::OpAsmParser::parseEqual(), parseNamedStructuredOpResults(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::succeeded(), and mlir::success().
parseNamedStructuredOp()
template<typename NamedStructuredOpType > static ParseResult parseNamedStructuredOp (OpAsmParser & parser, OperationState & result, ArrayRef< OpAsmParser::OperandType > captures = {}) static
Definition at line 2657 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::failure(), parseCommonStructuredOpParts(), parseNamedStructuredOpResults(), and mlir::success().
parseNamedStructuredOpRegion()
template<typename NamedStructuredOpType > static ParseResult parseNamedStructuredOpRegion (OpAsmParser & parser, Region & region, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< OpAsmParser::OperandType > captures = {}) static
Specific parsing and printing for named structured ops created by ods-gen.
Definition at line 2625 of file LinalgOps.cpp.
References mlir::OpAsmParser::emitError(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), and mlir::success().
parseNamedStructuredOpResults()
static ParseResult parseNamedStructuredOpResults (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes) static
Definition at line 2647 of file LinalgOps.cpp.
References mlir::failure(), mlir::OpAsmParser::parseOptionalArrow(), mlir::OpAsmParser::parseTypeList(), mlir::succeeded(), and mlir::success().
Referenced by parseGenericOp(), and parseNamedStructuredOp().
parseTiledLoopOp()
static ParseResult parseTiledLoopOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1931 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::getIteratorTypesAttrName(), mlir::getParallelIteratorTypeName(), mlir::Value::getParentRegion(), mlir::Builder::getStringAttr(), mlir::Region::isAncestor(), mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseAssignmentListWithTypes(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
parseYieldOp()
static ParseResult parseYieldOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1764 of file LinalgOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OpAsmParser::resolveOperands().
print() [1/4]
static void print (OpAsmPrinter & p, GenericOp op) static
Definition at line 598 of file LinalgOps.cpp.
References printGenericOp().
print() [2/4]
static void print (OpAsmPrinter & p, IndexedGenericOp op) static
Definition at line 600 of file LinalgOps.cpp.
References printGenericOp().
print() [3/4]
static void print (OpAsmPrinter & p, linalg::YieldOp op) static
Definition at line 1755 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [4/4]
static void print (OpAsmPrinter & p, TiledLoopOp op) static
Definition at line 1894 of file LinalgOps.cpp.
References mlir::getIteratorTypesAttrName(), mlir::getParallelIteratorTypeName(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
printCommonStructuredOpParts()
template<typename NamedStructuredOpType > static void printCommonStructuredOpParts (OpAsmPrinter & p, NamedStructuredOpType op) static
Definition at line 2611 of file LinalgOps.cpp.
Referenced by printGenericOp(), and printNamedStructuredOp().
printCopyOpRegion()
void printCopyOpRegion (OpAsmPrinter & , Operation * , Region & , Type , Type)
CopyOp region is elided when printing.
Definition at line 342 of file LinalgOps.cpp.
printFillOpRegion()
void printFillOpRegion (OpAsmPrinter & , Operation * , Region & , Type , Value)
FillOp region is elided when printing.
Definition at line 416 of file LinalgOps.cpp.
printGenericOp()
template<typename GenericOpType > static void printGenericOp (OpAsmPrinter & p, GenericOpType op) static
Definition at line 557 of file LinalgOps.cpp.
References printCommonStructuredOpParts(), printNamedStructuredOpResults(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
Referenced by operator<<(), print(), and printDenseElementsAttrImpl().
printNamedStructuredOp()
template<typename NamedStructuredOpType > static void printNamedStructuredOp (OpAsmPrinter & p, NamedStructuredOpType op) static
Definition at line 2689 of file LinalgOps.cpp.
References printCommonStructuredOpParts(), printNamedStructuredOpResults(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printNamedStructuredOpResults()
static void printNamedStructuredOpResults (OpAsmPrinter & p, TypeRange resultTypes) static
Definition at line 2681 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalArrowTypeList().
Referenced by printGenericOp(), and printNamedStructuredOp().
verify() [1/15]
static LogicalResult verify (CopyOp op) static
Definition at line 344 of file LinalgOps.cpp.
References mlir::Type::dyn_cast(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::Value::getType(), mlir::OperationState::regions, and mlir::success().
Referenced by getGenericEffectsImpl(), and verifyGenericOp().
verify() [2/15]
static LogicalResult verify (FillOp op) static
Definition at line 418 of file LinalgOps.cpp.
References mlir::OpBuilder::createBlock(), mlir::Region::end(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArguments(), getElementType(), mlir::Builder::getIndexType(), mlir::Builder::getStrArrayAttr(), mlir::Builder::getStringAttr(), mlir::OperationState::location, mlir::OperationState::regions, and mlir::success().
verify() [3/15]
static LogicalResult verify (GenericOp op) static
Definition at line 734 of file LinalgOps.cpp.
References verifyGenericOp().
verify() [4/15]
static LogicalResult verify (IndexedGenericOp op) static
Definition at line 736 of file LinalgOps.cpp.
References mlir::OperationState::addAttributes(), dispatchIndexOpFoldResult(), elementType(), mlir::Builder::getI64ArrayAttr(), mlir::ShapedType::kDynamicSize, and verifyGenericOp().
verify() [5/15]
static LogicalResult verify (InitTensorOp op) static
Definition at line 756 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), getAsOpFoldResult(), mlir::Value::getDefiningOp(), mlir::Builder::getI64ArrayAttr(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), mlir::ShapedType::kDynamicSize, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and mlir::verifyListOfOperandsOrIntegers().
verify() [6/15]
static LogicalResult verify (PadTensorOp op) static
Definition at line 919 of file LinalgOps.cpp.
References mlir::OperationState::addAttributes(), mlir::linalg::applyMapToValues(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::OpBuilder::createOrFold(), dispatchIndexOpFoldResult(), mlir::Value::dyn_cast(), mlir::Region::end(), mlir::detail::enumerate(), extractFromI64ArrayAttr(), mlir::Region::front(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineSymbolExpr(), mlir::Block::getArgumentTypes(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::Block::getNumArguments(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::kDynamicSize, and mlir::success().
verify() [7/15]
static LogicalResult verify (ReshapeOp op) static
Definition at line 1607 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), computeReshapeCollapsedType(), mlir::failed(), mlir::failure(), getAffineMaps(), mlir::success(), and verifyReshapeLikeTypes().
verify() [8/15]
static LogicalResult verify (TensorReshapeOp op) static
Definition at line 1678 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), computeTensorReshapeCollapsedType(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), getAffineMaps(), getAsValues(), mlir::DenseElementsAttr::getFromRawBuffer(), mlir::DenseElementsAttr::getRawData(), getReshapeOutputShapeFromInputShape(), getShape(), mlir::DenseElementsAttr::isSplat(), mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and verifyReshapeLikeTypes().
verify() [9/15]
static LogicalResult verify (linalg::YieldOp op) static
Definition at line 1797 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OpBuilder::createBlock(), mlir::detail::enumerate(), mlir::Block::getArguments(), getElementType(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::getIteratorTypesAttrName(), mlir::Value::getType(), mlir::Type::isa(), mlir::OperationState::location, mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and verifyYield().
verify() [10/15]
static LogicalResult verify (TiledLoopOp op) static
Definition at line 2057 of file LinalgOps.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), foldMemRefCastInTiledLoopOp(), mlir::OpBuilder::getListener(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::RewritePatternSet::insert(), mlir::Type::isa(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::replaceOp(), mlir::success(), and mlir::Value::use_empty().
verify() [11/15]
static LogicalResult verify (IndexOp op) static
Definition at line 2265 of file LinalgOps.cpp.
References mlir::success().
verify() [12/15]
static LogicalResult verify (ConvOp op) static
Definition at line 2302 of file LinalgOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyStrideOrDilation().
verify() [13/15]
static LogicalResult verify (PoolingMaxOp op) static
Definition at line 2359 of file LinalgOps.cpp.
References verifySingleInputPoolingOp().
verify() [14/15]
static LogicalResult verify (PoolingMinOp op) static
Definition at line 2362 of file LinalgOps.cpp.
References verifySingleInputPoolingOp().
verify() [15/15]
static LogicalResult verify (PoolingSumOp op) static
Definition at line 2365 of file LinalgOps.cpp.
References DEFINE_POOLING_OP_GET_EFFECTS, and verifySingleInputPoolingOp().
verifyGenericOp()
template<typename GenericOpType > static LogicalResult verifyGenericOp (GenericOpType op) static
Definition at line 727 of file LinalgOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verify().
Referenced by verify().
verifyNamedStructuredOp()
template<typename NamedStructuredOpType > static LogicalResult verifyNamedStructuredOp (NamedStructuredOpType op) static
Definition at line 2708 of file LinalgOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::clone(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Block::eraseArgument(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Block::front(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Operation::getNumResults(), mlir::Operation::getResults(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Value::replaceAllUsesWith(), mlir::RewriterBase::replaceOp(), and mlir::success().
verifyReshapeLikeShapes()
template<typename OpTy > static LogicalResult verifyReshapeLikeShapes (OpTy op, ShapedType collapsedType, ShapedType expandedType, bool isExpandingReshape) static
Verify that shapes of the reshaped types using following rules 1) if a dimension in the collapsed type is static, then the corresponding dimensions in the expanded shape should be a) static b) the product should be same as the collaped shape.
2) if a dimension in the collaped type is dynamic, one and only one of the corresponding dimensions in the expanded type should be dynamic. This rule is only needed with reshape operations that are expanding.
Definition at line 1519 of file LinalgOps.cpp.
References mlir::detail::enumerate(), mlir::ShapedType::getShape(), mlir::ShapedType::isDynamic(), and mlir::success().
Referenced by verifyReshapeLikeTypes().
verifyReshapeLikeTypes()
template<typename Op , typename T > static LogicalResult verifyReshapeLikeTypes (Op op, T & expandedType, T & collapsedType) static
Definition at line 1564 of file LinalgOps.cpp.
References mlir::OpState::emitOpError(), mlir::detail::enumerate(), getAffineMaps(), isReassociationValid(), mlir::success(), and verifyReshapeLikeShapes().
Referenced by verify().
verifySingleInputPoolingOp()
template<typename PoolingOp > static LogicalResult verifySingleInputPoolingOp (PoolingOp op) static
Definition at line 2325 of file LinalgOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyStrideOrDilation().
Referenced by verify().
verifyStrideOrDilation()
template<typename LinalgPoolingOp > static LogicalResult verifyStrideOrDilation (LinalgPoolingOp op, ArrayRef< Attribute > attrs, bool isStride) static
Definition at line 2279 of file LinalgOps.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), and mlir::success().
Referenced by verify(), and verifySingleInputPoolingOp().
verifyYield()
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOpInterface) static
Definition at line 1776 of file LinalgOps.cpp.
References elementType(), and mlir::success().
Referenced by verify().