MLIR: lib/Dialect/MemRef/IR/MemRefOps.cpp File Reference
MemRefOps.cpp File Reference
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "llvm/ADT/STLExtras.h"
#include "mlir/Dialect/MemRef/IR/MemRefOps.cpp.inc"
Classes
struct SubViewReturnTypeCanonicalizer
Return the canonical type of the result of a subview.
struct SubViewCanonicalizer
A canonicalizer wrapper to replace SubViewOps.
Namespaces
saturated_arith
Helpers to write more idiomatic operations.
Macros
#define GET_OP_CLASSES
Enumerations
enum SubViewVerificationResult {
Success, RankTooLarge, SizeMismatch, ElemTypeMismatch,
MemSpaceMismatch, AffineMapMismatch
}
Functions
static SmallVector< int64_t, 4 > extractFromI64ArrayAttr (Attribute attr)
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
static void dispatchIndexOpFoldResult (OpFoldResult ofr, SmallVectorImpl< Value > &dynamicVec, SmallVectorImpl< int64_t > &staticVec, int64_t sentinel)
Helper function to dispatch an OpFoldResult into either the dynamicVec if it is a Value or into staticVec if it is an IntegerAttr.
static void dispatchIndexOpFoldResults (ArrayRef< OpFoldResult > ofrs, SmallVectorImpl< Value > &dynamicVec, SmallVectorImpl< int64_t > &staticVec, int64_t sentinel)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
static Type getTensorTypeFromMemRefType (Type type)
template<typename AllocLikeOp >
static LogicalResult verifyAllocLikeOp (AllocLikeOp op)
static LogicalResult verify (AllocOp op)
static LogicalResult verify (AllocaOp op)
static LogicalResult verify (AssumeAlignmentOp op)
static LogicalResult verify (CloneOp op)
static LogicalResult verify (DeallocOp op)
static LogicalResult verify (DimOp op)
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter &p, GlobalOp op, TypeAttr type, Attribute initialValue)
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser &parser, TypeAttr &typeAttr, Attribute &initialValue)
static LogicalResult verify (GlobalOp op)
static LogicalResult verify (LoadOp op)
static void print (OpAsmPrinter &p, PrefetchOp op)
static ParseResult parsePrefetchOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (PrefetchOp op)
static LogicalResult verify (ReinterpretCastOp op)
static LogicalResult verify (ReshapeOp op)
static LogicalResult verify (StoreOp op)
static SubViewVerificationResult isRankReducedType (Type originalType, Type candidateReducedType, std::string *errMsg=nullptr)
Checks if original Type type can be rank reduced to reduced type.
template<typename OpTy >
static LogicalResult produceSubViewErrorMsg (SubViewVerificationResult result, OpTy op, Type expectedType, StringRef errMsg="")
static LogicalResult verify (SubViewOp op)
Verifier for SubViewOp.
static MemRefType getCanonicalSubViewResultType (unsigned resultRank, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Infer the canonical type of the result of a subview operation.
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap)
Build a strided memref type by applying permutationMap tp memRefType.
static void print (OpAsmPrinter &p, TransposeOp op)
static ParseResult parseTransposeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TransposeOp op)
static ParseResult parseViewOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ViewOp op)
static LogicalResult verify (ViewOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2248 of file MemRefOps.cpp.
Enumeration Type Documentation
SubViewVerificationResult
enum SubViewVerificationResult
Enumerator
Success
RankTooLarge
SizeMismatch
ElemTypeMismatch
MemSpaceMismatch
AffineMapMismatch
Definition at line 1686 of file MemRefOps.cpp.
Function Documentation
dispatchIndexOpFoldResult()
static void dispatchIndexOpFoldResult (OpFoldResult ofr, SmallVectorImpl< Value > & dynamicVec, SmallVectorImpl< int64_t > & staticVec, int64_t sentinel) static
Helper function to dispatch an OpFoldResult into either the dynamicVec if it is a Value or into staticVec if it is an IntegerAttr.
In the case of a Value, a copy of the sentinel value is also pushed to staticVec. This is useful to extract mixed static and dynamic entries that come from an AttrSizedOperandSegments trait.
Definition at line 47 of file MemRefOps.cpp.
Referenced by dispatchIndexOpFoldResults().
dispatchIndexOpFoldResults()
static void dispatchIndexOpFoldResults (ArrayRef< OpFoldResult > ofrs, SmallVectorImpl< Value > & dynamicVec, SmallVectorImpl< int64_t > & staticVec, int64_t sentinel) static
Definition at line 60 of file MemRefOps.cpp.
References dispatchIndexOpFoldResult().
Referenced by verify().
extractFromI64ArrayAttr()
static SmallVector<int64_t, 4> extractFromI64ArrayAttr (Attribute attr) static
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
Definition at line 35 of file MemRefOps.cpp.
References mlir::Attribute::cast().
Referenced by verify().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref.cast into the root operation directly.
Definition at line 75 of file MemRefOps.cpp.
References mlir::Operation::getOpOperands(), and mlir::success().
Referenced by mlir::memref::DmaStartOp::fold(), mlir::memref::DmaWaitOp::fold(), and verify().
getCanonicalSubViewResultType()
static MemRefType getCanonicalSubViewResultType (unsigned resultRank, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Infer the canonical type of the result of a subview operation.
Returns a type with rank resultRank that is either the rank of the rank-reduced type, or the non-rank-reduced type.
Definition at line 1866 of file MemRefOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::failure(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by SubViewReturnTypeCanonicalizer::operator()().
getTensorTypeFromMemRefType()
static Type getTensorTypeFromMemRefType (Type type) static
Definition at line 91 of file MemRefOps.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::getContext().
Referenced by parseGlobalMemrefOpTypeAndInitialValue(), and verify().
inferTransposeResultType()
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap) static
Build a strided memref type by applying permutationMap tp memRefType.
Definition at line 1994 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::AffineMap::compose(), mlir::detail::enumerate(), mlir::AffineMap::getResults(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::makeStridedLinearLayoutMap(), mlir::MemRefType::Builder::setAffineMaps(), mlir::MemRefType::Builder::setShape(), and mlir::succeeded().
Referenced by verify().
isRankReducedType()
static SubViewVerificationResult isRankReducedType (Type originalType, Type candidateReducedType, std::string * errMsg = nullptr) static
Checks if original Type type can be rank reduced to reduced type.
This function is slight variant of is subsequence algorithm where not matching dimension must be 1.
Definition at line 1699 of file MemRefOps.cpp.
References AffineMapMismatch, mlir::Type::cast(), mlir::computeRankReductionMask(), mlir::AffineExpr::dyn_cast(), ElemTypeMismatch, mlir::ShapedType::getElementType(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::getProjectedMap(), mlir::AffineMap::getResult(), mlir::ShapedType::getShape(), mlir::getStridedLinearLayoutMap(), mlir::Type::isa(), MemSpaceMismatch, RankTooLarge, mlir::simplifyAffineExpr(), SizeMismatch, and Success.
Referenced by verify().
parseGlobalMemrefOpTypeAndInitialValue()
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser & parser, TypeAttr & typeAttr, Attribute & initialValue) static
Definition at line 1074 of file MemRefOps.cpp.
References mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getNameLoc(), getTensorTypeFromMemRefType(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseOptionalEqual(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
parsePrefetchOp()
static ParseResult parsePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1212 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseGreater(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
parseTransposeOp()
static ParseResult parseTransposeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2038 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMap(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseViewOp()
static ParseResult parseViewOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2083 of file MemRefOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
print() [1/3]
static void print (OpAsmPrinter & p, PrefetchOp op) static
Definition at line 1200 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [2/3]
static void print (OpAsmPrinter & p, TransposeOp op) static
Definition at line 2031 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/3]
static void print (OpAsmPrinter & p, ViewOp op) static
Definition at line 2108 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOperand(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printGlobalMemrefOpTypeAndInitialValue()
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter & p, GlobalOp op, TypeAttr type, Attribute initialValue) static
Definition at line 1060 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printAttributeWithoutType().
produceSubViewErrorMsg()
template<typename OpTy > static LogicalResult produceSubViewErrorMsg (SubViewVerificationResult result, OpTy op, Type expectedType, StringRef errMsg = "") static
Definition at line 1773 of file MemRefOps.cpp.
References AffineMapMismatch, mlir::Type::cast(), ElemTypeMismatch, MemSpaceMismatch, RankTooLarge, SizeMismatch, mlir::success(), and Success.
Referenced by verify().
verify() [1/15]
static LogicalResult verify (AllocOp op) static
Definition at line 126 of file MemRefOps.cpp.
References verifyAllocLikeOp().
verify() [2/15]
static LogicalResult verify (AllocaOp op) static
Definition at line 128 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), mlir::MemRefType::Builder::setShape(), mlir::success(), linalg.opdsl.lang.types::T, and verifyAllocLikeOp().
verify() [3/15]
static LogicalResult verify (AssumeAlignmentOp op) static
Definition at line 234 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), foldMemRefCast(), mlir::getStridesAndOffset(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
verify() [4/15]
static LogicalResult verify (CloneOp op) static
Definition at line 477 of file MemRefOps.cpp.
References mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::findDealloc(), foldMemRefCast(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::RewritePatternSet::insert(), mlir::RewriterBase::replaceOp(), mlir::succeeded(), and mlir::success().
verify() [5/15]
static LogicalResult verify (DeallocOp op) static
Definition at line 547 of file MemRefOps.cpp.
References mlir::OpBuilder::create(), foldMemRefCast(), mlir::Builder::getIndexType(), mlir::OperationState::location, and mlir::success().
verify() [6/15]
static LogicalResult verify (DimOp op) static
Definition at line 582 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Value::dyn_cast(), mlir::Type::dyn_cast(), mlir::Value::dyn_cast_or_null(), mlir::failed(), mlir::failure(), foldMemRefCast(), mlir::Builder::getIndexAttr(), mlir::Operation::getLoc(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointAfter(), mlir::succeeded(), and mlir::success().
verify() [7/15]
static LogicalResult verify (GlobalOp op) static
Definition at line 1103 of file MemRefOps.cpp.
References getTensorTypeFromMemRefType(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), and mlir::success().
verify() [8/15]
static LogicalResult verify (LoadOp op) static
Definition at line 1159 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::failure(), foldMemRefCast(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
verify() [9/15]
static LogicalResult verify (PrefetchOp op) static
Definition at line 1253 of file MemRefOps.cpp.
References mlir::OperationState::addAttributes(), dispatchIndexOpFoldResults(), foldMemRefCast(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, and mlir::success().
verify() [10/15]
static LogicalResult verify (ReinterpretCastOp op) static
Definition at line 1322 of file MemRefOps.cpp.
References mlir::Type::cast(), mlir::detail::enumerate(), extractFromI64ArrayAttr(), mlir::failed(), mlir::failure(), mlir::BaseMemRefType::getMemorySpace(), mlir::getStridesAndOffset(), and mlir::success().
verify() [11/15]
static LogicalResult verify (ReshapeOp op) static
Definition at line 1378 of file MemRefOps.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), getElementType(), mlir::ShapedType::kDynamicSize, and mlir::success().
verify() [12/15]
static LogicalResult verify (StoreOp op) static
Definition at line 1413 of file MemRefOps.cpp.
References foldMemRefCast(), and mlir::success().
verify() [13/15]
static LogicalResult verify (SubViewOp op) static
Verifier for SubViewOp.
Definition at line 1804 of file MemRefOps.cpp.
References extractFromI64ArrayAttr(), isRankReducedType(), mlir::isStrided(), and produceSubViewErrorMsg().
verify() [14/15]
static LogicalResult verify (TransposeOp op) static
Definition at line 2056 of file MemRefOps.cpp.
References foldMemRefCast(), inferTransposeResultType(), mlir::succeeded(), and mlir::success().
verify() [15/15]
static LogicalResult verify (ViewOp op) static
Definition at line 2116 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Value::getDefiningOp(), mlir::getStridesAndOffset(), mlir::ShapedType::isDynamic(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::MemRefType::Builder::setShape(), and mlir::success().
verifyAllocLikeOp()
template<typename AllocLikeOp > static LogicalResult verifyAllocLikeOp (AllocLikeOp op) static
Definition at line 104 of file MemRefOps.cpp.
References mlir::success().
Referenced by verify().