MLIR: mlir::edsc::op Namespace Reference
mlir::edsc::op Namespace Reference
Functions
Value operator+ (Value lhs, Value rhs)
Value operator- (Value lhs, Value rhs)
Value operator* (Value lhs, Value rhs)
Value operator/ (Value lhs, Value rhs)
Value operator% (Value lhs, Value rhs)
Value floorDiv (Value lhs, Value rhs)
Value ceilDiv (Value lhs, Value rhs)
Value negate (Value value)
Logical operator overloadings.
Value operator && (Value lhs, Value rhs)
Value operator|| (Value lhs, Value rhs)
Value operator^ (Value lhs, Value rhs)
Value eq (Value lhs, Value rhs)
Comparison operator overloadings.
Value ne (Value lhs, Value rhs)
Value slt (Value lhs, Value rhs)
Value sle (Value lhs, Value rhs)
Value sgt (Value lhs, Value rhs)
Value sge (Value lhs, Value rhs)
Value ult (Value lhs, Value rhs)
Value ule (Value lhs, Value rhs)
Value ugt (Value lhs, Value rhs)
Value uge (Value lhs, Value rhs)
Function Documentation
ceilDiv()
Value mlir::edsc::op::ceilDiv (Value lhs, Value rhs)
Definition at line 187 of file Builders.cpp.
References mlir::AffineExpr::ceilDiv(), and createBinaryIndexHandle().
eq()
Value mlir::edsc::op::eq (Value lhs, Value rhs)
Comparison operator overloadings.
Definition at line 237 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::FlatAffineConstraints::addAffineForOpDomain(), addMemRefAccessConstraints(), addOrderingConstraints(), mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), mlir::LinearTransform::applyTo(), computeDirectionVector(), mlir::edsc::TemplatedIndexedValue< Load, Store >::eq(), genIf(), genWhileInduction(), mlir::SDBM::get(), getAtomicOpScope(), mlir::FlatAffineConstraints::getConstantBoundOnDimSize(), getICmpPredicate(), mlir::FlatAffineConstraints::getInequality(), getLLVMCmpPredicate(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), getNewNumDimsSymbols(), mlir::lowerAffineLowerBound(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), mlir::SimpleAffineExprFlattener::visitDimExpr(), and mlir::SimpleAffineExprFlattener::visitSymbolExpr().
floorDiv()
Value mlir::edsc::op::floorDiv (Value lhs, Value rhs)
Definition at line 182 of file Builders.cpp.
References createBinaryIndexHandle(), and mlir::AffineExpr::floorDiv().
ne()
Value mlir::edsc::op::ne (Value lhs, Value rhs)
Definition at line 243 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), createLinalgBodyCalculationForElementwiseOp(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::ne(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), and verify().
negate()
Value mlir::edsc::op::negate (Value value)
Logical operator overloadings.
Definition at line 192 of file Builders.cpp.
References mlir::Value::getType(), mlir::Type::isInteger(), and operator &&().
Referenced by createLinalgBodyCalculationForElementwiseOp().
operator &&()
Value mlir::edsc::op::operator&& (Value lhs, Value rhs)
Referenced by negate(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().
operator%()
Value mlir::edsc::op::operator% (Value lhs, Value rhs)
Definition at line 177 of file Builders.cpp.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs(), and mlir::AffineExpr::operator!().
operator*()
Value mlir::edsc::op::operator* (Value lhs, Value rhs)
Definition at line 165 of file Builders.cpp.
operator+()
Value mlir::edsc::op::operator+ (Value lhs, Value rhs)
Definition at line 155 of file Builders.cpp.
operator-()
Value mlir::edsc::op::operator- (Value lhs, Value rhs)
Definition at line 160 of file Builders.cpp.
operator/()
Value mlir::edsc::op::operator/ (Value lhs, Value rhs)
Definition at line 170 of file Builders.cpp.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs().
operator^()
Value mlir::edsc::op::operator^ (Value lhs, Value rhs)
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs().
operator||()
Value mlir::edsc::op::operator|| (Value lhs, Value rhs)
Definition at line 203 of file Builders.cpp.
References mlir::Value::getType(), and mlir::Type::isInteger().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().
sge()
Value mlir::edsc::op::sge (Value lhs, Value rhs)
Definition at line 267 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), createLinalgBodyCalculationForElementwiseOp(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), getPaddedInput(), mlir::lowerAffineLowerBound(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), reduceMatchAndRewriteHelper(), replaceOpWithRegion(), mlir::edsc::TemplatedIndexedValue< Load, Store >::sge(), mlir::vector::unrollSingleResultVectorOp(), and mlir::LLVM::detail::vectorOneToOneRewrite().
sgt()
Value mlir::edsc::op::sgt (Value lhs, Value rhs)
Definition at line 261 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), emitPoolingMinMaxScalarImplementation(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::ops::linalg_generic_pointwise_max(), lowerAffineMapMax(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), reduceMatchAndRewriteHelper(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::sgt().
sle()
Value mlir::edsc::op::sle (Value lhs, Value rhs)
Definition at line 255 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), createScopedFoldedSLE(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::sle().
slt()
Value mlir::edsc::op::slt (Value lhs, Value rhs)
Definition at line 249 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), applyMapToValues(), buildVectorComparison(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), emitPoolingMinMaxScalarImplementation(), mlir::linalg::generateParallelLoopNest(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), getPaddedInput(), lowerAffineMapMin(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), processParallelLoop(), reduceMatchAndRewriteHelper(), mlir::edsc::TemplatedIndexedValue< Load, Store >::slt(), stripmineSink(), and mlir::vector::unrollSingleResultVectorOp().
uge()
Value mlir::edsc::op::uge (Value lhs, Value rhs)
Definition at line 291 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), mlir::populateSPIRVToLLVMConversionPatterns(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::uge().
ugt()
Value mlir::edsc::op::ugt (Value lhs, Value rhs)
Definition at line 285 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::ugt().
ule()
Value mlir::edsc::op::ule (Value lhs, Value rhs)
Definition at line 279 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::ule().
ult()
Value mlir::edsc::op::ult (Value lhs, Value rhs)
Definition at line 273 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), applyCmpPredicateToEqualOperands(), genLocals(), genWhile(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::ult().