MLIR: linalg.opdsl.ops.core_named_ops Namespace Reference
linalg.opdsl.ops.core_named_ops Namespace Reference
Functions
def matmul (A=TensorDef(T1, S.M, S.K), B=TensorDef(T2, S.K, S.N), C=TensorDef(U, S.M, S.N, output=True))
def batch_matmul (A=TensorDef(T1, Batch, S.M, S.K), B=TensorDef(T2, Batch, S.K, S.N), C=TensorDef(U, Batch, S.M, S.N, output=True))
def matvec (A=TensorDef(T1, S.M, S.N), y=TensorDef(T2, S.N), x=TensorDef(U, S.M, output=True))
def vecmat (y=TensorDef(T1, S.M), A=TensorDef(T2, S.M, S.N), x=TensorDef(U, S.N, output=True))
def dot (A=TensorDef(T1, S.M), B=TensorDef(T2, S.M), C=TensorDef(U, output=True))
Variables
T1 = TV.T1
T2 = TV.T2
Batch = S.Batch
Function Documentation
batch_matmul()
def linalg.opdsl.ops.core_named_ops.batch_matmul (A = TensorDef(T1, Batch, S.M, S.K), B = TensorDef(T2, Batch, S.K, S.N), C = TensorDef(U, Batch, S.M, S.N, output=True))
Performs a batched matrix multiplication of two 3D inputs.
Numeric casting is performed on the operands to the inner multiply, promoting
them to the same data type as the accumulator/output.
Definition at line 25 of file core_named_ops.py.
References linalg.opdsl.lang.dsl.implements(), and linalg.opdsl.ops.core_named_ops.matvec().
Referenced by linalg.opdsl.ops.core_named_ops.matmul().
dot()
def linalg.opdsl.ops.core_named_ops.dot (A = TensorDef(T1, S.M), B = TensorDef(T2, S.M), C = TensorDef(U, output=True))
Performs a dot product of two vectors to a scalar result.
Numeric casting is performed on the operands to the inner multiply, promoting
them to the same data type as the accumulator/output.
Definition at line 63 of file core_named_ops.py.
References linalg.opdsl.lang.dsl.implements().
Referenced by linalg.opdsl.ops.core_named_ops.vecmat().
matmul()
def linalg.opdsl.ops.core_named_ops.matmul (A = TensorDef(T1, S.M, S.K), B = TensorDef(T2, S.K, S.N), C = TensorDef(U, S.M, S.N, output=True))
Performs a matrix multiplication of two 2D inputs.
Numeric casting is performed on the operands to the inner multiply, promoting
them to the same data type as the accumulator/output.
Definition at line 12 of file core_named_ops.py.
References linalg.opdsl.ops.core_named_ops.batch_matmul(), and linalg.opdsl.lang.dsl.implements().
matvec()
def linalg.opdsl.ops.core_named_ops.matvec (A = TensorDef(T1, S.M, S.N), y = TensorDef(T2, S.N), x = TensorDef(U, S.M, output=True))
Performs a matrix-vector multiplication.
Numeric casting is performed on the operands to the inner multiply, promoting
them to the same data type as the accumulator/output.
Definition at line 38 of file core_named_ops.py.
References linalg.opdsl.lang.dsl.implements(), and linalg.opdsl.ops.core_named_ops.vecmat().
Referenced by linalg.opdsl.ops.core_named_ops.batch_matmul().
vecmat()
def linalg.opdsl.ops.core_named_ops.vecmat (y = TensorDef(T1, S.M), A = TensorDef(T2, S.M, S.N), x = TensorDef(U, S.N, output=True))
Performs a vector-matrix multiplication.
Numeric casting is performed on the operands to the inner multiply, promoting
them to the same data type as the accumulator/output.
Definition at line 51 of file core_named_ops.py.
References linalg.opdsl.ops.core_named_ops.dot(), and linalg.opdsl.lang.dsl.implements().
Referenced by linalg.opdsl.ops.core_named_ops.matvec().
Variable Documentation
Batch
linalg.opdsl.ops.core_named_ops.Batch = S.Batch
Definition at line 6 of file core_named_ops.py.
T1
linalg.opdsl.ops.core_named_ops.T1 = TV.T1
Definition at line 3 of file core_named_ops.py.
T2
linalg.opdsl.ops.core_named_ops.T2 = TV.T2
Definition at line 4 of file core_named_ops.py.