MLIR: linalg.opdsl.dump_oplib Namespace Reference
linalg.opdsl.dump_oplib Namespace Reference
Functions
def create_arg_parser ()
def load_module_from_file (module_name, file_path)
def main (args)
Function Documentation
create_arg_parser()
def linalg.opdsl.dump_oplib.create_arg_parser (argparse, ArgumentParser)
Definition at line 33 of file dump_oplib.py.
Referenced by linalg.opdsl.dump_oplib.main().
load_module_from_file()
def linalg.opdsl.dump_oplib.load_module_from_file (module_name, file_path)
Definition at line 54 of file dump_oplib.py.
Referenced by linalg.opdsl.dump_oplib.main().
main()
def linalg.opdsl.dump_oplib.main (args)
Definition at line 61 of file dump_oplib.py.
References linalg.opdsl.dump_oplib.create_arg_parser(), mlir::detail.enumerate(), linalg.opdsl.dump_oplib.load_module_from_file(), print(), and linalg.opdsl.lang.yaml_helper.yaml_dump_all().