MLIR: _linalg_ops_ext Namespace Reference
_linalg_ops_ext Namespace Reference
Classes
class FillOp
class InitTensorOp
class StructuredOpMixin
Functions
def isa
def select_opview_mixin (parent_opview_cls)
Function Documentation
isa()
def _linalg_ops_ext.isa (cls)
Definition at line 13 of file _linalg_ops_ext.py.
Referenced by _linalg_ops_ext.FillOp.__init__(), getTreePredicates(), mlir::AffineExpr.operator!(), mlir::pdl_to_pdl_interp::TypePosition.TypePosition(), and verify().
select_opview_mixin()
def _linalg_ops_ext.select_opview_mixin (parent_opview_cls)
Definition at line 100 of file _linalg_ops_ext.py.