MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Namespaces
detail
Classes
struct AffineMapAndOperands
Helper struct to return the results of substituteMin.
struct AffineMinRangeCanonicalizationPattern
Canonicalize AffineMinOp operations in the context of ops with a known range by:
struct AffineMinSCFCanonicalizationPattern
Specialized version of AffineMinRangeCanonicalizationPattern pattern using getSCFMinMaxExpr to know the min and max expression of induction variables from scf loops.
class Aliases
A very primitive alias analysis which just records for each view, either:
struct CodegenStrategy
Codegen strategy controls how a Linalg op is progressively lowered.
class ConvOpVectorization
Converts Convolution op into vector contraction.
class CopyOpToLibraryCallRewrite
Rewrite pattern specialization for CopyOp, kicks in when both input and output permutations are left unspecified or are the identity.
class CopyTransposeRewrite
Rewrite CopyOp with permutations into a sequence of TransposeOp and permutation-free CopyOp.
struct FusionInfo
A struct containing the Linalg producer before and after fusion.
struct GenerateLoopNest
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
class IndexedGenericOpToLibraryCallRewrite
Conversion pattern specialization for IndexedGenericOp, has special handling for the extra index operands.
struct LateCodegenStrategyOptions
Options to control the application of late transformations.
struct LinalgBaseInterchangePattern
Linalg interchange patterns.
struct LinalgBasePromotionPattern
Linalg promotion patterns.
struct LinalgBaseTileAndFusePattern
struct LinalgBaseTilingPattern
Base pattern that applied the tiling transformation specified by options.
struct LinalgBaseVectorizationPattern
struct LinalgCopyVTRForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
struct LinalgCopyVTWForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
class LinalgDependenceGraph
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
struct LinalgElementwiseFusionOptions
Options that control fusion of elementwise operations.
struct LinalgFusionOptions
struct LinalgInterchangePattern
struct LinalgLoopDistributionOptions
Options that allow distribution of loops generated in Linalg transforms to processors while generating the loops.
struct LinalgLoweringPattern
class LinalgOpToLibraryCallRewrite
struct LinalgPromotionOptions
struct LinalgPromotionPattern
struct LinalgTileAndFusePattern
struct LinalgTilingOptions
struct LinalgTilingPattern
struct LinalgTransformationFilter
Helper class to control application of linalg transformation patterns.
struct LinalgTransforms
struct LinalgVectorizationOptions
Linalg vectorization patterns.
struct LinalgVectorizationPattern
struct PadTensorOpVectorizationPattern
PadTensorOp does not implement the LinalgStructuredOpInterface LinalgOp, it needs a specific pattern to vectorize.
struct ProcInfo
Callback function type used to get processor ID, and number of processors used for distribution for all parallel loops generated.
struct Promote
Promotion transformation enqueues a particular stage-1 pattern for Promote<LinalgOpType>with the appropriate options.
struct PromotionInfo
Creates a new buffer using the allocationFn provided.
class RangeType
A RangeType represents a minimal range abstraction (min, max, step).
struct RegionMatcher
A struct containing common matchers over linalg op's region.
struct SparsificationOptions
Sparsification options.
struct Tile
Promotion transformation enqueues a particular stage-1 pattern for Tile<LinalgOpType>with the appropriate options.
struct TiledAndFusedLinalgOps
Fuse a sequence of linalg operations (ops) using tile-and-fuse.
struct TiledLinalgOp
Performs standalone tiling of a single LinalgOp by tileSizes.
struct Transformation
Abstract Transformation class applied in a sequence that also handles state through markers.
struct Vectorize
Vectorization transformation enqueues a particular stage-1 pattern for LinalgVectorizationPattern<LinalgOpType> as well as copy to vector transfer rewrite forwarding patterns.
Typedefs
using LoopRangeBuilder = std::function< SmallVector< Range, 4 >(OpBuilder &, Location)>
using ReassociationIndices = SmallVector< int64_t, 2 >
using ReassociationIndicesRef = ArrayRef< int64_t >
using ReassociationExprs = SmallVector< AffineExpr, 2 >
using LinalgLoops = SmallVector< Operation *, 4 >
using ControlElementwiseOpsFusionFn = std::function< bool(const OpResult &producer, const OpOperand &consumer)>
using AllocBufferCallbackFn = std::function< Optional< Value >(OpBuilder &b, memref::SubViewOp subView, ArrayRef< Value > boundingSubViewSize, DataLayout &layout, OperationFolder *folder)>
Callback function type used to perform the allocation for the promoted subView.
using DeallocBufferCallbackFn = std::function< LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
using CopyCallbackFn = std::function< LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
using TileSizeComputationFunction = std::function< SmallVector< Value, 4 >(OpBuilder &, Operation *)>
using PaddingValueComputationFunction = std::function< Value(OpBuilder &, OpOperand &)>
Specify the padding value for an OpOperand.
template<typename T , typename... Args>
using has_get_operation_name = decltype(T::getOperationName())
Trait to check if T provides a getOperationName method.
template<typename T >
using detect_has_get_operation_name = llvm::is_detected< has_get_operation_name, T >
using GetMinMaxExprFn = std::function< Optional< std::pair< AffineExpr, AffineExpr > >(Value value, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols)>
using FusableOpDependencesTy = llvm::MapVector< Operation *, SmallVector< LinalgDependenceGraph::LinalgDependenceGraphElem, 1 > >
using ProcInfoCallBackFn = std::function< SmallVector< ProcInfo, 2 >(OpBuilder &b, Location loc, ArrayRef< Range > parallelLoopRanges)>
Enumerations
enum LinalgTilingLoopType { LinalgTilingLoopType::Loops = 0, LinalgTilingLoopType::AffineLoops = 1, LinalgTilingLoopType::ParallelLoops = 2, LinalgTilingLoopType::TiledLoops = 3 }
Linalg tiling patterns.
enum LinalgLoweringType { LinalgLoweringType::LibraryCall = 0, LinalgLoweringType::Loops = 1, LinalgLoweringType::AffineLoops = 2, LinalgLoweringType::ParallelLoops = 3 }
Linalg lowering patterns.
enum SparseParallelizationStrategy {
SparseParallelizationStrategy::kNone, SparseParallelizationStrategy::kDenseOuterLoop, SparseParallelizationStrategy::kAnyStorageOuterLoop, SparseParallelizationStrategy::kDenseAnyLoop,
SparseParallelizationStrategy::kAnyStorageAnyLoop
}
Defines a parallelization strategy.
enum SparseVectorizationStrategy { SparseVectorizationStrategy::kNone, SparseVectorizationStrategy::kDenseInnerLoop, SparseVectorizationStrategy::kAnyStorageInnerLoop }
Defines a vectorization strategy.
enum SparseIntType {
SparseIntType::kNative, SparseIntType::kI64, SparseIntType::kI32, SparseIntType::kI16,
SparseIntType::kI8
}
Defines a type for "pointer" and "index" storage in the sparse storage scheme, with a choice between the native platform-dependent index width or any of 64-/32-/16-/8-bit integers.
enum DistributionMethod { DistributionMethod::Cyclic = 0, DistributionMethod::CyclicNumProcsGeNumIters = 1, DistributionMethod::CyclicNumProcsEqNumIters = 2 }
Scheme used to distribute loops to processors.
Functions
void populateLinalgToStandardConversionPatterns (RewritePatternSet &patterns)
Populate the given list with patterns that convert from Linalg to Standard.
SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ValueRange values)
Returns the values obtained by applying map to the list of values.
bool isaContractionOpInterface (LinalgOp linalgOp)
Checks whether linalgOp conforms to ContractionOpInterface.
LoopRangeBuilder defaultLoopRangesBuilder (LinalgOp op)
Provide a very simple inference procedure to build the loop ranges from the op and its operands.
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &startIdx, MLIRContext *context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
template<typename PoolingOp >
SmallVector< AffineExpr, 4 > weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
void getDimsOfType (Operation *op, StringRef iteratorTypeName, SmallVectorImpl< AffineExpr > &res)
Return the dims that are iteratorTypeName loops in the LinalgOp op.
template<template< typename > class PatternType, typename ConcreteOpType , typename OptionsType , typename = std::enable_if_t<std::is_member_function_pointer< decltype(&ConcreteOpType::getOperationName)>::value>>
void sfinae_enqueue (RewritePatternSet &patternList, OptionsType options, StringRef opName, linalg::LinalgTransformationFilter m)
SFINAE: Enqueue helper for ConcreteOpType that have a getOperationName.
template<template< typename > class PatternType, typename OpType , typename OptionsType >
void sfinae_enqueue (RewritePatternSet &patternList, OptionsType options, StringRef opName, linalg::LinalgTransformationFilter m)
SFINAE: Enqueue helper for OpType that do not have a getOperationName (e.g.
template<typename PatternType , typename OpType , typename OptionsType >
void enqueue (RewritePatternSet &patternList, OptionsType options, StringRef opName, linalg::LinalgTransformationFilter m)
void hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write on buffers pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
void hoistRedundantVectorTransfersOnTensor (FuncOp func)
Same behavior as hoistRedundantVectorTransfers but works on tensors instead of buffers.
LogicalResult hoistPaddingOnTensors (PadTensorOp &padTensorOp, unsigned nLoops)
Mechanically hoist padding operations on tensors by nLoops into a new, generally larger tensor.
void populateConvVectorizationPatterns (MLIRContext *context, SmallVectorImpl< RewritePatternSet > &patterns, ArrayRef< int64_t > tileSizes)
Populates patterns for vectorization of all ConvN-D ops.
void populateElementwiseToLinalgConversionPatterns (RewritePatternSet &patterns)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
void populateFoldReshapeOpsByExpansionPatterns (RewritePatternSet &patterns, bool allowFoldingUnitDimReshapes=false)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
void populateFoldReshapeOpsByLinearizationPatterns (RewritePatternSet &patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic/indexed_generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic/indexed_generic operation.
void populateFoldUnitDimsReshapeOpsByLinearizationPatterns (RewritePatternSet &patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic/indexed_generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic/indexed_generic operation.
void populateLinalgBufferizePatterns (BufferizeTypeConverter &converter, RewritePatternSet &patterns)
Populates the given list with patterns to bufferize linalg ops.
void populateFoldUnitExtentDimsPatterns (RewritePatternSet &patterns)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors.
void populateElementwiseOpsFusionPatterns (RewritePatternSet &patterns, LinalgElementwiseFusionOptions options=LinalgElementwiseFusionOptions())
Patterns for fusing linalg operation on tensors.
void populatePushReshapeOpsPatterns (RewritePatternSet &patterns)
Patterns to push reshape op towards the end of the graph in order to expose more fusion opportunities.
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, const LinalgTilingOptions &options)
Optional< TiledAndFusedLinalgOps > tileAndFuseLinalgOps (OpBuilder &builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph, const LinalgTilingOptions &tilingOptions)
void interchange (PatternRewriter &rewriter, LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions and adapts the index accesses of op.
Optional< PromotionInfo > promoteSubviewAsNewBuffer (OpBuilder &b, Location loc, memref::SubViewOp subView, AllocBufferCallbackFn allocationFn, DataLayout &layout, OperationFolder *folder=nullptr)
Optional< LinalgOp > promoteSubViews (OpBuilder &b, LinalgOp op, LinalgPromotionOptions options, OperationFolder *folder=nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
LogicalResult vectorizeLinalgOp (OpBuilder &builder, Operation *op, SmallVectorImpl< Value > &newResults)
Emit a suitable vector form for a Linalg op with fully static shape.
template<typename LoopTy >
Optional< LinalgLoops > linalgLowerOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of LoopTy with the proper body for op.
LogicalResult linalgOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of scf.for with the proper body for op.
LogicalResult linalgOpToParallelLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of scf.parallel with the proper body for op.
LogicalResult linalgOpToAffineLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of affine.for with the proper body for op.
LogicalResult interchangeGenericLinalgOpPrecondition (Operation *op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
LogicalResult promoteSubviewsPrecondition (Operation *op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
LogicalResult vectorizeLinalgOpPrecondition (Operation *op)
Rewrite a linalg.generic into a suitable vector.contraction op.
RewritePatternSet getLinalgTilingCanonicalizationPatterns (MLIRContext *ctx)
Canonicalization patterns relevant to apply after tiling patterns.
void populateLinalgTilingCanonicalizationPatterns (RewritePatternSet &patterns)
template<typename OpType , typename = std::enable_if_t<detect_has_get_operation_name<OpType>::value>, typename = void>
void insertVectorizationPatternImpl (RewritePatternSet &patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ op with a getOperationName method.
template<typename OpType , typename = std::enable_if_t< !detect_has_get_operation_name<OpType>::value>>
void insertVectorizationPatternImpl (RewritePatternSet &patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ class without a getOperationName method (e.g.
template<typename... OpTypes>
void insertVectorizationPatterns (RewritePatternSet &patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f=linalg::LinalgTransformationFilter())
Variadic helper function to insert vectorization patterns for C++ ops.
void populateLinalgNamedOpsGeneralizationPatterns (RewritePatternSet &patterns, LinalgTransformationFilter filter=LinalgTransformationFilter())
Linalg generalization patterns.
void populateLinalgConvGeneralizationPatterns (RewritePatternSet &patterns, LinalgTransformationFilter filter=LinalgTransformationFilter())
Populates patterns with patterns to convert linalg.conv ops to linalg.generic ops.
AffineMapAndOperands substituteMin (AffineMinOp affineMinOp, GetMinMaxExprFn getMinMaxExpr)
Traverse the dims of the AffineMap of affineMinOp and substitute dimensions with known range by new expressions involving the min or max expression:
LogicalResult applyStagedPatterns (Operation *op, ArrayRef< FrozenRewritePatternSet > stage1Patterns, const FrozenRewritePatternSet &stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda=nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
void populateSparsificationPatterns (RewritePatternSet &patterns, const SparsificationOptions &options=SparsificationOptions())
Sets up sparsification rewriting rules with the given options.
template<typename T , unsigned N>
void applyPermutationToVector (SmallVector< T, N > &inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
IntegerAttr getSmallestBoundingIndex (Value size)
If size comes from an AffineMinOp and one of the values of AffineMinOp is a constant then return a new value set to the smallest such constant.
bool isParallelIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isReductionIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isWindowIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isProducerLastWriteOfView (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
bool isFusableInto (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
SmallVector< Value, 4 > makeTiledShapes (OpBuilder &builder, Location loc, LinalgOp linalgOp, ArrayRef< Value > tiledOperands, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Creates subtensor/subview ops for all tiledOperands of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
FusableOpDependencesTy findAllFusableDependences (ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph)
Find all dependences that are fusable.
Optional< FusionInfo > fuseProducerOfBuffer (OpBuilder &b, OpOperand &consumerOpOperand, const LinalgDependenceGraph &graph)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Optional< FusionInfo > fuseProducerOfTensor (OpBuilder &b, OpOperand &consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
Optional< FusionInfo > fuseProducerOfTensor (OpBuilder &b, OpResult producerOpResult, OpOperand &consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
void updateBoundsForCyclicDistribution (OpBuilder &builder, Location loc, Value procId, Value nprocs, Value &lb, Value &ub, Value &step)
Update the lb, ub and step to get per processor lb, ub and step.
static void generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage, ArrayRef< DistributionMethod > distributionMethod={})
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
Typedef Documentation
AllocBufferCallbackFn
using mlir::linalg::AllocBufferCallbackFn = typedef std::function<Optional<Value>(OpBuilder &b, memref::SubViewOp subView, ArrayRef<Value> boundingSubViewSize, DataLayout &layout, OperationFolder *folder)>
Callback function type used to perform the allocation for the promoted subView.
In boundingSubViewsize a best attempt is made to find the smallest constant value for the size of the buffer needed for each dimension. If that is not possible, contains the dynamic size of the subview. The call back should return the buffer to use.
Definition at line 221 of file Transforms.h.
ControlElementwiseOpsFusionFn
using mlir::linalg::ControlElementwiseOpsFusionFn = typedef std::function<bool(const OpResult &producer, const OpOperand &consumer)>
Definition at line 75 of file Transforms.h.
CopyCallbackFn
using mlir::linalg::CopyCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
The copy has to happen from src to dst.
Definition at line 233 of file Transforms.h.
DeallocBufferCallbackFn
using mlir::linalg::DeallocBufferCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
Definition at line 226 of file Transforms.h.
detect_has_get_operation_name
template<typename T > using mlir::linalg::detect_has_get_operation_name = typedef llvm::is_detected<has_get_operation_name, T>
Definition at line 746 of file Transforms.h.
FusableOpDependencesTy
using mlir::linalg::FusableOpDependencesTy = typedef llvm::MapVector< Operation *, SmallVector<LinalgDependenceGraph::LinalgDependenceGraphElem, 1> >
Definition at line 103 of file Utils.h.
GetMinMaxExprFn
using mlir::linalg::GetMinMaxExprFn = typedef std::function<Optional<std::pair<AffineExpr, AffineExpr> >(Value value, SmallVectorImpl<Value> &dims, SmallVectorImpl<Value> &symbols)>
Definition at line 932 of file Transforms.h.
has_get_operation_name
template<typename T , typename... Args> using mlir::linalg::has_get_operation_name = typedef decltype(T::getOperationName())
Trait to check if T provides a getOperationName method.
Definition at line 743 of file Transforms.h.
LinalgLoops
using mlir::linalg::LinalgLoops = typedef SmallVector<Operation *, 4>
Definition at line 34 of file Transforms.h.
LoopRangeBuilder
using mlir::linalg::LoopRangeBuilder = typedef std::function<SmallVector<Range, 4>(OpBuilder &, Location)>
Definition at line 44 of file LinalgOps.h.
PaddingValueComputationFunction
using mlir::linalg::PaddingValueComputationFunction = typedef std::function<Value(OpBuilder &, OpOperand &)>
Specify the padding value for an OpOperand.
This should be a function of both the operation and the operand type.
Definition at line 438 of file Transforms.h.
ProcInfoCallBackFn
using mlir::linalg::ProcInfoCallBackFn = typedef std::function<SmallVector<ProcInfo, 2>(OpBuilder &b, Location loc, ArrayRef<Range> parallelLoopRanges)>
Definition at line 191 of file Utils.h.
ReassociationExprs
using mlir::linalg::ReassociationExprs = typedef SmallVector<AffineExpr, 2>
Definition at line 57 of file LinalgOps.h.
ReassociationIndices
using mlir::linalg::ReassociationIndices = typedef SmallVector<int64_t, 2>
Definition at line 55 of file LinalgOps.h.
ReassociationIndicesRef
using mlir::linalg::ReassociationIndicesRef = typedef ArrayRef<int64_t>
Definition at line 56 of file LinalgOps.h.
TileSizeComputationFunction
using mlir::linalg::TileSizeComputationFunction = typedef std::function<SmallVector<Value, 4>(OpBuilder &, Operation *)>
Definition at line 433 of file Transforms.h.
Enumeration Type Documentation
DistributionMethod
enum mlir::linalg::DistributionMethod strong
Scheme used to distribute loops to processors.
Enumerator
Cyclic
Cyclic distribution where no assumption is made about the dynamic relationship between number of processors and number of iterations of the distributed loop.
Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
scf.parallel(iv)= (lb + procId * step) to (ub) step (step * nprocs)
CyclicNumProcsGeNumIters
Cyclic distribution where the number of processors can be assumed to be more than or equal to the number of iterations of the distributed loop.
In such cases, a simple in-bounds check is enough (instead of materializing a loop). Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step cond = cmpi "slt", iv, ub scf.if cond { ... }
CyclicNumProcsEqNumIters
Cyclic distribution where the number of processors can be assumed to be equal to the number of iterations of the distributed loop.
In such cases, no bounds check is needed. Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step
Definition at line 144 of file Utils.h.
LinalgLoweringType
enum mlir::linalg::LinalgLoweringType strong
Linalg lowering patterns.
Apply the linalgLowerOpToLoops transformation as a pattern. filter controls LinalgTransformMarker matching and update when specified. See linalgLowerOpToLoops for more details.
Enumerator
LibraryCall
Loops
AffineLoops
ParallelLoops
Definition at line 789 of file Transforms.h.
LinalgTilingLoopType
enum mlir::linalg::LinalgTilingLoopType strong
Linalg tiling patterns.
Apply the tileLinalgOp transformation as a pattern. filter controls LinalgTransformMarker matching and update when specified. See tileLinalgOp for more details.
Enumerator
Loops
AffineLoops
ParallelLoops
TiledLoops
Definition at line 425 of file Transforms.h.
SparseIntType
enum mlir::linalg::SparseIntType strong
Defines a type for "pointer" and "index" storage in the sparse storage scheme, with a choice between the native platform-dependent index width or any of 64-/32-/16-/8-bit integers.
A narrow width obviously reduces the memory footprint of the sparse storage scheme, but the width should suffice to define the total required range (viz. the maximum number of stored entries per indirection level for the "pointers" and the maximum value of each tensor index over all dimensions for the "indices").
Enumerator
kNative
kI64
kI32
kI16
kI8
Definition at line 1105 of file Transforms.h.
SparseParallelizationStrategy
enum mlir::linalg::SparseParallelizationStrategy strong
Defines a parallelization strategy.
Any implicit loop in the Linalg operation that is marked "parallel" (thus not "reduction") is a candidate for parallelization. The loop is made parallel if (1) allowed by the strategy (e.g., AnyStorageOuterLoop considers either a dense or sparse outermost loop only), and (2) the generated code is an actual for-loop (and not a co-iterating while-loop).
Enumerator
kNone
kDenseOuterLoop
kAnyStorageOuterLoop
kDenseAnyLoop
kAnyStorageAnyLoop
Definition at line 1078 of file Transforms.h.
SparseVectorizationStrategy
enum mlir::linalg::SparseVectorizationStrategy strong
Defines a vectorization strategy.
Any implicit inner loop in the Linalg operation is a candidate (full SIMD for "parallel" loops and horizontal SIMD for "reduction" loops). A loop is actually vectorized if (1) allowed by the strategy, and (2) the emitted code is an actual for-loop (and not a co-iterating while-loop).
Enumerator
kNone
kDenseInnerLoop
kAnyStorageInnerLoop
Definition at line 1092 of file Transforms.h.
Function Documentation
applyMapToValues()
SmallVector< Value, 4 > mlir::linalg::applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ValueRange values)
Returns the values obtained by applying map to the list of values.
Definition at line 169 of file LinalgInterfaces.cpp.
References mlir::OpBuilder::create(), createFoldedComposedAffineApply(), mlir::OpBuilder::createOrFold(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::ShapedType::getRank(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), mlir::ShapedType::getShape(), and mlir::ShapedType::hasStaticShape().
Referenced by getCollapsedOutputDimFromInputShape(), getExpandedOutputDimFromInputShape(), verify(), and HasAffineDimExprVisitor::visitSymbolExpr().
applyPermutationToVector()
template<typename T , unsigned N> void mlir::linalg::applyPermutationToVector (SmallVector< T, N > & inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
Element i in inVec is mapped to location j = permutation[i]. E.g.: for an input vector `inVec = ['a', 'b', 'c']and a permutation vector permutation = [2, 0, 1], this function leavesinVec = ['c', 'a', 'b']`.
Definition at line 42 of file Utils.h.
References getSmallestBoundingIndex(), isFusableInto(), isParallelIteratorType(), isProducerLastWriteOfView(), isReductionIteratorType(), isWindowIteratorType(), and makeTiledShapes().
Referenced by interchange(), and tileLinalgOpImpl().
applyStagedPatterns()
LogicalResult mlir::linalg::applyStagedPatterns (Operation * op, ArrayRef< FrozenRewritePatternSet > stage1Patterns, const FrozenRewritePatternSet & stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda = nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
the first stage consists of a list of FrozenRewritePatternSet. Each FrozenRewritePatternSet in this list is applied once, in order.
the second stage consists of a single OwningRewritePattern that is applied greedily until convergence.
the third stage consists of applying a lambda, generally used for non-local transformation effects. This allows creating custom fused transformations where patterns can be ordered and applied at a finer granularity than a sequence of traditional compiler passes.
Definition at line 479 of file Transforms.cpp.
References mlir::applyPatternsAndFoldGreedily(), DBGS, mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::linalg::ConvOpVectorization< ConvOp, N >::ConvOpVectorization(), and mlir::linalg::CodegenStrategy::transform().
concat()
SmallVector< AffineExpr, 4 > mlir::linalg::concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Definition at line 2452 of file LinalgOps.cpp.
Referenced by mlir::Simplex::makeProduct().
defaultLoopRangesBuilder()
LoopRangeBuilder mlir::linalg::defaultLoopRangesBuilder (LinalgOp op)
Provide a very simple inference procedure to build the loop ranges from the op and its operands.
This only works with permutation affine maps and patterns of the form (m, n)[s] -> (m + n - s floordiv 2). A more advanced Tensor-Comprehension like inference is possible but has proven to be ambiguous in unfavorable case. As a consequence, we relax the default behavior very conservatively and provide an op-specified hook so that Linalg ops may override the behavior.
enqueue()
template<typename PatternType , typename OpType , typename OptionsType > void mlir::linalg::enqueue (RewritePatternSet & patternList, OptionsType options, StringRef opName, linalg::LinalgTransformationFilter m)
Definition at line 58 of file CodegenStrategy.h.
References mlir::RewritePatternSet::add(), mlir::linalg::LinalgTransformationFilter::addOpFilter(), mlir::RewritePatternSet::getContext(), and options.
extractOrIdentityMap()
AffineMap mlir::linalg::extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
Definition at line 2404 of file LinalgOps.cpp.
References mlir::AffineMap::get(), and mlir::AffineMap::getMultiDimIdentityMap().
findAllFusableDependences()
FusableOpDependencesTy mlir::linalg::findAllFusableDependences (ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph)
Find all dependences that are fusable.
Definition at line 721 of file Fusion.cpp.
References findFusableProducer().
Referenced by tileAndFuseLinalgOpsImpl().
fuseProducerOfBuffer()
Optional< FusionInfo > mlir::linalg::fuseProducerOfBuffer (OpBuilder & b, OpOperand & consumerOpOperand, const LinalgDependenceGraph & graph)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Implements the fusion part of the "tileAndFuse on buffers" transformation and thus requires the consumerOpOperand to be a subview op (generally obtained by applying the tiling transformation).
Definition at line 391 of file Fusion.cpp.
References findFusableProducer(), fuse(), mlir::OpOperand::get(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), mlir::Value::getParentBlock(), and mlir::OpBuilder::setInsertionPoint().
fuseProducerOfTensor() [1/2]
Optional< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, OpOperand & consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a subtensor op (generally obtained by applying the tiling transformation).
Definition at line 462 of file Fusion.cpp.
References mlir::OpOperand::get(), and getProducerOfTensor().
fuseProducerOfTensor() [2/2]
Optional< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, OpResult producerOpResult, OpOperand & consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a subtensor op (generally obtained by applying the tiling transformation). Assumes producerOfTensor is a Linalg op that produces consumerOpOperand.
Definition at line 474 of file Fusion.cpp.
References mlir::OpBuilder::create(), fuse(), mlir::OpOperand::get(), mlir::Value::getDefiningOp(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), mlir::OpResult::getOwner(), mlir::Value::getParentBlock(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::OpOperand::set(), and mlir::OpBuilder::setInsertionPoint().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(A, f) : memref<f32>, f32 name mangles into linalg_fill_viewf32_f32_impl
linalg.dot A, B, C : (memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32>) name mangles into linalg_dot_viewxf32_viewxf32_viewf32_impl
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32_impl
Definition at line 2481 of file LinalgOps.cpp.
References appendMangledType(), foldMemRefCast(), foldReshapeOp(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), mlir::OperationName::getStringRef(), and mlir::succeeded().
generateParallelLoopNest()
static void mlir::linalg::generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > & ivStorage, ArrayRef< DistributionMethod > distributionMethod = {}) static
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
` Consecutive parallel loops create a single scf.parallel operation; each sequential loop creates a new scf.for operation. The body of the innermost loop is populated by bodyBuilderFn that accepts a range of induction variables for all loops. ivStorage is used to store the partial list of induction variables.
Definition at line 315 of file Utils.cpp.
References mlir::edsc::conditionBuilder(), isParallelIteratorType(), mlir::edsc::loopNestBuilder(), and mlir::edsc::op::slt().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
getDimsOfType()
void mlir::linalg::getDimsOfType (Operation * op, StringRef iteratorTypeName, SmallVectorImpl< AffineExpr > & res)
Return the dims that are iteratorTypeName loops in the LinalgOp op.
Assumes op is a LinalgOp.
Definition at line 2389 of file LinalgOps.cpp.
References mlir::getAffineDimExpr(), and mlir::Operation::getContext().
Referenced by replaceBlockArgForUnitDimLoops< IndexedGenericOp >().
getLinalgTilingCanonicalizationPatterns()
RewritePatternSet mlir::linalg::getLinalgTilingCanonicalizationPatterns (MLIRContext * ctx)
Canonicalization patterns relevant to apply after tiling patterns.
These are applied automatically by the tiling pass but need to be applied manually when tiling is called programmatically.
Definition at line 495 of file Tiling.cpp.
References populateLinalgTilingCanonicalizationPatterns().
Referenced by applyTilingToLoopPatterns(), mlir::linalg::LinalgTilingOptions::setPaddingValueComputationFunction(), and mlir::linalg::CodegenStrategy::transform().
getSmallestBoundingIndex()
IntegerAttr mlir::linalg::getSmallestBoundingIndex (Value size)
If size comes from an AffineMinOp and one of the values of AffineMinOp is a constant then return a new value set to the smallest such constant.
If size comes from a ConstantOp, return the constant. Otherwise return nullptr.
Otherwise returngetSmallestBoundingIndex nullptr.
Definition at line 165 of file Utils.cpp.
References mlir::Value::getContext(), mlir::Value::getDefiningOp(), and min().
Referenced by applyPermutationToVector(), padOperandToSmallestStaticBoundingBox(), and promoteSubviewAsNewBuffer().
hoistPaddingOnTensors()
LogicalResult mlir::linalg::hoistPaddingOnTensors (PadTensorOp & padTensorOp, unsigned nLoops)
Mechanically hoist padding operations on tensors by nLoops into a new, generally larger tensor.
This achieves packing of multiple padding ops into a larger tensor. On success, padTensorOp is replaced by the cloned version in the packing loop so the caller can continue reasoning about the padding operation.
Example in pseudo-mlir:
If hoistPaddingOnTensors is called with nLoops = 2 on the following IR.
scf.for (%i, %j, %k)
  %st0 = subtensor f(%i, %k) : ... to tensor<?x?xf32>
  %0 = linalg.pad_tensor %st0 low[0, 0] high[...] {
  ^bb0( ... ):
    linalg.yield %pad
  } : tensor<?x?xf32> to tensor<4x8xf32>
  compute(%0)
IR resembling the following is produced:
scf.for (%i) {
  %packed_init = linalg.init_tensor range(%j) : tensor<?x4x8xf32>
  %packed = scf.for (%k) iter_args(%p : %packed_init) {
    %st0 = subtensor f(%i, %k) : ... to tensor<?x?xf32>
    %0 = linalg.pad_tensor %st0 low[0, 0] high[...] {
    ^bb0( ... ):
      linalg.yield %pad
    } : tensor<?x?xf32> to tensor<4x8xf32>
    %1 = subtensor_insert %0 ... : tensor<4x8xf32> to tensor<?x4x8xf32>
    scf.yield %1: tensor<?x4x8xf32>
  } -> tensor<?x4x8xf32>
  scf.for (%j, %k) {
    %st0 = subtensor %packed [%k, 0, 0][1, 4, 8][1, 1, 1] :
             tensor<?x4x8xf32> to tensor<4x8xf32>
    compute(%st0)
  }
}
Definition at line 752 of file Hoisting.cpp.
References buildLoopIterationCount(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::scf::getForInductionVarOwner(), mlir::Builder::getIndexAttr(), hoistPaddingOnTensorsPrerequisites(), mlir::ShapedType::isDynamic(), mlir::ShapedType::kDynamicSize, mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
hoistRedundantVectorTransfers()
void mlir::linalg::hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write on buffers pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
The two ops access the same memref with the same indices.
All operands are invariant under the enclosing scf::ForOp.
No uses of the memref either dominate the transfer_read or are dominated by the transfer_write (i.e. no aliasing between the write and the read across the loop) To improve hoisting opportunities, call the moveLoopInvariantCode helper function on the candidate loop above which to hoist. Hoisting the transfers results in scf::ForOp yielding the value that originally transited through memory.
Definition at line 390 of file Hoisting.cpp.
References mlir::WalkResult::advance(), mlir::cloneWithNewYields(), DBGS, mlir::failed(), mlir::getForwardSlice(), mlir::WalkResult::interrupt(), mlir::moveLoopInvariantCode(), and mlir::DominanceInfo::properlyDominates().
Referenced by mlir::linalg::CodegenStrategy::transform().
hoistRedundantVectorTransfersOnTensor()
void mlir::linalg::hoistRedundantVectorTransfersOnTensor (FuncOp func)
Same behavior as hoistRedundantVectorTransfers but works on tensors instead of buffers.
Definition at line 338 of file Hoisting.cpp.
References mlir::WalkResult::advance(), mlir::applyPatternsAndFoldGreedily(), DBGS, mlir::detail::enumerate(), findMatchingTransferRead(), getLoopInvariantTransferWriteOpDefining(), mlir::Operation::getOpOperand(), hoistReadWrite(), mlir::WalkResult::interrupt(), and tensorChunkAccessedByUnknownOp().
Referenced by mlir::linalg::CodegenStrategy::transform().
insertVectorizationPatternImpl() [1/2]
template<typename OpType , typename = std::enable_if_t<detect_has_get_operation_name<OpType>::value>, typename = void> void mlir::linalg::insertVectorizationPatternImpl (RewritePatternSet & patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ op with a getOperationName method.
Definition at line 753 of file Transforms.h.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
insertVectorizationPatternImpl() [2/2]
template<typename OpType , typename = std::enable_if_t< !detect_has_get_operation_name<OpType>::value>> void mlir::linalg::insertVectorizationPatternImpl (RewritePatternSet & patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ class without a getOperationName method (e.g.
an OpInterface).
Definition at line 764 of file Transforms.h.
References mlir::RewritePatternSet::add(), mlir::linalg::LinalgTransformationFilter::addOpFilter(), and mlir::RewritePatternSet::getContext().
insertVectorizationPatterns()
template<typename... OpTypes> void mlir::linalg::insertVectorizationPatterns (RewritePatternSet & patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f = linalg::LinalgTransformationFilter())
Variadic helper function to insert vectorization patterns for C++ ops.
Definition at line 773 of file Transforms.h.
References options.
interchange()
void mlir::linalg::interchange (PatternRewriter & rewriter, LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions and adapts the index accesses of op.
This is an in-place transformation controlled by interchangeVector. An empty vector is interpreted as the identity permutation and the transformation returns early.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed with interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..op.rank without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 52 of file Interchange.cpp.
References applyPermutationToVector(), mlir::AffineMap::compose(), mlir::OpBuilder::create(), mlir::Block::front(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getSubMap(), mlir::inversePermutation(), mlir::AffineMap::isEmpty(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
interchangeGenericLinalgOpPrecondition()
LogicalResult mlir::linalg::interchangeGenericLinalgOpPrecondition (Operation * op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
Definition at line 35 of file Interchange.cpp.
References mlir::failure(), mlir::Operation::getContext(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
isaContractionOpInterface()
bool mlir::linalg::isaContractionOpInterface (LinalgOp linalgOp)
Checks whether linalgOp conforms to ContractionOpInterface.
Definition at line 118 of file LinalgInterfaces.cpp.
References isContractionInterfaceImpl(), and Success.
Referenced by vectorizeContraction(), vectorizeLinalgOp(), and vectorizeLinalgOpPrecondition().
isFusableInto()
bool mlir::linalg::isFusableInto (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
This checks producer is the last write of consumedView and that no interleaved dependence would be violated (RAW, WAR or WAW).
Definition at line 299 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringDependences(), and isProducerLastWriteOfView().
Referenced by applyPermutationToVector(), and findFusableProducer().
isParallelIteratorType()
bool mlir::linalg::isParallelIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 120 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getParallelIteratorTypeName().
Referenced by applyPermutationToVector(), mlir::linalg::GenerateLoopNest< LoopTy >::doit(), and generateParallelLoopNest().
isProducerLastWriteOfView()
bool mlir::linalg::isProducerLastWriteOfView (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
This checks structural dominance, that the dependence is a RAW without any interleaved write to any piece of consumedView.
Definition at line 275 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringWrites(), and isStructurallyFusableProducer().
Referenced by applyPermutationToVector(), and isFusableInto().
isReductionIteratorType()
bool mlir::linalg::isReductionIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 127 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getReductionIteratorTypeName().
Referenced by applyPermutationToVector(), genFor(), reduceIfNeeded(), and reductionPreconditions().
isWindowIteratorType()
bool mlir::linalg::isWindowIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 134 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getWindowIteratorTypeName().
Referenced by applyPermutationToVector().
linalgLowerOpToLoops()
template<typename LoopTy > template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< AffineForOp > (OpBuilder & builder, Operation * op)
Emits a loop nest of LoopTy with the proper body for op.
Emits a loop nest with the proper body for op.
Definition at line 654 of file Loops.cpp.
linalgOpToAffineLoops()
LogicalResult mlir::linalg::linalgOpToAffineLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of affine.for with the proper body for op.
Definition at line 670 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
linalgOpToLoops()
LogicalResult mlir::linalg::linalgOpToLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of scf.for with the proper body for op.
Definition at line 677 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
linalgOpToParallelLoops()
LogicalResult mlir::linalg::linalgOpToParallelLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of scf.parallel with the proper body for op.
Definition at line 683 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
makeAffineDimExprs()
SmallVector< AffineExpr, 4 > mlir::linalg::makeAffineDimExprs (unsigned num, unsigned & startIdx, MLIRContext * context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
Definition at line 2415 of file LinalgOps.cpp.
References mlir::getAffineDimExpr().
makeTiledShapes()
SmallVector< Value, 4 > mlir::linalg::makeTiledShapes (OpBuilder & builder, Location loc, LinalgOp linalgOp, ArrayRef< Value > tiledOperands, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Creates subtensor/subview ops for all tiledOperands of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
sizeBounds are the iteration space bounds for all the implicit loops in linalgOp.
Note that a constant zero in tileSizes means no tiling at that implicit loop. The number of non-zero values in tileSizes should be equal to the number of values in ivs.
Definition at line 488 of file Utils.cpp.
References applyMapToValues(), mlir::bindDims(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::Builder::getContext(), mlir::ShapedType::getDimSize(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::ShapedType::getRank(), mlir::AffineMap::getSubMap(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), isTiled(), and isZero().
Referenced by applyPermutationToVector(), fuse(), and tileLinalgOpImpl().
populateConvVectorizationPatterns()
void mlir::linalg::populateConvVectorizationPatterns (MLIRContext * context, SmallVectorImpl< RewritePatternSet > & patterns, ArrayRef< int64_t > tileSizes)
Populates patterns for vectorization of all ConvN-D ops.
Definition at line 819 of file Vectorization.cpp.
populateElementwiseOpsFusionPatterns()
void mlir::linalg::populateElementwiseOpsFusionPatterns (RewritePatternSet & patterns, LinalgElementwiseFusionOptions options = LinalgElementwiseFusionOptions())
Patterns for fusing linalg operation on tensors.
Definition at line 1478 of file FusionOnTensors.cpp.
References mlir::RewritePatternSet::add(), mlir::linalg::LinalgElementwiseFusionOptions::allowFoldingUnitDimReshapes, mlir::linalg::LinalgElementwiseFusionOptions::controlElementwiseOpsFusionFn, mlir::RewritePatternSet::getContext(), and populateFoldReshapeOpsByExpansionPatterns().
Referenced by fuseElementwiseOps(), and mlir::linalg::LinalgElementwiseFusionOptions::setControlElementwiseOpsFusionFn().
populateElementwiseToLinalgConversionPatterns()
void mlir::linalg::populateElementwiseToLinalgConversionPatterns (RewritePatternSet & patterns)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
Definition at line 119 of file ElementwiseToLinalg.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPartialConversion(), mlir::failed(), mlir::RewritePatternSet::getContext(), isElementwiseMappableOpOnRankedTensors(), and mlir::ConversionTarget::markUnknownOpDynamicallyLegal().
populateFoldReshapeOpsByExpansionPatterns()
void mlir::linalg::populateFoldReshapeOpsByExpansionPatterns (RewritePatternSet & patterns, bool allowFoldingUnitDimReshapes = false)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
Definition at line 1470 of file FusionOnTensors.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by populateElementwiseOpsFusionPatterns().
populateFoldReshapeOpsByLinearizationPatterns()
void mlir::linalg::populateFoldReshapeOpsByLinearizationPatterns (RewritePatternSet & patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic/indexed_generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic/indexed_generic operation.
Definition at line 1454 of file FusionOnTensors.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by fuseElementwiseOps().
populateFoldUnitDimsReshapeOpsByLinearizationPatterns()
void mlir::linalg::populateFoldUnitDimsReshapeOpsByLinearizationPatterns (RewritePatternSet & patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic/indexed_generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic/indexed_generic operation.
The patterns are applied only when the tensor reshape involved is collapsing (introducing) unit-extent dimensions.
Definition at line 1462 of file FusionOnTensors.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateFoldUnitExtentDimsPatterns()
void mlir::linalg::populateFoldUnitExtentDimsPatterns (RewritePatternSet & patterns)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors.
Patterns that are used to canonicalize the use of unit-extent dims for broadcasting.
Definition at line 622 of file DropUnitDims.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsAndFoldGreedily(), and mlir::RewritePatternSet::getContext().
populateLinalgBufferizePatterns()
void mlir::linalg::populateLinalgBufferizePatterns (BufferizeTypeConverter & converter, RewritePatternSet & patterns)
Populates the given list with patterns to bufferize linalg ops.
Definition at line 331 of file Bufferize.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by finalizeBufferAllocation().
populateLinalgConvGeneralizationPatterns()
void mlir::linalg::populateLinalgConvGeneralizationPatterns (RewritePatternSet & patterns, LinalgTransformationFilter filter = LinalgTransformationFilter())
Populates patterns with patterns to convert linalg.conv ops to linalg.generic ops.
Definition at line 180 of file Generalization.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by createGenericOpFromNamedOp(), and mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateLinalgNamedOpsGeneralizationPatterns()
void mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns (RewritePatternSet & patterns, LinalgTransformationFilter filter = LinalgTransformationFilter())
Linalg generalization patterns.
Populates patterns with patterns to convert spec-generated named ops to linalg.generic ops.
Definition at line 185 of file Generalization.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by createGenericOpFromNamedOp(), and mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateLinalgTilingCanonicalizationPatterns()
void mlir::linalg::populateLinalgTilingCanonicalizationPatterns (RewritePatternSet & patterns)
Definition at line 501 of file Tiling.cpp.
References mlir::RewritePatternSet::getContext().
Referenced by getLinalgTilingCanonicalizationPatterns(), and mlir::linalg::LinalgTilingOptions::setPaddingValueComputationFunction().
populateLinalgToStandardConversionPatterns()
void mlir::linalg::populateLinalgToStandardConversionPatterns (RewritePatternSet & patterns)
Populate the given list with patterns that convert from Linalg to Standard.
Definition at line 196 of file LinalgToStandard.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addLegalDialect(), mlir::ConversionTarget::addLegalOp(), mlir::applyFullConversion(), mlir::failed(), and mlir::RewritePatternSet::getContext().
populatePushReshapeOpsPatterns()
void mlir::linalg::populatePushReshapeOpsPatterns (RewritePatternSet & patterns)
Patterns to push reshape op towards the end of the graph in order to expose more fusion opportunities.
Definition at line 1493 of file FusionOnTensors.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by mlir::linalg::LinalgElementwiseFusionOptions::setControlElementwiseOpsFusionFn().
populateSparsificationPatterns()
void mlir::linalg::populateSparsificationPatterns (RewritePatternSet & patterns, const SparsificationOptions & options = SparsificationOptions())
Sets up sparsification rewriting rules with the given options.
Populates the given patterns list with rewriting rules required for the sparsification of linear algebra operations.
Definition at line 1408 of file Sparsification.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
promoteSubviewAsNewBuffer()
Optional< PromotionInfo > mlir::linalg::promoteSubviewAsNewBuffer (OpBuilder & b, Location loc, memref::SubViewOp subView, AllocBufferCallbackFn allocationFn, DataLayout & layout, OperationFolder * folder = nullptr)
Definition at line 216 of file Promotion.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Builder::getIndexAttr(), and getSmallestBoundingIndex().
Referenced by promoteSubViews().
promoteSubViews()
Optional< LinalgOp > mlir::linalg::promoteSubViews (OpBuilder & b, LinalgOp op, LinalgPromotionOptions options, OperationFolder * folder = nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
Promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer.
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns the modified linalg op (the modification happens in place) as well as all the copy ops created.
Definition at line 389 of file Promotion.cpp.
References mlir::DataLayout::closest(), mlir::failed(), promoteSubViews(), promoteSubviewsPrecondition(), mlir::linalg::LinalgPromotionOptions::setDynamicBuffers(), and mlir::linalg::LinalgPromotionOptions::setUseAlloca().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite().
promoteSubviewsPrecondition()
LogicalResult mlir::linalg::promoteSubviewsPrecondition (Operation * op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
Definition at line 369 of file Promotion.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::linalg::LinalgPromotionOptions::operandsToPromote, and mlir::success().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and promoteSubViews().
sfinae_enqueue() [1/2]
template<template< typename > class PatternType, typename ConcreteOpType , typename OptionsType , typename = std::enable_if_t<std::is_member_function_pointer< decltype(&ConcreteOpType::getOperationName)>::value>> void mlir::linalg::sfinae_enqueue (RewritePatternSet & patternList, OptionsType options, StringRef opName, linalg::LinalgTransformationFilter m)
SFINAE: Enqueue helper for ConcreteOpType that have a getOperationName.
Definition at line 38 of file CodegenStrategy.h.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
sfinae_enqueue() [2/2]
template<template< typename > class PatternType, typename OpType , typename OptionsType > void mlir::linalg::sfinae_enqueue (RewritePatternSet & patternList, OptionsType options, StringRef opName, linalg::LinalgTransformationFilter m)
SFINAE: Enqueue helper for OpType that do not have a getOperationName (e.g.
LinalgOp, other interfaces, Operation*).
Definition at line 50 of file CodegenStrategy.h.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
substituteMin()
AffineMapAndOperands mlir::linalg::substituteMin (AffineMinOp affineMinOp, GetMinMaxExprFn getMinMaxExpr)
Traverse the dims of the AffineMap of affineMinOp and substitute dimensions with known range by new expressions involving the min or max expression:
If the AffineDimExpr mapped to a known value has a positive sign, it is replaced by the min expression.
If the AffineDimExpr mapped to a known value has a negative sign, it is replaced by the max expression. All known values are iteratively replaced. This is used as an intermediate step in computing bounding boxes and canonicalize AffineMinOps. All dim and symbol operands are assumed to have positive values (positive orthant assumptions). Return a new AffineMap, dims and symbols that have been canonicalized and simplified.
Definition at line 585 of file Transforms.cpp.
References substitute().
Referenced by computeLoopIndependentUpperBound(), and mlir::linalg::AffineMinRangeCanonicalizationPattern::matchAndRewrite().
tileAndFuseLinalgOps()
Optional< TiledAndFusedLinalgOps > mlir::linalg::tileAndFuseLinalgOps (OpBuilder & builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph, const LinalgTilingOptions & tilingOptions)
Definition at line 938 of file Fusion.cpp.
References mlir::linalg::LinalgTilingOptions::loopType.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
tileLinalgOp()
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, const LinalgTilingOptions & options)
Definition at line 434 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), mlir::Identifier::get(), mlir::RewritePatternSet::getContext(), mlir::linalg::LinalgTilingOptions::loopType, and options.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase(), and tileRootOperation().
updateBoundsForCyclicDistribution()
void mlir::linalg::updateBoundsForCyclicDistribution (OpBuilder & builder, Location loc, Value procId, Value nprocs, Value & lb, Value & ub, Value & step)
Update the lb, ub and step to get per processor lb, ub and step.
Definition at line 295 of file Utils.cpp.
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
vectorizeLinalgOp()
LogicalResult mlir::linalg::vectorizeLinalgOp (OpBuilder & builder, Operation * op, SmallVectorImpl< Value > & newResults)
Emit a suitable vector form for a Linalg op with fully static shape.
Definition at line 635 of file Vectorization.cpp.
References DEBUG_TYPE, mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), isaContractionOpInterface(), vectorizeAsLinalgGeneric(), vectorizeContraction(), and vectorizeLinalgOpPrecondition().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite().
vectorizeLinalgOpPrecondition()
LogicalResult mlir::linalg::vectorizeLinalgOpPrecondition (Operation * op)
Rewrite a linalg.generic into a suitable vector.contraction op.
Definition at line 612 of file Vectorization.cpp.
References allIndexingsAreProjectedPermutation(), mlir::failure(), mlir::ShapedType::hasStaticShape(), isaContractionOpInterface(), isElementwise(), reductionPreconditions(), mlir::succeeded(), and mlir::success().
Referenced by vectorizeLinalgOp().
weightedPoolingInputIndex()
template<typename PoolingOp > SmallVector< AffineExpr, 4 > mlir::linalg::weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
Returns the vector of AffineMaps representing: stride[i] * outputDims[i] + dilation[i] * windowDims[i] - pad_low[i]
Definition at line 2426 of file LinalgOps.cpp.