MLIR: runtime.np_to_memref Namespace Reference
runtime.np_to_memref Namespace Reference
Classes
class UnrankedMemRefDescriptor
Functions
def make_nd_memref_descriptor (rank, dtype)
def make_zero_d_memref_descriptor (dtype)
def get_ranked_memref_descriptor (nparray)
def get_unranked_memref_descriptor (nparray)
def unranked_memref_to_numpy (unranked_memref, np_dtype)
def ranked_memref_to_numpy (ranked_memref)
Function Documentation
get_ranked_memref_descriptor()
def runtime.np_to_memref.get_ranked_memref_descriptor (nparray)
Return a ranked memref descriptor for the given numpy array.
Definition at line 49 of file np_to_memref.py.
References runtime.np_to_memref.make_nd_memref_descriptor(), and runtime.np_to_memref.make_zero_d_memref_descriptor().
Referenced by runtime.np_to_memref.get_unranked_memref_descriptor().
get_unranked_memref_descriptor()
def runtime.np_to_memref.get_unranked_memref_descriptor (nparray)
Return a generic/unranked memref descriptor for the given numpy array.
Definition at line 79 of file np_to_memref.py.
References runtime.np_to_memref.get_ranked_memref_descriptor().
make_nd_memref_descriptor()
def runtime.np_to_memref.make_nd_memref_descriptor (rank, dtype)
Definition at line 11 of file np_to_memref.py.
Referenced by runtime.np_to_memref.get_ranked_memref_descriptor(), and runtime.np_to_memref.unranked_memref_to_numpy().
make_zero_d_memref_descriptor()
def runtime.np_to_memref.make_zero_d_memref_descriptor (dtype)
Definition at line 28 of file np_to_memref.py.
Referenced by runtime.np_to_memref.get_ranked_memref_descriptor().
ranked_memref_to_numpy()
def runtime.np_to_memref.ranked_memref_to_numpy (ranked_memref)
Converts ranked memrefs to numpy arrays.
Definition at line 107 of file np_to_memref.py.
unranked_memref_to_numpy()
def runtime.np_to_memref.unranked_memref_to_numpy (unranked_memref, np_dtype)
Converts unranked memrefs to numpy arrays.
Definition at line 90 of file np_to_memref.py.
References runtime.np_to_memref.make_nd_memref_descriptor().