MLIR: _ods_common Namespace Reference
_ods_common Namespace Reference
Functions
def extend_opview_class (ext_module)
def segmented_accessor (elements, raw_segments, idx)
def equally_sized_accessor (elements, n_variadic, n_preceding_simple, n_preceding_variadic)
def get_default_loc_context (location=None)
Function Documentation
equally_sized_accessor()
def _ods_common.equally_sized_accessor (elements, n_variadic, n_preceding_simple, n_preceding_variadic)
Returns a starting position and a number of elements per variadic group
assuming equally-sized groups and the given numbers of preceding groups.
  elements: a sequential container.
  n_variadic: the number of variadic groups in the container.
  n_preceding_simple: the number of non-variadic groups preceding the current
      group.
  n_preceding_variadic: the number of variadic groups preceding the current
      group.
Definition at line 88 of file _ods_common.py.
Referenced by segmented_accessor().
extend_opview_class()
def _ods_common.extend_opview_class (ext_module)
Decorator to extend an OpView class from an extension module.
Extension modules can expose various entry-points:
  Stand-alone class with the same name as a parent OpView class (i.e.
  "ReturnOp"). A name-based match is attempted first before falling back
  to a below mechanism.
  def select_opview_mixin(parent_opview_cls):
    If defined, allows an appropriate mixin class to be selected dynamically
    based on the parent OpView class. Should return NotImplemented if a
    decision is not made.
Args:
  ext_module: A module from which to locate extensions. Can be None if not
    available.
Returns:
  A decorator that takes an OpView subclass and further extends it as
  needed.
Definition at line 16 of file _ods_common.py.
get_default_loc_context()
def _ods_common.get_default_loc_context (location = None)
Returns a context in which the defaulted location is created. If the location
is None, takes the current location from the stack, raises ValueError if there
is no location on the stack.
Definition at line 110 of file _ods_common.py.
Referenced by _linalg_ops_ext.InitTensorOp.__init__().
segmented_accessor()
def _ods_common.segmented_accessor (elements, raw_segments, idx)
Returns a slice of elements corresponding to the idx-th segment.
  elements: a sliceable container (operands or results).
  raw_segments: an mlir.ir.Attribute, of DenseIntElements subclass containing
      sizes of the segments.
  idx: index of the segment.
Definition at line 72 of file _ods_common.py.
References equally_sized_accessor().