MLIR: mlir::impl Namespace Reference
mlir::impl Namespace Reference
Classes
class DataLayoutEntryStorage
class DataLayoutSpecStorage
class VariadicFlag
A named class for passing around the variadic flag.
Typedefs
using FuncTypeBuilder = function_ref< Type(Builder &, ArrayRef< Type >, ArrayRef< Type >, VariadicFlag, std::string &)>
Callback type for parseFunctionLikeOp, the callback should produce the type that will be associated with a function-like operation from lists of function arguments and results, VariadicFlag indicates whether the function should have variadic arguments; in case of error, it may populate the last argument with a message.
Functions
LogicalResult verifyHasDefaultDLTIDataLayoutTrait (Operation *op)
DataLayoutSpecInterface getDataLayoutSpec (Operation *op)
void addArgAndResultAttrs (Builder &builder, OperationState &result, ArrayRef< NamedAttrList > argAttrs, ArrayRef< NamedAttrList > resultAttrs)
Adds argument and result attributes, provided as argAttrs and resultAttrs arguments, to the list of operation attributes in result.
ParseResult parseFunctionArgumentList (OpAsmParser &parser, bool allowAttributes, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< NamedAttrList > &argAttrs, bool &isVariadic)
Parses function arguments using parser.
ParseResult parseFunctionSignature (OpAsmParser &parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< NamedAttrList > &argAttrs, bool &isVariadic, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs)
Parses a function signature using parser.
ParseResult parseFunctionLikeOp (OpAsmParser &parser, OperationState &result, bool allowVariadic, FuncTypeBuilder funcTypeBuilder)
Parser implementation for function-like operations.
void printFunctionLikeOp (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Printer implementation for function-like operations.
void printFunctionSignature (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Prints the signature of the function-like operation op.
void printFunctionAttributes (OpAsmPrinter &p, Operation *op, unsigned numInputs, unsigned numResults, ArrayRef< StringRef > elided={})
Prints the list of function prefixed with the "attributes" keyword.
StringRef getTypeAttrName ()
Return the name of the attribute used for function types.
StringRef getArgAttrName (unsigned arg, SmallVectorImpl< char > &out)
Return the name of the attribute used for function arguments.
bool isArgAttrName (StringRef name)
Returns true if the given name is a valid argument attribute name.
StringRef getResultAttrName (unsigned arg, SmallVectorImpl< char > &out)
Return the name of the attribute used for function results.
DictionaryAttr getArgAttrDict (Operation *op, unsigned index)
Returns the dictionary attribute corresponding to the argument at 'index'.
DictionaryAttr getResultAttrDict (Operation *op, unsigned index)
Returns the dictionary attribute corresponding to the result at 'index'.
ArrayRef< NamedAttribute > getArgAttrs (Operation *op, unsigned index)
Return all of the attributes for the argument at 'index'.
ArrayRef< NamedAttribute > getResultAttrs (Operation *op, unsigned index)
Return all of the attributes for the result at 'index'.
void eraseFunctionArguments (Operation *op, ArrayRef< unsigned > argIndices, unsigned originalNumArgs, Type newType)
Erase the specified arguments and update the function type attribute.
void eraseFunctionResults (Operation *op, ArrayRef< unsigned > resultIndices, unsigned originalNumResults, Type newType)
Erase the specified results and update the function type attribute.
FunctionType getFunctionType (Operation *op)
Get and set a FunctionLike operation's type signature.
void setFunctionType (Operation *op, FunctionType newType)
Region & getFunctionBody (Operation *op)
Get a FunctionLike operation's body.
void ensureRegionTerminator (Region &region, OpBuilder &builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Insert an operation, generated by buildTerminatorOp, at the end of the region's only block if it does not have a terminator already.
void ensureRegionTerminator (Region &region, Builder &builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Create a simple OpBuilder and forward to the OpBuilder version of this function.
ParseResult parseOneResultOneOperandTypeOp (OpAsmParser &parser, OperationState &result)
void buildBinaryOp (OpBuilder &builder, OperationState &result, Value lhs, Value rhs)
ParseResult parseOneResultSameOperandTypeOp (OpAsmParser &parser, OperationState &result)
void printOneResultOp (Operation *op, OpAsmPrinter &p)
LogicalResult foldCastInterfaceOp (Operation *op, ArrayRef< Attribute > attrOperands, SmallVectorImpl< OpFoldResult > &foldResults)
Attempt to fold the given cast operation.
LogicalResult verifyCastInterfaceOp (Operation *op, function_ref< bool(TypeRange, TypeRange)> areCastCompatible)
Attempt to verify the given cast operation.
void buildCastOp (OpBuilder &builder, OperationState &result, Value source, Type destType)
ParseResult parseCastOp (OpAsmParser &parser, OperationState &result)
void printCastOp (Operation *op, OpAsmPrinter &p)
Value foldCastOp (Operation *op)
LogicalResult verifyCastOp (Operation *op, function_ref< bool(Type, Type)> areCastCompatible)
ParseResult parseOptionalVisibilityKeyword (OpAsmParser &parser, NamedAttrList &attrs)
Parse an optional visibility attribute keyword (i.e., public, private, or nested) without quotes in a string attribute named 'attrName'.
Typedef Documentation
FuncTypeBuilder
using mlir::impl::FuncTypeBuilder = typedef function_ref<Type(Builder &, ArrayRef<Type>, ArrayRef<Type>, VariadicFlag, std::string &)>
Callback type for parseFunctionLikeOp, the callback should produce the type that will be associated with a function-like operation from lists of function arguments and results, VariadicFlag indicates whether the function should have variadic arguments; in case of error, it may populate the last argument with a message.
Definition at line 50 of file FunctionImplementation.h.
Function Documentation
addArgAndResultAttrs()
void mlir::impl::addArgAndResultAttrs (Builder & builder, OperationState & result, ArrayRef< NamedAttrList > argAttrs, ArrayRef< NamedAttrList > resultAttrs)
Adds argument and result attributes, provided as argAttrs and resultAttrs arguments, to the list of operation attributes in result.
Internally, argument and result attributes are stored as dict attributes with special names given by getResultAttrName, getArgumentAttrName.
Definition at line 143 of file FunctionImplementation.cpp.
References mlir::OperationState::addAttribute(), getArgAttrName(), mlir::Builder::getDictionaryAttr(), and getResultAttrName().
Referenced by mlir::impl::VariadicFlag::isVariadic(), parseFuncOp(), parseFunctionLikeOp(), parseGPUFuncOp(), and parseLLVMFuncOp().
buildBinaryOp()
void mlir::impl::buildBinaryOp (OpBuilder & builder, OperationState & result, Value lhs, Value rhs)
Definition at line 1119 of file Operation.cpp.
References mlir::OperationState::addOperands(), mlir::Value::getType(), and mlir::OperationState::types.
buildCastOp()
void mlir::impl::buildCastOp (OpBuilder & builder, OperationState & result, Value source, Type destType)
Definition at line 1202 of file Operation.cpp.
References mlir::OperationState::addOperands(), and mlir::OperationState::addTypes().
ensureRegionTerminator() [1/2]
void mlir::impl::ensureRegionTerminator (Region & region, OpBuilder & builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Insert an operation, generated by buildTerminatorOp, at the end of the region's only block if it does not have a terminator already.
If the region is empty, insert a new block first. buildTerminatorOp should return the terminator operation to insert.
Definition at line 1254 of file Operation.cpp.
References mlir::Region::back(), mlir::Block::back(), mlir::OpBuilder::createBlock(), mlir::Region::empty(), mlir::Block::empty(), mlir::Operation::hasTrait(), mlir::OpBuilder::insert(), and mlir::OpBuilder::setInsertionPointToEnd().
Referenced by ensureRegionTerminator().
ensureRegionTerminator() [2/2]
void mlir::impl::ensureRegionTerminator (Region & region, Builder & builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Create a simple OpBuilder and forward to the OpBuilder version of this function.
Definition at line 1271 of file Operation.cpp.
References ensureRegionTerminator(), and mlir::Builder::getContext().
Referenced by mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ensureTerminator(), and mlir::OptionalParseResult::operator*().
eraseFunctionArguments()
void mlir::impl::eraseFunctionArguments (Operation * op, ArrayRef< unsigned > argIndices, unsigned originalNumArgs, Type newType)
Erase the specified arguments and update the function type attribute.
Definition at line 34 of file FunctionSupport.cpp.
References mlir::Block::eraseArguments(), mlir::Region::front(), getArgAttrDict(), getArgAttrName(), mlir::Operation::getRegion(), getTypeAttrName(), iterateIndicesExcept(), mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::eraseArguments(), and getResultAttrs().
eraseFunctionResults()
void mlir::impl::eraseFunctionResults (Operation * op, ArrayRef< unsigned > resultIndices, unsigned originalNumResults, Type newType)
Erase the specified results and update the function type attribute.
Definition at line 71 of file FunctionSupport.cpp.
References getResultAttrDict(), getResultAttrName(), getTypeAttrName(), iterateIndicesExcept(), mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::eraseResults(), and getResultAttrs().
foldCastInterfaceOp()
LogicalResult mlir::impl::foldCastInterfaceOp (Operation * op, ArrayRef< Attribute > attrOperands, SmallVectorImpl< OpFoldResult > & foldResults)
Attempt to fold the given cast operation.
Definition at line 1162 of file Operation.cpp.
References mlir::failure(), mlir::Operation::getOperands(), mlir::Operation::getResults(), mlir::OperandRange::getTypes(), mlir::ResultRange::getTypes(), and mlir::success().
foldCastOp()
Value mlir::impl::foldCastOp (Operation * op)
Definition at line 1226 of file Operation.cpp.
References mlir::Operation::getOperand(), mlir::Operation::getResult(), and mlir::Value::getType().
Referenced by print(), and verify().
getArgAttrDict()
DictionaryAttr mlir::impl::getArgAttrDict (Operation * op, unsigned index) inline
Returns the dictionary attribute corresponding to the argument at 'index'.
If there are no argument attributes at 'index', a null attribute is returned.
Definition at line 50 of file FunctionSupport.h.
References getArgAttrName(), and mlir::Operation::getAttrOfType().
Referenced by eraseFunctionArguments(), mlir::OpTrait::FunctionLike< ConcreteType >::getAllArgAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrDict(), getArgAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), and wrapExternalFunction().
getArgAttrName()
StringRef mlir::impl::getArgAttrName (unsigned arg, SmallVectorImpl< char > & out) inline
Return the name of the attribute used for function arguments.
Definition at line 29 of file FunctionSupport.h.
Referenced by addArgAndResultAttrs(), eraseFunctionArguments(), getArgAttrDict(), mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrName(), parseShuffleVectorOp(), printFunctionAttributes(), printGPUFuncOp(), mlir::OpTrait::FunctionLike< ConcreteType >::setAllArgAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs(), setFunctionType(), and wrapExternalFunction().
getArgAttrs()
ArrayRef<NamedAttribute> mlir::impl::getArgAttrs (Operation * op, unsigned index) inline
Return all of the attributes for the argument at 'index'.
Definition at line 64 of file FunctionSupport.h.
References getArgAttrDict().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::getArgAttrs(), printFunctionSignature(), and verify().
getDataLayoutSpec()
DataLayoutSpecInterface mlir::impl::getDataLayoutSpec (Operation * op)
Definition at line 26 of file Traits.cpp.
References mlir::Operation::getAttrOfType().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::getDataLayoutSpec(), and verify().
getFunctionBody()
Region & mlir::impl::getFunctionBody (Operation * op)
Get a FunctionLike operation's body.
Definition at line 130 of file FunctionSupport.cpp.
References mlir::Operation::getRegion(), and mlir::Operation::hasTrait().
Referenced by mlir::TypeConverter::convertBlockSignature(), mlir::OpTrait::FunctionLike< ConcreteType >::getBody(), getResultAttrs(), and sourceMaterializationCallback().
getFunctionType()
FunctionType mlir::impl::getFunctionType (Operation * op)
Get and set a FunctionLike operation's type signature.
Definition at line 107 of file FunctionSupport.cpp.
References mlir::Operation::getAttrOfType(), getTypeAttrName(), and mlir::Operation::hasTrait().
Referenced by mlir::TypeConverter::convertBlockSignature(), getResultAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::getType(), and setFunctionType().
getResultAttrDict()
DictionaryAttr mlir::impl::getResultAttrDict (Operation * op, unsigned index) inline
Returns the dictionary attribute corresponding to the result at 'index'.
If there are no result attributes at 'index', a null attribute is returned.
Definition at line 58 of file FunctionSupport.h.
References mlir::Operation::getAttrOfType(), and getResultAttrName().
Referenced by eraseFunctionResults(), mlir::OpTrait::FunctionLike< ConcreteType >::getAllResultAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrDict(), getResultAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::removeResultAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr().
getResultAttrName()
StringRef mlir::impl::getResultAttrName (unsigned arg, SmallVectorImpl< char > & out) inline
Return the name of the attribute used for function results.
Definition at line 42 of file FunctionSupport.h.
Referenced by addArgAndResultAttrs(), eraseFunctionResults(), getResultAttrDict(), mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrName(), printFunctionAttributes(), mlir::OpTrait::FunctionLike< ConcreteType >::setAllResultAttrs(), setFunctionType(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs().
getResultAttrs()
ArrayRef<NamedAttribute> mlir::impl::getResultAttrs (Operation * op, unsigned index) inline
Return all of the attributes for the result at 'index'.
Definition at line 70 of file FunctionSupport.h.
References eraseFunctionArguments(), eraseFunctionResults(), getFunctionBody(), getFunctionType(), getResultAttrDict(), and setFunctionType().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::getResultAttrs(), and printFunctionSignature().
getTypeAttrName()
StringRef mlir::impl::getTypeAttrName () inline
Return the name of the attribute used for function types.
Definition at line 26 of file FunctionSupport.h.
Referenced by eraseFunctionArguments(), eraseFunctionResults(), filterFuncAttributes(), getFunctionType(), mlir::OpTrait::FunctionLike< ConcreteType >::getTypeAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::getTypeAttrName(), lowerAsEntryFunction(), mlir::GPUFuncOpLowering::matchAndRewrite(), parseFuncOp(), parseFunctionLikeOp(), parseGPUFuncOp(), parseLLVMFuncOp(), print(), printFunctionAttributes(), printGPUFuncOp(), printLaunchFuncOperands(), printLLVMFuncOp(), setFunctionType(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), and mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait().
isArgAttrName()
bool mlir::impl::isArgAttrName (StringRef name) inline
Returns true if the given name is a valid argument attribute name.
Definition at line 35 of file FunctionSupport.h.
Referenced by filterFuncAttributes().
parseCastOp()
ParseResult mlir::impl::parseCastOp (OpAsmParser & parser, OperationState & result)
Definition at line 1208 of file Operation.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseFunctionArgumentList()
ParseResult mlir::impl::parseFunctionArgumentList (OpAsmParser & parser, bool allowAttributes, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< NamedAttrList > & argAttrs, bool & isVariadic)
Parses function arguments using parser.
The allowVariadic argument indicates whether functions with variadic arguments are supported. The trailing arguments are populated by this function with names, types and attributes of the arguments.
Definition at line 16 of file FunctionImplementation.cpp.
References mlir::OpAsmParser::emitError(), mlir::NamedAttrList::empty(), mlir::failed(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OpAsmParser::OperandType::name, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalEllipsis(), mlir::OpAsmParser::parseOptionalRegionArgument(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
Referenced by parseFunctionSignature(), and parseLaunchFuncOperands().
parseFunctionLikeOp()
ParseResult mlir::impl::parseFunctionLikeOp (OpAsmParser & parser, OperationState & result, bool allowVariadic, FuncTypeBuilder funcTypeBuilder)
Parser implementation for function-like operations.
Uses funcTypeBuilder to construct the custom function type given lists of input and output types. If allowVariadic is set, the parser will accept trailing ellipsis in the function signature and indicate to the builder whether the function is variadic. If the builder returns a null type, result will not contain the type attribute. The caller can then add a type, report the error or delegate the reporting to the op's verifier.
Uses funcTypeBuilder to construct the custom function type given lists of input and output types.
Definition at line 163 of file FunctionImplementation.cpp.
References addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::NamedAttrList::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::SymbolTable::getSymbolAttrName(), getTypeAttrName(), mlir::SymbolTable::getVisibilityAttrName(), mlir::OptionalParseResult::hasValue(), parseFunctionSignature(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalRegion(), parseOptionalVisibilityKeyword(), mlir::OpAsmParser::parseSymbolName(), and mlir::success().
Referenced by parseFuncOp().
parseFunctionSignature()
ParseResult mlir::impl::parseFunctionSignature (OpAsmParser & parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< NamedAttrList > & argAttrs, bool & isVariadic, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs)
Parses a function signature using parser.
The allowVariadic argument indicates whether functions with variadic arguments are supported. The trailing arguments are populated by this function with names, types and attributes of the arguments and those of the results.
Definition at line 128 of file FunctionImplementation.cpp.
References mlir::failure(), parseFunctionArgumentList(), parseFunctionResultList(), mlir::OpAsmParser::parseOptionalArrow(), mlir::succeeded(), and mlir::success().
Referenced by parseFuncOp(), parseFunctionLikeOp(), parseGPUFuncOp(), and parseLLVMFuncOp().
parseOneResultOneOperandTypeOp()
ParseResult mlir::impl::parseOneResultOneOperandTypeOp (OpAsmParser & parser, OperationState & result)
parseOneResultSameOperandTypeOp()
ParseResult mlir::impl::parseOneResultSameOperandTypeOp (OpAsmParser & parser, OperationState & result)
Definition at line 1126 of file Operation.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseOptionalVisibilityKeyword()
ParseResult mlir::impl::parseOptionalVisibilityKeyword (OpAsmParser & parser, NamedAttrList & attrs)
Parse an optional visibility attribute keyword (i.e., public, private, or nested) without quotes in a string attribute named 'attrName'.
Definition at line 1071 of file SymbolTable.cpp.
References mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getNamedAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getVisibilityAttrName(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::NamedAttrList::push_back(), and mlir::success().
Referenced by mlir::OpTrait::SymbolTable< ConcreteType >::lookupSymbol(), and parseFunctionLikeOp().
printCastOp()
void mlir::impl::printCastOp (Operation * op, OpAsmPrinter & p)
Definition at line 1219 of file Operation.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printFunctionAttributes()
void mlir::impl::printFunctionAttributes (OpAsmPrinter & p, Operation * op, unsigned numInputs, unsigned numResults, ArrayRef< StringRef > elided = {})
Prints the list of function prefixed with the "attributes" keyword.
The attributes with names listed in "elided" as well as those used by the function-like operation internally are not printed. Nothing is printed if all attributes are elided. Assumes op has the FunctionLike trait and passed the verification.
Definition at line 303 of file FunctionImplementation.cpp.
References getArgAttrName(), mlir::Operation::getAttr(), mlir::Operation::getAttrs(), getResultAttrName(), mlir::SymbolTable::getSymbolAttrName(), getTypeAttrName(), and mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword().
Referenced by print(), printFunctionLikeOp(), printGPUFuncOp(), and printLLVMFuncOp().
printFunctionLikeOp()
void mlir::impl::printFunctionLikeOp (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Printer implementation for function-like operations.
Accepts lists of argument and result types to use while printing.
Definition at line 333 of file FunctionImplementation.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getName(), mlir::Operation::getRegion(), mlir::SymbolTable::getSymbolAttrName(), mlir::SymbolTable::getVisibilityAttrName(), printFunctionAttributes(), printFunctionSignature(), mlir::OpAsmPrinter::printRegion(), and mlir::OpAsmPrinter::printSymbolName().
Referenced by print().
printFunctionSignature()
void mlir::impl::printFunctionSignature (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
Prints the signature of the function-like operation op.
Print the signature of the function-like operation op.
Assumes op has the FunctionLike trait and passed the verification.
Definition at line 260 of file FunctionImplementation.cpp.
References mlir::Region::empty(), getArgAttrs(), mlir::Region::getArgument(), mlir::Operation::getRegion(), getResultAttrs(), mlir::OpAsmPrinter::getStream(), printFunctionResultList(), mlir::OpAsmPrinter::printOperand(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printType().
Referenced by print(), printFunctionLikeOp(), printGPUFuncOp(), and printLLVMFuncOp().
printOneResultOp()
void mlir::impl::printOneResultOp (Operation * op, OpAsmPrinter & p)
Definition at line 1137 of file Operation.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
setFunctionType()
void mlir::impl::setFunctionType (Operation * op, FunctionType newType)
Definition at line 114 of file FunctionSupport.cpp.
References getArgAttrName(), getFunctionType(), getResultAttrName(), getTypeAttrName(), mlir::Operation::hasTrait(), mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::TypeConverter::convertBlockSignature(), getResultAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::setType().
verifyCastInterfaceOp()
LogicalResult mlir::impl::verifyCastInterfaceOp (Operation * op, function_ref< bool(TypeRange, TypeRange)> areCastCompatible)
Attempt to verify the given cast operation.
Definition at line 1179 of file Operation.cpp.
References diag(), mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), and mlir::success().
verifyCastOp()
LogicalResult mlir::impl::verifyCastOp (Operation * op, function_ref< bool(Type, Type)> areCastCompatible)
Definition at line 1234 of file Operation.cpp.
References mlir::Operation::emitError(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::success().
verifyHasDefaultDLTIDataLayoutTrait()
LogicalResult mlir::impl::verifyHasDefaultDLTIDataLayoutTrait (Operation * op)
Definition at line 15 of file Traits.cpp.
References mlir::success().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::verifyTrait().