MLIR: lib/Dialect/StandardOps/IR/Ops.cpp File Reference
Ops.cpp File Reference
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/StandardOps/IR/OpsEnums.cpp.inc"
#include "mlir/Dialect/StandardOps/IR/Ops.cpp.inc"
Classes
struct SubTensorReturnTypeCanonicalizer
Return the canonical type of the result of a subtensor.
struct SubTensorCanonicalizer
A canonicalizer wrapper to replace SubTensorOps.
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Enumerations
enum SubTensorVerificationResult { Success, RankTooLarge, SizeMismatch, ElemTypeMismatch }
Functions
static void dispatchIndexOpFoldResult (OpFoldResult ofr, SmallVectorImpl< Value > &dynamicVec, SmallVectorImpl< int64_t > &staticVec, int64_t sentinel)
Helper function to dispatch an OpFoldResult into either the dynamicVec if it is a Value or into staticVec if it is an IntegerAttr.
static void dispatchIndexOpFoldResults (ArrayRef< OpFoldResult > ofrs, SmallVectorImpl< Value > &dynamicVec, SmallVectorImpl< int64_t > &staticVec, int64_t sentinel)
static void printStandardUnaryOp (Operation *op, OpAsmPrinter &p)
A custom unary operation printer that omits the "std." prefix from the operation names.
static void printStandardBinaryOp (Operation *op, OpAsmPrinter &p)
A custom binary operation printer that omits the "std." prefix from the operation names.
static void printStandardTernaryOp (Operation *op, OpAsmPrinter &p)
A custom ternary operation printer that omits the "std." prefix from the operation names.
static void printStandardCastOp (Operation *op, OpAsmPrinter &p)
A custom cast operation printer that omits the "std." prefix from the operation names.
static bool areVectorCastSimpleCompatible (Type a, Type b, function_ref< bool(TypeRange, TypeRange)> areElementsCastCompatible)
This method checks for cast compatibility of vector types.
static SmallVector< int64_t, 4 > extractFromI64ArrayAttr (Attribute attr)
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
static LogicalResult verify (AtomicRMWOp op)
static LogicalResult verify (GenericAtomicRMWOp op)
static ParseResult parseGenericAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, GenericAtomicRMWOp op)
static LogicalResult verify (AtomicYieldOp op)
static LogicalResult collapseBranch (Block *&successor, ValueRange &successorOperands, SmallVectorImpl< Value > &argStorage)
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
static LogicalResult simplifyBrToBlockWithSinglePred (BranchOp op, PatternRewriter &rewriter)
Simplify a branch to a block that has a single predecessor.
static LogicalResult simplifyPassThroughBr (BranchOp op, PatternRewriter &rewriter)
br ^bb1 ^bb1 br ^bbN(...)
static Type getI1SameShape (Type type)
static void buildCmpIOp (OpBuilder &build, OperationState &result, CmpIPredicate predicate, Value lhs, Value rhs)
static bool applyCmpPredicateToEqualOperands (CmpIPredicate predicate)
static void buildCmpFOp (OpBuilder &build, OperationState &result, CmpFPredicate predicate, Value lhs, Value rhs)
static void print (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ConstantOp &op)
The constant op requires an attribute, and furthermore requires that it matches the return type.
static LogicalResult verify (ReturnOp op)
static void print (OpAsmPrinter &p, SelectOp op)
static ParseResult parseSelectOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (SelectOp op)
static LogicalResult verify (SignExtendIOp op)
static APInt signedCeilNonnegInputs (APInt a, APInt b, bool &overflow)
static LogicalResult verify (SplatOp op)
static SubTensorVerificationResult isRankReducedType (Type originalType, Type candidateReducedType, std::string *errMsg=nullptr)
Checks if original Type type can be rank reduced to reduced type.
template<typename OpTy >
static LogicalResult produceSubTensorErrorMsg (SubTensorVerificationResult result, OpTy op, Type expectedType, StringRef errMsg="")
static LogicalResult verify (SubTensorOp op)
Verifier for SubTensorOp.
static RankedTensorType getCanonicalSubTensorResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Infer the canonical type of the result of a subtensor operation.
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType)
static ParseResult parseSwitchOpCases (OpAsmParser &parser, Type &flagType, Block *&defaultDestination, SmallVectorImpl< OpAsmParser::OperandType > &defaultOperands, SmallVectorImpl< Type > &defaultOperandTypes, DenseIntElementsAttr &caseValues, SmallVectorImpl< Block *> &caseDestinations, SmallVectorImpl< OpAsmParser::OperandType > &caseOperands, SmallVectorImpl< Type > &caseOperandTypes, DenseIntElementsAttr &caseOperandOffsets)
<cases> ::= default : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)*
static void printSwitchOpCases (OpAsmPrinter &p, SwitchOp op, Type flagType, Block *defaultDestination, OperandRange defaultOperands, TypeRange defaultOperandTypes, DenseIntElementsAttr caseValues, SuccessorRange caseDestinations, OperandRange caseOperands, TypeRange caseOperandTypes, ElementsAttr caseOperandOffsets)
static LogicalResult verify (SwitchOp op)
static LogicalResult simplifySwitchWithOnlyDefault (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1 ] -> br ^bb1
static LogicalResult dropSwitchCasesThatMatchDefault (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb1, 43: ^bb2 ] -> switch flag : i32, [ default: ^bb1, 43: ^bb2 ]
static void foldSwitch (SwitchOp op, PatternRewriter &rewriter, APInt caseValue)
Helper for folding a switch with a constant value.
static LogicalResult simplifyConstSwitchValue (SwitchOp op, PatternRewriter &rewriter)
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, 43: ^bb3 ] -> br ^bb2
static LogicalResult simplifyPassThroughSwitch (SwitchOp op, PatternRewriter &rewriter)
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3 -> switch c_42 : i32, [ default: ^bb1, 42: ^bb3, ]
static LogicalResult simplifySwitchFromSwitchOnSameCondition (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 42: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb4
static LogicalResult simplifySwitchFromDefaultSwitchOnSameCondition (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb2 ] ^bb1: switch flag : i32, [ default: ^bb3, 42: ^bb4, 43: ^bb5 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb1: switch flag : i32, [ default: ^bb3, 43: ^bb5 ]
static LogicalResult verify (TruncateIOp op)
static LogicalResult verify (ZeroExtendIOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2788 of file Ops.cpp.
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
SubTensorVerificationResult
enum SubTensorVerificationResult
Enumerator
Success
RankTooLarge
SizeMismatch
ElemTypeMismatch
Definition at line 1835 of file Ops.cpp.
Function Documentation
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (CmpIPredicate predicate) static
Definition at line 664 of file Ops.cpp.
References mlir::applyCmpPredicate(), mlir::edsc::op::eq(), mlir::BoolAttr::get(), mlir::edsc::op::ne(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
areVectorCastSimpleCompatible()
static bool areVectorCastSimpleCompatible (Type a, Type b, function_ref< bool(TypeRange, TypeRange)> areElementsCastCompatible) static
This method checks for cast compatibility of vector types.
If 'a' and 'b' are vector types, and they are cast compatible, it calls the 'areElementsCastCompatible' function to check for element cast compatibility. Returns 'true' if the vector types are cast compatible, and 'false' otherwise.
Definition at line 245 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::m_Zero(), and mlir::matchPattern().
Referenced by mlir::ConstantIndexOp::build(), signedCeilNonnegInputs(), and verify().
buildCmpFOp()
static void buildCmpFOp (OpBuilder & build, OperationState & result, CmpFPredicate predicate, Value lhs, Value rhs) static
Definition at line 704 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
buildCmpIOp()
static void buildCmpIOp (OpBuilder & build, OperationState & result, CmpIPredicate predicate, Value lhs, Value rhs) static
Definition at line 626 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
collapseBranch()
static LogicalResult collapseBranch (Block *& successor, ValueRange & successorOperands, SmallVectorImpl< Value > & argStorage) static
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
If the successor is collapsable, successor and successorOperands are updated to reference the new destination and values. argStorage is used as storage if operands to the collapsed successor need to be remapped. It must outlive uses of successorOperands.
Definition at line 447 of file Ops.cpp.
References mlir::Block::args_empty(), mlir::Block::begin(), mlir::Value::dyn_cast(), mlir::Block::end(), mlir::failure(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArguments(), mlir::BlockArgument::getOwner(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), and mlir::success().
Referenced by mlir::applyCmpPredicate(), simplifyPassThroughBr(), and simplifyPassThroughSwitch().
dispatchIndexOpFoldResult()
static void dispatchIndexOpFoldResult (OpFoldResult ofr, SmallVectorImpl< Value > & dynamicVec, SmallVectorImpl< int64_t > & staticVec, int64_t sentinel) static
Helper function to dispatch an OpFoldResult into either the dynamicVec if it is a Value or into staticVec if it is an IntegerAttr.
In the case of a Value, a copy of the sentinel value is also pushed to staticVec. This is useful to extract mixed static and dynamic entries that come from an AttrSizedOperandSegments trait.
Definition at line 42 of file Ops.cpp.
Referenced by dispatchIndexOpFoldResults().
dispatchIndexOpFoldResults()
static void dispatchIndexOpFoldResults (ArrayRef< OpFoldResult > ofrs, SmallVectorImpl< Value > & dynamicVec, SmallVectorImpl< int64_t > & staticVec, int64_t sentinel) static
Definition at line 55 of file Ops.cpp.
References dispatchIndexOpFoldResult().
Referenced by foldIdentityOffsetSizeAndStrideOpInterface(), and verify().
dropSwitchCasesThatMatchDefault()
static LogicalResult dropSwitchCasesThatMatchDefault (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb1, 43: ^bb2 ] -> switch flag : i32, [ default: ^bb1, 43: ^bb2 ]
Definition at line 2396 of file Ops.cpp.
References mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
extractFromI64ArrayAttr()
static SmallVector<int64_t, 4> extractFromI64ArrayAttr (Attribute attr) static
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
Definition at line 279 of file Ops.cpp.
References mlir::Attribute::cast(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::m_ConstantInt(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
Referenced by verify().
foldIdentityOffsetSizeAndStrideOpInterface()
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType) static
Definition at line 2024 of file Ops.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::tensor::canFoldIntoConsumerOp(), mlir::canonicalizeSubViewPart(), mlir::OpBuilder::create(), dispatchIndexOpFoldResults(), mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexAttr(), mlir::ShapedType::getShape(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::isEqualConstantIntOrValue(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
foldSwitch()
static void foldSwitch (SwitchOp op, PatternRewriter & rewriter, APInt caseValue) static
Helper for folding a switch with a constant value.
switch c_42 : i32, [ default: ^bb1 , 42: ^bb2, 43: ^bb3 ] -> br ^bb2
Definition at line 2431 of file Ops.cpp.
References mlir::RewriterBase::replaceOpWithNewOp().
Referenced by simplifyConstSwitchValue(), and simplifySwitchFromSwitchOnSameCondition().
getCanonicalSubTensorResultType()
static RankedTensorType getCanonicalSubTensorResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Infer the canonical type of the result of a subtensor operation.
Returns a type with rank resultRank that is either the rank of the rank-reduced type, or the non-rank-reduced type.
Definition at line 1923 of file Ops.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::failure(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by SubTensorReturnTypeCanonicalizer::operator()().
getI1SameShape()
static Type getI1SameShape (Type type) static
Definition at line 611 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getContext(), mlir::Type::isa(), and vectorType().
Referenced by buildCmpFOp(), buildCmpIOp(), and verify().
isRankReducedType()
static SubTensorVerificationResult isRankReducedType (Type originalType, Type candidateReducedType, std::string * errMsg = nullptr) static
Checks if original Type type can be rank reduced to reduced type.
This function is slight variant of is subsequence algorithm where not matching dimension must be 1.
Definition at line 1846 of file Ops.cpp.
References mlir::Type::cast(), mlir::computeRankReductionMask(), ElemTypeMismatch, mlir::ShapedType::getElementType(), mlir::ShapedType::getShape(), mlir::Type::isa(), RankTooLarge, SizeMismatch, and Success.
Referenced by verify().
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 972 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
parseGenericAtomicRMWOp()
static ParseResult parseGenericAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 395 of file Ops.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, mlir::success(), and mlir::OperationState::types.
parseSelectOp()
static ParseResult parseSelectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1374 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::succeeded().
parseSwitchOpCases()
static ParseResult parseSwitchOpCases (OpAsmParser & parser, Type & flagType, Block *& defaultDestination, SmallVectorImpl< OpAsmParser::OperandType > & defaultOperands, SmallVectorImpl< Type > & defaultOperandTypes, DenseIntElementsAttr & caseValues, SmallVectorImpl< Block *> & caseDestinations, SmallVectorImpl< OpAsmParser::OperandType > & caseOperands, SmallVectorImpl< Type > & caseOperandTypes, DenseIntElementsAttr & caseOperandOffsets) static
<cases> ::= default : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)*
Definition at line 2222 of file Ops.cpp.
References mlir::failed(), mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Type::getIntOrFloatBitWidth(), mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseInteger(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseSuccessor(), mlir::succeeded(), and mlir::success().
print() [1/3]
static void print (OpAsmPrinter & p, GenericAtomicRMWOp op) static
Definition at line 417 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [2/3]
static void print (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 959 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/3]
static void print (OpAsmPrinter & p, SelectOp op) static
Definition at line 1365 of file Ops.cpp.
References mlir::Type::dyn_cast(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardBinaryOp()
static void printStandardBinaryOp (Operation * op, OpAsmPrinter & p) static
A custom binary operation printer that omits the "std." prefix from the operation names.
Definition at line 161 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardCastOp()
static void printStandardCastOp (Operation * op, OpAsmPrinter & p) static
A custom cast operation printer that omits the "std." prefix from the operation names.
Definition at line 211 of file Ops.cpp.
References mlir::OpBuilder::create(), mlir::Operation::getName(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), mlir::Value::getType(), and materializeConstant().
printStandardTernaryOp()
static void printStandardTernaryOp (Operation * op, OpAsmPrinter & p) static
A custom ternary operation printer that omits the "std." prefix from the operation names.
Definition at line 185 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardUnaryOp()
static void printStandardUnaryOp (Operation * op, OpAsmPrinter & p) static
A custom unary operation printer that omits the "std." prefix from the operation names.
Definition at line 148 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::OperationName::getStringRef(), mlir::Value::getType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printSwitchOpCases()
static void printSwitchOpCases (OpAsmPrinter & p, SwitchOp op, Type flagType, Block * defaultDestination, OperandRange defaultOperands, TypeRange defaultOperandTypes, DenseIntElementsAttr caseValues, SuccessorRange caseDestinations, OperandRange caseOperands, TypeRange caseOperandTypes, ElementsAttr caseOperandOffsets) static
Definition at line 2280 of file Ops.cpp.
References mlir::OpAsmPrinter::printNewline(), and mlir::OpAsmPrinter::printSuccessorAndUseList().
produceSubTensorErrorMsg()
template<typename OpTy > static LogicalResult produceSubTensorErrorMsg (SubTensorVerificationResult result, OpTy op, Type expectedType, StringRef errMsg = "") static
Definition at line 1889 of file Ops.cpp.
References mlir::Type::cast(), ElemTypeMismatch, RankTooLarge, SizeMismatch, mlir::success(), and Success.
Referenced by verify().
signedCeilNonnegInputs()
static APInt signedCeilNonnegInputs (APInt a, APInt b, bool & overflow) static
Definition at line 1475 of file Ops.cpp.
References areVectorCastSimpleCompatible(), mlir::ceil(), mlir::Type::isa(), and mlir::Type::isSignlessInteger().
simplifyBrToBlockWithSinglePred()
static LogicalResult simplifyBrToBlockWithSinglePred (BranchOp op, PatternRewriter & rewriter) static
Simplify a branch to a block that has a single predecessor.
This effectively merges the two blocks.
Definition at line 493 of file Ops.cpp.
References mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Block::getPredecessors(), mlir::RewriterBase::mergeBlocks(), and mlir::success().
Referenced by simplifyPassThroughBr().
simplifyConstSwitchValue()
static LogicalResult simplifyConstSwitchValue (SwitchOp op, PatternRewriter & rewriter) static
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, 43: ^bb3 ] -> br ^bb2
Definition at line 2451 of file Ops.cpp.
References mlir::failure(), foldSwitch(), mlir::m_ConstantInt(), mlir::matchPattern(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifyPassThroughBr()
static LogicalResult simplifyPassThroughBr (BranchOp op, PatternRewriter & rewriter) static
br ^bb1 ^bb1 br ^bbN(...)
-> br ^bbN(...)
Definition at line 512 of file Ops.cpp.
References collapseBranch(), mlir::failed(), mlir::failure(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), simplifyBrToBlockWithSinglePred(), mlir::succeeded(), and mlir::success().
simplifyPassThroughSwitch()
static LogicalResult simplifyPassThroughSwitch (SwitchOp op, PatternRewriter & rewriter) static
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3 -> switch c_42 : i32, [ default: ^bb1, 42: ^bb3, ]
Definition at line 2472 of file Ops.cpp.
References collapseBranch(), mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifySwitchFromDefaultSwitchOnSameCondition()
static LogicalResult simplifySwitchFromDefaultSwitchOnSameCondition (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb2 ] ^bb1: switch flag : i32, [ default: ^bb3, 42: ^bb4, 43: ^bb5 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb1: switch flag : i32, [ default: ^bb3, 43: ^bb5 ]
Definition at line 2601 of file Ops.cpp.
References mlir::RewritePatternSet::add(), dropSwitchCasesThatMatchDefault(), mlir::failure(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::RewriterBase::replaceOpWithNewOp(), simplifyConstSwitchValue(), simplifyPassThroughSwitch(), simplifySwitchFromSwitchOnSameCondition(), simplifySwitchWithOnlyDefault(), and mlir::success().
simplifySwitchFromSwitchOnSameCondition()
static LogicalResult simplifySwitchFromSwitchOnSameCondition (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 42: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb4
and
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 43: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3
Definition at line 2544 of file Ops.cpp.
References mlir::failure(), foldSwitch(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifySwitchWithOnlyDefault()
static LogicalResult simplifySwitchWithOnlyDefault (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1 ] -> br ^bb1
Definition at line 2375 of file Ops.cpp.
References mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
verify() [1/12]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 324 of file Ops.cpp.
References mlir::Region::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), elementType(), mlir::Value::getType(), mlir::Region::push_back(), and mlir::success().
verify() [2/12]
static LogicalResult verify (GenericAtomicRMWOp op) static
Definition at line 374 of file Ops.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failure(), hasSideEffects(), mlir::WalkResult::interrupt(), and mlir::success().
verify() [3/12]
static LogicalResult verify (AtomicYieldOp op) static
Definition at line 428 of file Ops.cpp.
References mlir::success().
verify() [4/12]
static LogicalResult verify (ConstantOp & op) static
The constant op requires an attribute, and furthermore requires that it matches the return type.
Definition at line 992 of file Ops.cpp.
References mlir::Type::cast(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::Type::isa(), and mlir::success().
verify() [5/12]
static LogicalResult verify (ReturnOp op) static
Definition at line 1304 of file Ops.cpp.
References mlir::edsc::op::eq(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::edsc::op::ne(), and mlir::success().
verify() [6/12]
static LogicalResult verify (SelectOp op) static
Definition at line 1397 of file Ops.cpp.
References getI1SameShape(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), and mlir::success().
verify() [7/12]
static LogicalResult verify (SignExtendIOp op) static
Definition at line 1422 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), and mlir::success().
verify() [8/12]
static LogicalResult verify (SplatOp op) static
Definition at line 1622 of file Ops.cpp.
References mlir::OperationState::addAttributes(), areVectorCastSimpleCompatible(), mlir::Type::cast(), dispatchIndexOpFoldResults(), mlir::DenseElementsAttr::get(), getElementType(), mlir::Builder::getI64ArrayAttr(), mlir::getPositionsOfShapeOne(), mlir::Value::getType(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [9/12]
static LogicalResult verify (SubTensorOp op) static
Verifier for SubTensorOp.
Definition at line 1910 of file Ops.cpp.
References extractFromI64ArrayAttr(), isRankReducedType(), and produceSubTensorErrorMsg().
verify() [10/12]
static LogicalResult verify (SwitchOp op) static
Definition at line 2303 of file Ops.cpp.
References mlir::Attribute::cast(), mlir::ElementsAttr::getValue(), mlir::ElementsAttr::size(), mlir::MutableOperandRange::size(), and mlir::success().
verify() [11/12]
static LogicalResult verify (TruncateIOp op) static
Definition at line 2665 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), mlir::Builder::getZeroAttr(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [12/12]
static LogicalResult verify (ZeroExtendIOp op) static
Definition at line 2767 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), and mlir::success().