MLIR: mlir::vector::PointwiseExtractPattern Struct Reference
mlir::vector::PointwiseExtractPattern Struct Reference
Canonicalize an extra element using the result of a pointwise operation.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintType = std::function< LogicalResult(ExtractMapOp op)>
Public Member Functions
PointwiseExtractPattern (MLIRContext *context, FilterConstraintType constraint=[](ExtractMapOp op) { return success();})
LogicalResult matchAndRewrite (ExtractMapOp extract, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< ExtractMapOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< ExtractMapOp >
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (ExtractMapOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (ExtractMapOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Canonicalize an extra element using the result of a pointwise operation.
Transforms: v = addf a, b : vector32xf32> dv = vector.extract_map v, id, 32 : vector<32xf32> into vector<1xf32> to: da = vector.extract_map a, id, 32 : vector<32xf32> into vector<1xf32> db = vector.extract_map a, id, 32 : vector<32xf32> into vector<1xf32> dv = addf da, db : vector<1xf32>
Definition at line 262 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintType
using mlir::vector::PointwiseExtractPattern::FilterConstraintType = std::function<LogicalResult(ExtractMapOp op)>
Definition at line 263 of file VectorTransforms.h.
Constructor & Destructor Documentation
PointwiseExtractPattern()
mlir::vector::PointwiseExtractPattern::PointwiseExtractPattern (MLIRContext * context, FilterConstraintType constraint = [](ExtractMapOp op) { return success(); }) inline
Definition at line 264 of file VectorTransforms.h.
References mlir::success(), and mlir::vector::transferOpflowOpt().
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::vector::PointwiseExtractPattern::matchAndRewrite (ExtractMapOp extract, PatternRewriter & rewriter) const override virtual
Reimplemented from mlir::detail::OpOrInterfaceRewritePatternBase< ExtractMapOp >.
Definition at line 2666 of file VectorTransforms.cpp.
References cloneOpWithOperandsAndTypes(), mlir::OpBuilder::create(), mlir::failure(), mlir::Operation::getNumResults(), mlir::Operation::getOpOperands(), mlir::Operation::getResult(), mlir::RewriterBase::replaceOp(), and mlir::success().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Vector/VectorTransforms.h
lib/Dialect/Vector/VectorTransforms.cpp