MLIR: mlir::linalg::GenerateLoopNest< LoopTy > Struct Template Reference
mlir::linalg::GenerateLoopNest< LoopTy > Struct Template Reference
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
#include "mlir/Dialect/Linalg/Utils/Utils.h"
Public Types
using IndexedValueTy = typename std::conditional< std::is_same< LoopTy, AffineForOp >::value, edsc::intrinsics::AffineIndexedValue, edsc::intrinsics::MemRefIndexedValue >::type
Public Member Functions
template<>
void doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions)
Specialization to build an scf "for" nest.
template<>
void doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >)
Specialization to build affine "for" nest.
template<>
void doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >)
Specialization to build an linalg.tiled_loop.
template<>
void doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions)
Specialization for generating a mix of parallel and sequential scf loops.
Static Public Member Functions
static void doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >=None)
Detailed Description
template<typename LoopTy>
struct mlir::linalg::GenerateLoopNest< LoopTy >
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
bodyBuilderFn is used to generate the body of the innermost loop. It is passed a range of loop induction variables.
Definition at line 249 of file Utils.h.
Member Typedef Documentation
IndexedValueTy
template<typename LoopTy> using mlir::linalg::GenerateLoopNest< LoopTy >::IndexedValueTy = typename std::conditional<std::is_same<LoopTy, AffineForOp>::value, edsc::intrinsics::AffineIndexedValue, edsc::intrinsics::MemRefIndexedValue>::type
Definition at line 253 of file Utils.h.
Member Function Documentation
doit() [1/5]
template<> void mlir::linalg::GenerateLoopNest< scf::ForOp >::doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions)
Specialization to build an scf "for" nest.
Definition at line 199 of file Utils.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), mlir::edsc::loopNestBuilder(), mlir::scf::LoopNest::loops, mlir::mapLoopToProcessorIds(), and unpackRanges().
doit() [2/5]
template<> void mlir::linalg::GenerateLoopNest< AffineForOp >::doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >)
Specialization to build affine "for" nest.
Definition at line 230 of file Utils.cpp.
References mlir::edsc::affineLoopNestBuilder(), and unpackRanges().
doit() [3/5]
template<typename LoopTy> static void mlir::linalg::GenerateLoopNest< LoopTy >::doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > = None) static
doit() [4/5]
template<> void mlir::linalg::GenerateLoopNest< TiledLoopOp >::doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions >)
Specialization to build an linalg.tiled_loop.
Definition at line 258 of file Utils.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getArrayAttr(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), and unpackRanges().
doit() [5/5]
template<> void mlir::linalg::GenerateLoopNest< scf::ParallelOp >::doit (ArrayRef< Range > loopRanges, LinalgOp linalgOp, ArrayRef< Attribute > iteratorTypes, function_ref< scf::ValueVector(ValueRange, ValueRange)> bodyBuilderFn, Optional< LinalgLoopDistributionOptions > distributionOptions)
Specialization for generating a mix of parallel and sequential scf loops.
Definition at line 426 of file Utils.cpp.
References mlir::detail::enumerate(), mlir::linalg::generateParallelLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), mlir::linalg::isParallelIteratorType(), options, unpackRanges(), and mlir::linalg::updateBoundsForCyclicDistribution().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/Utils/Utils.h