MLIR: lib/Dialect/Tensor/IR/TensorDialect.cpp File Reference
TensorDialect.cpp File Reference
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/Tensor/IR/TensorAttrDefs.cpp.inc"
#include "mlir/Dialect/Tensor/IR/TensorOps.cpp.inc"
Macros
#define GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_LIST
#define GET_OP_LIST
Functions
static constexpr StringRef getSparseDimLevelTypeAttrName ()
static constexpr StringRef getSparseDimOrderingAttrName ()
static constexpr StringRef getSparsePointerBitWidthAttrName ()
static constexpr StringRef getSparseIndexBitWidthAttrName ()
static constexpr StringRef getDenseDimLevelTypeVal ()
static constexpr StringRef getCompressedDimLevelTypeVal ()
static constexpr StringRef getSingletonDimLevelTypeVal ()
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 21 of file TensorDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getCompressedDimLevelTypeVal()
static constexpr StringRef getCompressedDimLevelTypeVal () static
Definition at line 40 of file TensorDialect.cpp.
Referenced by getSingletonDimLevelTypeVal().
getDenseDimLevelTypeVal()
static constexpr StringRef getDenseDimLevelTypeVal () static
Definition at line 39 of file TensorDialect.cpp.
Referenced by getSingletonDimLevelTypeVal().
getSingletonDimLevelTypeVal()
static constexpr StringRef getSingletonDimLevelTypeVal () static
Definition at line 43 of file TensorDialect.cpp.
References mlir::DialectInlinerInterface::DialectInlinerInterface(), elementType(), mlir::DialectAsmParser::emitError(), mlir::emitError(), mlir::failed(), getCompressedDimLevelTypeVal(), getDenseDimLevelTypeVal(), mlir::DialectAsmParser::getNameLoc(), mlir::AffineMap::getNumResults(), getSparseDimLevelTypeAttrName(), getSparseDimOrderingAttrName(), getSparseIndexBitWidthAttrName(), getSparsePointerBitWidthAttrName(), isLegalToInline(), mlir::AffineMap::isPermutation(), mlir::parseAttribute(), mlir::DialectAsmParser::parseAttribute(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseKeyword(), mlir::DialectAsmParser::parseLess(), print(), mlir::succeeded(), and mlir::success().
getSparseDimLevelTypeAttrName()
static constexpr StringRef getSparseDimLevelTypeAttrName () static
Definition at line 25 of file TensorDialect.cpp.
Referenced by getSingletonDimLevelTypeVal().
getSparseDimOrderingAttrName()
static constexpr StringRef getSparseDimOrderingAttrName () static
Definition at line 28 of file TensorDialect.cpp.
Referenced by getSingletonDimLevelTypeVal().
getSparseIndexBitWidthAttrName()
static constexpr StringRef getSparseIndexBitWidthAttrName () static
Definition at line 34 of file TensorDialect.cpp.
Referenced by getSingletonDimLevelTypeVal().
getSparsePointerBitWidthAttrName()
static constexpr StringRef getSparsePointerBitWidthAttrName () static
Definition at line 31 of file TensorDialect.cpp.
Referenced by getSingletonDimLevelTypeVal().