MLIR: lib/Dialect/Vector/VectorTransforms.cpp File Reference
VectorTransforms.cpp File Reference
#include <type_traits>
#include "mlir/Dialect/Affine/EDSC/Builders.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/EDSC/Intrinsics.h"
#include "mlir/Dialect/MemRef/EDSC/Intrinsics.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorTransforms.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Types.h"
#include "mlir/Interfaces/VectorInterfaces.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct UnrolledVectorState
struct VectorState
struct TransferReadExtractPattern
struct TransferWriteInsertPattern
struct TransferReadToVectorLoadLowering
Progressive lowering of transfer_read.
struct TransferWriteToVectorStoreLowering
Progressive lowering of transfer_write.
struct TransferReadPermutationLowering
Lower transfer_read op with permutation into a transfer_read with a permutation map composed of leading zeros followed by a minor identiy + vector.transpose op.
struct TransferOpReduceRank
Lower transfer_read op with broadcast in the leading dimensions into transfer_read of lower rank + vector.broadcast.
struct CastAwayExtractStridedSliceLeadingOneDim
struct CastAwayInsertStridedSliceLeadingOneDim
struct CastAwayTransferReadLeadingOneDim
struct CastAwayTransferWriteLeadingOneDim
struct BubbleDownVectorBitCastForExtract
struct BubbleDownBitCastForStridedSliceExtract
struct BubbleUpBitCastForStridedSliceInsert
struct MaterializeTransferMask< ConcreteOp >
class VectorCreateMaskOpConversion
Conversion pattern for a vector.create_mask (1-D only).
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "vector-to-vector"
Functions
static Optional< int64_t > getResultIndex (AffineMap map, int64_t index)
static SmallVector< Attribute, 4 > adjustIter (ArrayAttr iteratorTypes, int64_t index)
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter &rewriter)
static Type adjustType (VectorType tp, int64_t index)
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Operation * cloneOpWithOperandsAndTypes (OpBuilder &builder, Location loc, Operation *op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes)
static void getMappedElements (const DenseMap< int64_t, int64_t > &indexMap, ArrayRef< int64_t > inputElements, SmallVectorImpl< int64_t > &resultElements)
static TupleType generateExtractSlicesOpResultType (VectorType vectorType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, OpBuilder &builder)
static void initUnrolledVectorState (VectorType vectorType, Value initValue, const DenseMap< int64_t, int64_t > &indexMap, ArrayRef< int64_t > targetShape, UnrolledVectorState &state, OpBuilder &builder)
static int64_t getUnrolledVectorLinearIndex (UnrolledVectorState &state, ArrayRef< int64_t > vectorOffsets, DenseMap< int64_t, int64_t > &indexMap)
static Value getOrCreateUnrolledVectorSlice (Location loc, UnrolledVectorState &state, ArrayRef< int64_t > vectorOffsets, ArrayRef< int64_t > offsets, DenseMap< int64_t, int64_t > &indexMap, Value initValue, SmallVectorImpl< Value > &cache, OpBuilder &builder)
static Value unrollSingleResultStructuredOp (Operation *op, ArrayRef< int64_t > iterationBounds, std::vector< VectorState > &vectors, unsigned resultIndex, ArrayRef< int64_t > targetShape, OpBuilder &builder)
static void getVectorContractionOpUnrollState (vector::ContractionOp contractionOp, ArrayRef< int64_t > targetShape, std::vector< VectorState > &vectors, unsigned &resultIndex)
static void getVectorElementwiseOpUnrollState (Operation *op, ArrayRef< int64_t > targetShape, std::vector< VectorState > &vectors, unsigned &resultIndex)
static void generateTransferOpSlices (Type shapedElementType, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, ArrayRef< Value > indices, OpBuilder &builder, function_ref< void(unsigned, ArrayRef< Value >)> fn)
Generates slices of 'vectorType' according to 'sizes' and 'strides, and calls 'fn' with linear index and indices for each slice.
static bool isIdentitySuffix (AffineMap map)
Returns true if 'map' is a suffix of an identity affine map, false otherwise.
static Value unrollTransferReadOp (vector::TransferReadOp readOp, ArrayRef< int64_t > targetShape, OpBuilder &builder)
Unroll transfer_read ops to the given shape and create an aggregate with all the chunks.
static Value createAdd (Location loc, Value x, Value y, bool isInt, PatternRewriter &rewriter)
Creates an AddIOp if isInt is true otherwise create an AddFOp using operands x and y.
static Value createMul (Location loc, Value x, Value y, bool isInt, PatternRewriter &rewriter)
Creates a MulIOp if isInt is true otherwise create an MulFOp using operands x andy`.
static Optional< int64_t > extractConstantIndex (Value v)
static Value createScopedFoldedSLE (Value v, Value ub)
static Value createScopedInBoundsCond (VectorTransferOpInterface xferOp)
static MemRefType getCastCompatibleMemRefType (MemRefType aT, MemRefType bT)
Given two MemRefTypes aT and bT, return a MemRefType to which both can be cast.
static Value createScopedSubViewIntersection (VectorTransferOpInterface xferOp, Value alloc)
Operates under a scoped context to build the intersection between the view xferOp.source() @ xferOp.indices() and the view alloc.
static scf::IfOp createScopedFullPartialLinalgCopy (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
static scf::IfOp createScopedFullPartialVectorTransferRead (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
static VectorType trimLeadingOneDims (VectorType oldType)
static SmallVector< int64_t, 4 > getIntValueVector (ArrayAttr arrayAttr)
static Value createCastToIndexLike (PatternRewriter &rewriter, Location loc, Type targetType, Value value)
static Value buildVectorComparison (PatternRewriter &rewriter, Operation *op, bool enableIndexOptimizations, int64_t dim, Value b, Value *off=nullptr)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-to-vector"
Definition at line 47 of file VectorTransforms.cpp.
Function Documentation
adjustIter()
static SmallVector<Attribute, 4> adjustIter (ArrayAttr iteratorTypes, int64_t index) static
Definition at line 62 of file VectorTransforms.cpp.
References mlir::detail::enumerate().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
adjustMap()
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter & rewriter) static
Definition at line 75 of file VectorTransforms.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumDims(), and mlir::AffineMap::getNumResults().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
adjustType()
static Type adjustType (VectorType tp, int64_t index) static
Definition at line 92 of file VectorTransforms.cpp.
Referenced by reshapeLoad(), and reshapeStore().
buildVectorComparison()
static Value buildVectorComparison (PatternRewriter & rewriter, Operation * op, bool enableIndexOptimizations, int64_t dim, Value b, Value * off = nullptr) static
Definition at line 3469 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), createCastToIndexLike(), mlir::Builder::getI32Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Operation::getLoc(), mlir::Value::getType(), and mlir::edsc::op::slt().
Referenced by MaterializeTransferMask< ConcreteOp >::matchAndRewrite(), and VectorCreateMaskOpConversion::matchAndRewrite().
cloneOpWithOperandsAndTypes()
static Operation* cloneOpWithOperandsAndTypes (OpBuilder & builder, Location loc, Operation * op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes) static
Definition at line 167 of file VectorTransforms.cpp.
References mlir::OpBuilder::createOperation(), mlir::Operation::getAttrs(), mlir::Operation::getName(), and mlir::OperationName::getStringRef().
Referenced by mlir::vector::PointwiseExtractPattern::matchAndRewrite(), and unrollSingleResultStructuredOp().
createAdd()
static Value createAdd (Location loc, Value x, Value y, bool isInt, PatternRewriter & rewriter) static
Creates an AddIOp if isInt is true otherwise create an AddFOp using operands x and y.
Definition at line 1734 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::ContractionOpToDotLowering::matchAndRewrite(), and mlir::ContractionOpLowering::matchAndRewrite().
createCastToIndexLike()
static Value createCastToIndexLike (PatternRewriter & rewriter, Location loc, Type targetType, Value value) static
Definition at line 3441 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::Value::getType(), and mlir::Type::isIndex().
Referenced by buildVectorComparison().
createMul()
static Value createMul (Location loc, Value x, Value y, bool isInt, PatternRewriter & rewriter) static
Creates a MulIOp if isInt is true otherwise create an MulFOp using operands x andy`.
Definition at line 1743 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::ContractionOpToDotLowering::matchAndRewrite(), and mlir::ContractionOpLowering::matchAndRewrite().
createScopedFoldedSLE()
static Value createScopedFoldedSLE (Value v, Value ub) static
Definition at line 2305 of file VectorTransforms.cpp.
References extractConstantIndex(), and mlir::edsc::op::sle().
Referenced by createScopedInBoundsCond().
createScopedFullPartialLinalgCopy()
static scf::IfOp createScopedFullPartialLinalgCopy (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   memref.cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %2 = linalg.fill(%alloc, %pad)
   %3 = subview %view [...][...][...]
   linalg.copy(%3, %alloc)
   memref.cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %4, ... : compatibleMemRefType, index, index
}
Return the produced scf::IfOp.
Definition at line 2449 of file VectorTransforms.cpp.
References mlir::edsc::conditionBuilder(), and createScopedSubViewIntersection().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createScopedFullPartialVectorTransferRead()
static scf::IfOp createScopedFullPartialVectorTransferRead (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   memref.cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %2 = vector.transfer_read %view[...], %pad : memref<A...>, vector<...>
   %3 = vector.type_cast %extra_alloc :
     memref<...> to memref<vector<...>>
   store %2, %3[] : memref<vector<...>>
   %4 = memref.cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %4, ... : compatibleMemRefType, index, index
}
Return the produced scf::IfOp.
Definition at line 2503 of file VectorTransforms.cpp.
References mlir::Operation::clone(), mlir::edsc::conditionBuilder(), and mlir::Value::getType().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createScopedInBoundsCond()
static Value createScopedInBoundsCond (VectorTransferOpInterface xferOp) static
Definition at line 2316 of file VectorTransforms.cpp.
References createScopedFoldedSLE().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createScopedSubViewIntersection()
static Value createScopedSubViewIntersection (VectorTransferOpInterface xferOp, Value alloc) static
Operates under a scoped context to build the intersection between the view xferOp.source() @ xferOp.indices() and the view alloc.
Definition at line 2399 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::Type::cast(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), and mlir::AffineMap::inferFromExprList().
Referenced by createScopedFullPartialLinalgCopy().
extractConstantIndex()
static Optional<int64_t> extractConstantIndex (Value v) static
Definition at line 2293 of file VectorTransforms.cpp.
References mlir::Value::getDefiningOp().
Referenced by applyMapToValues(), and createScopedFoldedSLE().
generateExtractSlicesOpResultType()
static TupleType generateExtractSlicesOpResultType (VectorType vectorType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, OpBuilder & builder) static
Definition at line 194 of file VectorTransforms.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeMaxLinearIndex(), mlir::computeSliceSizes(), mlir::computeStrides(), mlir::delinearize(), mlir::Builder::getTupleType(), and mlir::shapeRatio().
Referenced by initUnrolledVectorState(), unrollTransferReadOp(), and mlir::vector::unrollTransferWriteOp().
generateTransferOpSlices()
static void generateTransferOpSlices (Type shapedElementType, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, ArrayRef< Value > indices, OpBuilder & builder, function_ref< void(unsigned, ArrayRef< Value >)> fn) static
Generates slices of 'vectorType' according to 'sizes' and 'strides, and calls 'fn' with linear index and indices for each slice.
Definition at line 519 of file VectorTransforms.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeStrides(), mlir::OpBuilder::create(), mlir::delinearize(), mlir::Type::dyn_cast(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), and mlir::shapeRatio().
Referenced by mlir::vector::unrollSingleResultVectorOp(), unrollTransferReadOp(), and mlir::vector::unrollTransferWriteOp().
getCastCompatibleMemRefType()
static MemRefType getCastCompatibleMemRefType (MemRefType aT, MemRefType bT) static
Given two MemRefTypes aT and bT, return a MemRefType to which both can be cast.
If the MemRefTypes don't have the same rank or are not strided, return null; otherwise:
if aT and bT are cast-compatible, return aT.
else return a new MemRefType obtained by iterating over the shape and strides and: a. keeping the ones that are static and equal across aT and bT. b. using a dynamic shape and/or stride for the dimensions that don't agree.
Definition at line 2366 of file VectorTransforms.cpp.
References mlir::failed(), mlir::getStridesAndOffset(), and mlir::makeStridedLinearLayoutMap().
Referenced by mlir::vector::splitFullAndPartialTransfer().
getIntValueVector()
static SmallVector<int64_t, 4> getIntValueVector (ArrayAttr arrayAttr) static
Definition at line 3204 of file VectorTransforms.cpp.
Referenced by BubbleDownBitCastForStridedSliceExtract::matchAndRewrite(), and BubbleUpBitCastForStridedSliceInsert::matchAndRewrite().
getMappedElements()
static void getMappedElements (const DenseMap< int64_t, int64_t > & indexMap, ArrayRef< int64_t > inputElements, SmallVectorImpl< int64_t > & resultElements) static
Definition at line 178 of file VectorTransforms.cpp.
Referenced by getOrCreateUnrolledVectorSlice(), getUnrolledVectorLinearIndex(), and initUnrolledVectorState().
getOrCreateUnrolledVectorSlice()
static Value getOrCreateUnrolledVectorSlice (Location loc, UnrolledVectorState & state, ArrayRef< int64_t > vectorOffsets, ArrayRef< int64_t > offsets, DenseMap< int64_t, int64_t > & indexMap, Value initValue, SmallVectorImpl< Value > & cache, OpBuilder & builder) static
Definition at line 279 of file VectorTransforms.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Builder::getI64IntegerAttr(), getMappedElements(), mlir::Value::getType(), getUnrolledVectorLinearIndex(), UnrolledVectorState::slicesTuple, UnrolledVectorState::unrolledShape, and vectorType().
Referenced by unrollSingleResultStructuredOp().
getResultIndex()
static Optional<int64_t> getResultIndex (AffineMap map, int64_t index) static
Definition at line 52 of file VectorTransforms.cpp.
References mlir::AffineMap::getDimPosition(), and mlir::AffineMap::getNumResults().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
getUnrolledVectorLinearIndex()
static int64_t getUnrolledVectorLinearIndex (UnrolledVectorState & state, ArrayRef< int64_t > vectorOffsets, DenseMap< int64_t, int64_t > & indexMap) static
Definition at line 266 of file VectorTransforms.cpp.
References UnrolledVectorState::basis, getMappedElements(), mlir::linearize(), and UnrolledVectorState::unrolledShape.
Referenced by getOrCreateUnrolledVectorSlice(), and unrollSingleResultStructuredOp().
getVectorContractionOpUnrollState()
static void getVectorContractionOpUnrollState (vector::ContractionOp contractionOp, ArrayRef< int64_t > targetShape, std::vector< VectorState > & vectors, unsigned & resultIndex) static
Definition at line 459 of file VectorTransforms.cpp.
Referenced by mlir::vector::unrollSingleResultVectorOp().
getVectorElementwiseOpUnrollState()
static void getVectorElementwiseOpUnrollState (Operation * op, ArrayRef< int64_t > targetShape, std::vector< VectorState > & vectors, unsigned & resultIndex) static
Definition at line 488 of file VectorTransforms.cpp.
References mlir::Type::dyn_cast_or_null(), mlir::detail::enumerate(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), getShape(), and mlir::Value::getType().
Referenced by mlir::vector::unrollSingleResultVectorOp().
initUnrolledVectorState()
static void initUnrolledVectorState (VectorType vectorType, Value initValue, const DenseMap< int64_t, int64_t > & indexMap, ArrayRef< int64_t > targetShape, UnrolledVectorState & state, OpBuilder & builder) static
Definition at line 235 of file VectorTransforms.cpp.
References UnrolledVectorState::basis, mlir::computeMaxLinearIndex(), mlir::computeStrides(), mlir::OpBuilder::create(), generateExtractSlicesOpResultType(), mlir::Value::getLoc(), getMappedElements(), UnrolledVectorState::numInstances, mlir::shapeRatio(), UnrolledVectorState::slicesTuple, UnrolledVectorState::unrolledShape, and UnrolledVectorState::unrollFactors.
Referenced by unrollSingleResultStructuredOp().
isIdentitySuffix()
static bool isIdentitySuffix (AffineMap map) static
Returns true if 'map' is a suffix of an identity affine map, false otherwise.
Example: affine_map<(d0, d1, d2, d3) -> (d2, d3)>
Definition at line 575 of file VectorTransforms.cpp.
References mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResults().
Referenced by mlir::vector::unrollSingleResultVectorOp(), unrollTransferReadOp(), and mlir::vector::unrollTransferWriteOp().
reshapeLoad()
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 112 of file VectorTransforms.cpp.
References adjustType(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), and mlir::Builder::getZeroAttr().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
reshapeStore()
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 140 of file VectorTransforms.cpp.
References adjustType(), mlir::OpBuilder::create(), and mlir::Builder::getI64ArrayAttr().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
trimLeadingOneDims()
static VectorType trimLeadingOneDims (VectorType oldType) static
Definition at line 3019 of file VectorTransforms.cpp.
Referenced by CastAwayExtractStridedSliceLeadingOneDim::matchAndRewrite(), CastAwayInsertStridedSliceLeadingOneDim::matchAndRewrite(), CastAwayTransferReadLeadingOneDim::matchAndRewrite(), and CastAwayTransferWriteLeadingOneDim::matchAndRewrite().
unrollSingleResultStructuredOp()
static Value unrollSingleResultStructuredOp (Operation * op, ArrayRef< int64_t > iterationBounds, std::vector< VectorState > & vectors, unsigned resultIndex, ArrayRef< int64_t > targetShape, OpBuilder & builder) static
Definition at line 369 of file VectorTransforms.cpp.
References mlir::Type::cast(), cloneOpWithOperandsAndTypes(), mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeMaxLinearIndex(), mlir::computeStrides(), mlir::OpBuilder::create(), mlir::delinearize(), mlir::Type::dyn_cast_or_null(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), getOrCreateUnrolledVectorSlice(), mlir::Operation::getResult(), mlir::Builder::getTupleType(), mlir::Value::getType(), getUnrolledVectorLinearIndex(), initUnrolledVectorState(), resultIndex(), and mlir::shapeRatio().
Referenced by mlir::vector::unrollSingleResultVectorOp().
unrollTransferReadOp()
static Value unrollTransferReadOp (vector::TransferReadOp readOp, ArrayRef< int64_t > targetShape, OpBuilder & builder) static
Unroll transfer_read ops to the given shape and create an aggregate with all the chunks.
Definition at line 594 of file VectorTransforms.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), generateExtractSlicesOpResultType(), generateTransferOpSlices(), getElementType(), mlir::Builder::getI64ArrayAttr(), and isIdentitySuffix().
Referenced by mlir::vector::unrollSingleResultVectorOp().